package documents

import "github.com/open-rails/authkit/internal/errmodel"

// Document error codes on the one AuthKit error model (ak#290): each sentinel
// is an *errmodel.Error (= authkit.Error) with its catalogued status.
var (
	CodeInvalidReference     = errmodel.Define("invalid_document_reference", 400, "The document reference is invalid.")
	CodeInvalidType          = errmodel.Define("invalid_document_type", 400, "The document type is invalid.")
	CodeInvalidDigest        = errmodel.Define("invalid_document_digest", 400, "The document digest is invalid.")
	CodeDuplicateReference   = errmodel.Define("duplicate_document_reference", 400, "The document reference is duplicated.")
	CodeTooManyReferences    = errmodel.Define("too_many_document_references", 400, "Too many document references.")
	CodeReferencesTooLarge   = errmodel.Define("document_references_too_large", 400, "The document references are too large.")
	CodeWrongTokenType       = errmodel.Define("documents_wrong_token_type", 400, "The token type is wrong for documents.")
	CodeReservedAttribute    = errmodel.Define("reserved_document_attribute", 400, "The document uses a reserved attribute.")
	CodeInvalidEnvelope      = errmodel.Define("invalid_document_envelope", 400, "The document envelope is invalid.")
	CodePayloadTooLarge      = errmodel.Define("document_payload_too_large", 400, "The document payload is too large.")
	CodeMalformedJWS         = errmodel.Define("malformed_document_jws", 400, "The document JWS is malformed.")
	CodeWrongJOSEType        = errmodel.Define("wrong_document_jose_type", 400, "The document JOSE type is wrong.")
	CodeUnsupportedAlgorithm = errmodel.Define("unsupported_document_algorithm", 400, "The document algorithm is not supported.")
	CodeUnsupportedSigner    = errmodel.Define("unsupported_document_signer", 400, "The document signer is not supported.")
	CodeUnknownKey           = errmodel.Define("unknown_document_key", 400, "The document names an unknown key.")
	CodeInvalidSignature     = errmodel.Define("invalid_document_signature", 400, "The document signature is invalid.")
	CodeDigestMismatch       = errmodel.Define("document_digest_mismatch", 400, "The document digest does not match.")
	CodeIssuerMismatch       = errmodel.Define("document_issuer_mismatch", 400, "The document issuer does not match.")
	CodeAudienceMismatch     = errmodel.Define("document_audience_mismatch", 400, "The document audience does not match.")
	CodeTypeMismatch         = errmodel.Define("document_type_mismatch", 400, "The document type does not match.")
	CodeUntrustedIssuer      = errmodel.Define("untrusted_document_issuer", 403, "The document issuer is not trusted.")
	CodeUnauthorized         = errmodel.Define("document_unauthorized", 401, "The document request is not authorized.")
	CodeNotFound             = errmodel.Define("document_not_found", 404, "The document was not found.")
	CodeFetch                = errmodel.Define("document_fetch_failed", 502, "The document could not be fetched.")
	CodeRedirect             = errmodel.Define("document_redirect_rejected", 502, "The document redirect was rejected.")
	CodeDigestCollision      = errmodel.Define("document_digest_collision", 409, "A different document already exists under that digest.")
)

var (
	ErrInvalidReference     = errmodel.E(CodeInvalidReference)
	ErrInvalidType          = errmodel.E(CodeInvalidType)
	ErrInvalidDigest        = errmodel.E(CodeInvalidDigest)
	ErrDuplicateReference   = errmodel.E(CodeDuplicateReference)
	ErrTooManyReferences    = errmodel.E(CodeTooManyReferences)
	ErrReferencesTooLarge   = errmodel.E(CodeReferencesTooLarge)
	ErrWrongTokenType       = errmodel.E(CodeWrongTokenType)
	ErrReservedAttribute    = errmodel.E(CodeReservedAttribute)
	ErrInvalidEnvelope      = errmodel.E(CodeInvalidEnvelope)
	ErrPayloadTooLarge      = errmodel.E(CodePayloadTooLarge)
	ErrMalformedJWS         = errmodel.E(CodeMalformedJWS)
	ErrWrongJOSEType        = errmodel.E(CodeWrongJOSEType)
	ErrUnsupportedAlgorithm = errmodel.E(CodeUnsupportedAlgorithm)
	ErrUnsupportedSigner    = errmodel.E(CodeUnsupportedSigner)
	ErrUnknownKey           = errmodel.E(CodeUnknownKey)
	ErrInvalidSignature     = errmodel.E(CodeInvalidSignature)
	ErrDigestMismatch       = errmodel.E(CodeDigestMismatch)
	ErrIssuerMismatch       = errmodel.E(CodeIssuerMismatch)
	ErrAudienceMismatch     = errmodel.E(CodeAudienceMismatch)
	ErrTypeMismatch         = errmodel.E(CodeTypeMismatch)
	ErrUntrustedIssuer      = errmodel.E(CodeUntrustedIssuer)
	ErrUnauthorized         = errmodel.E(CodeUnauthorized)
	ErrNotFound             = errmodel.E(CodeNotFound)
	ErrFetch                = errmodel.E(CodeFetch)
	ErrRedirect             = errmodel.E(CodeRedirect)
	ErrDigestCollision      = errmodel.E(CodeDigestCollision)
)
