version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - "/"
      - "/adapters/gin"
      - "/adapters/riverjobs"
    schedule:
      interval: weekly
    groups:
      go-minor-patch:
        update-types: [minor, patch]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
