// Code generated by internal/genremote; DO NOT EDIT.

package server

import (
	"context"
	"encoding/json"
	"net"
	"time"

	authkit "github.com/open-rails/authkit"
)

// generatedMethods is the management-API dispatch table, one entry per
// authkit.Client method.
var generatedMethods = map[string]MethodFunc{
	// types referenced below pin the net/time imports
	"AdminCountUsers": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 authkit.AdminUserListOptions `json:"opts"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.AdminCountUsers(ctx, a.A0)
		return r0, err
	},
	"AdminGetUser": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"id"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.AdminGetUser(ctx, a.A0)
		return r0, err
	},
	"AdminListUserSessions": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.AdminListUserSessions(ctx, a.A0)
		return r0, err
	},
	"AdminListUsers": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 authkit.AdminUserListOptions `json:"opts"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.AdminListUsers(ctx, a.A0)
		return r0, err
	},
	"AdminRevokeUserSessions": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.AdminRevokeUserSessions(ctx, a.A0)
	},
	"AdminSetPassword": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
			A1 string `json:"new"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.AdminSetPassword(ctx, a.A0, a.A1)
	},
	"ApplyBootstrapManifest": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 authkit.BootstrapManifest         `json:"manifest"`
			A1 authkit.BootstrapReconcileOptions `json:"opts"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ApplyBootstrapManifest(ctx, a.A0, a.A1)
		return r0, err
	},
	"AssignGroupRole": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"persona"`
			A1 string `json:"instanceSlug"`
			A2 string `json:"subjectID"`
			A3 string `json:"subjectKind"`
			A4 string `json:"role"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.AssignGroupRole(ctx, a.A0, a.A1, a.A2, a.A3, a.A4)
	},
	"AssignGroupRoleAs": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"actorUserID"`
			A1 string `json:"persona"`
			A2 string `json:"instanceSlug"`
			A3 string `json:"subjectID"`
			A4 string `json:"subjectKind"`
			A5 string `json:"role"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.AssignGroupRoleAs(ctx, a.A0, a.A1, a.A2, a.A3, a.A4, a.A5)
	},
	"AssignRoleBySlug": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
			A1 string `json:"slug"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.AssignRoleBySlug(ctx, a.A0, a.A1)
	},
	"AssignRoleBySlugAs": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"actorUserID"`
			A1 string `json:"userID"`
			A2 string `json:"slug"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.AssignRoleBySlugAs(ctx, a.A0, a.A1, a.A2)
	},
	"BanUser": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string     `json:"userID"`
			A1 *string    `json:"reason"`
			A2 *time.Time `json:"until"`
			A3 string     `json:"bannedBy"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.BanUser(ctx, a.A0, a.A1, a.A2, a.A3)
	},
	"Can": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"subjectID"`
			A1 string `json:"subjectKind"`
			A2 string `json:"persona"`
			A3 string `json:"instanceSlug"`
			A4 string `json:"perm"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.Can(ctx, a.A0, a.A1, a.A2, a.A3, a.A4)
		return r0, err
	},
	"ChangePassword": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string  `json:"userID"`
			A1 string  `json:"current"`
			A2 string  `json:"new"`
			A3 *string `json:"keepSessionID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.ChangePassword(ctx, a.A0, a.A1, a.A2, a.A3)
	},
	"CheckSMSHealth": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		return nil, c.CheckSMSHealth(ctx)
	},
	"CleanupExpiredAuthState": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		return nil, c.CleanupExpiredAuthState(ctx)
	},
	"ClearPasswordlessCodeAttempts": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"identifier"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		c.ClearPasswordlessCodeAttempts(ctx, a.A0)
		return nil, nil
	},
	"ConfirmPasswordlessCode": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"identifier"`
			A1 string `json:"code"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ConfirmPasswordlessCode(ctx, a.A0, a.A1)
		return r0, err
	},
	"ConfirmPasswordlessToken": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"token"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ConfirmPasswordlessToken(ctx, a.A0)
		return r0, err
	},
	"CreateAccountRegistrationInvite": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 authkit.CreateAccountRegistrationInviteRequest `json:"req"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.CreateAccountRegistrationInvite(ctx, a.A0)
		return r0, err
	},
	"CreateGroupInviteLink": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 authkit.CreateGroupInviteLinkRequest `json:"req"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.CreateGroupInviteLink(ctx, a.A0)
		return r0, err
	},
	"CreatePermissionGroup": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 authkit.CreatePermissionGroupRequest `json:"req"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.CreatePermissionGroup(ctx, a.A0)
		return r0, err
	},
	"CreateUser": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"email"`
			A1 string `json:"username"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.CreateUser(ctx, a.A0, a.A1)
		return r0, err
	},
	"DeleteRemoteApplication": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"issuer"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.DeleteRemoteApplication(ctx, a.A0)
	},
	"EnsureRootGroup": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		r0, err := c.EnsureRootGroup(ctx)
		return r0, err
	},
	"ExchangeRefreshToken": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"refreshToken"`
			A1 string `json:"ua"`
			A2 net.IP `json:"ip"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, r1, r2, err := c.ExchangeRefreshToken(ctx, a.A0, a.A1, a.A2)
		return map[string]any{"r0": r0, "r1": r1, "r2": r2}, err
	},
	"ExternalInvitesEnabled": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		return c.ExternalInvitesEnabled(), nil
	},
	"GetProviderUsername": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
			A1 string `json:"provider"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.GetProviderUsername(ctx, a.A0, a.A1)
		return r0, err
	},
	"GetRemoteApplication": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"issuer"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.GetRemoteApplication(ctx, a.A0)
		return r0, err
	},
	"GetUserByEmail": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"email"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.GetUserByEmail(ctx, a.A0)
		return r0, err
	},
	"GetUserByPhone": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"phone"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.GetUserByPhone(ctx, a.A0)
		return r0, err
	},
	"GetUserBySolanaAddress": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"address"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.GetUserBySolanaAddress(ctx, a.A0)
		return r0, err
	},
	"GetUserByUsername": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"username"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.GetUserByUsername(ctx, a.A0)
		return r0, err
	},
	"GetUserMetadata": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.GetUserMetadata(ctx, a.A0)
		return r0, err
	},
	"HardDeleteUser": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.HardDeleteUser(ctx, a.A0)
	},
	"HasEmailSender": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		return c.HasEmailSender(), nil
	},
	"HasSMSSender": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		return c.HasSMSSender(), nil
	},
	"ImportUsers": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 []authkit.ImportUserInput `json:"inputs"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ImportUsers(ctx, a.A0)
		return r0, err
	},
	"IsUserAllowed": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.IsUserAllowed(ctx, a.A0)
		return r0, err
	},
	"IssueAccessToken": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string         `json:"userID"`
			A1 string         `json:"email"`
			A2 map[string]any `json:"extra"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, r1, err := c.IssueAccessToken(ctx, a.A0, a.A1, a.A2)
		return map[string]any{"r0": r0, "r1": r1}, err
	},
	"LeaveGroup": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
			A1 string `json:"persona"`
			A2 string `json:"instanceSlug"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.LeaveGroup(ctx, a.A0, a.A1, a.A2)
	},
	"LinkProvider": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string  `json:"userID"`
			A1 string  `json:"provider"`
			A2 string  `json:"subject"`
			A3 *string `json:"email"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.LinkProvider(ctx, a.A0, a.A1, a.A2, a.A3)
	},
	"LinkProviderByIssuer": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string  `json:"userID"`
			A1 string  `json:"issuer"`
			A2 string  `json:"providerSlug"`
			A3 string  `json:"subject"`
			A4 *string `json:"email"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.LinkProviderByIssuer(ctx, a.A0, a.A1, a.A2, a.A3, a.A4)
	},
	"ListAPIKeys": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"persona"`
			A1 string `json:"instanceSlug"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ListAPIKeys(ctx, a.A0, a.A1)
		return r0, err
	},
	"ListEffectivePermissions": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"subjectID"`
			A1 string `json:"subjectKind"`
			A2 string `json:"persona"`
			A3 string `json:"instanceSlug"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ListEffectivePermissions(ctx, a.A0, a.A1, a.A2, a.A3)
		return r0, err
	},
	"ListEntitlements": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return c.ListEntitlements(ctx, a.A0), nil
	},
	"ListGroupInviteLinks": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"persona"`
			A1 string `json:"instanceSlug"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ListGroupInviteLinks(ctx, a.A0, a.A1)
		return r0, err
	},
	"ListGroupMembers": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"persona"`
			A1 string `json:"instanceSlug"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ListGroupMembers(ctx, a.A0, a.A1)
		return r0, err
	},
	"ListRemoteApplications": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 bool `json:"activeOnly"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ListRemoteApplications(ctx, a.A0)
		return r0, err
	},
	"ListRoleSlugsByUser": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return c.ListRoleSlugsByUser(ctx, a.A0), nil
	},
	"ListRoleSlugsByUserErr": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ListRoleSlugsByUserErr(ctx, a.A0)
		return r0, err
	},
	"ListSubjectGroups": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"subjectID"`
			A1 string `json:"subjectKind"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ListSubjectGroups(ctx, a.A0, a.A1)
		return r0, err
	},
	"ListUserSessions": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ListUserSessions(ctx, a.A0)
		return r0, err
	},
	"ListUsersDeletedBefore": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 time.Time `json:"cutoff"`
			A1 int       `json:"limit"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ListUsersDeletedBefore(ctx, a.A0, a.A1)
		return r0, err
	},
	"MintAPIKey": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string     `json:"persona"`
			A1 string     `json:"instanceSlug"`
			A2 string     `json:"name"`
			A3 string     `json:"role"`
			A4 string     `json:"createdBy"`
			A5 *time.Time `json:"expiresAt"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, r1, err := c.MintAPIKey(ctx, a.A0, a.A1, a.A2, a.A3, a.A4, a.A5)
		return map[string]any{"r0": r0, "r1": r1}, err
	},
	"MintAPIKeyWithOptions": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string                    `json:"persona"`
			A1 string                    `json:"instanceSlug"`
			A2 authkit.APIKeyMintOptions `json:"opts"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, r1, err := c.MintAPIKeyWithOptions(ctx, a.A0, a.A1, a.A2)
		return map[string]any{"r0": r0, "r1": r1}, err
	},
	"MintCustomJWT": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 authkit.CustomJWTMintOptions `json:"opts"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.MintCustomJWT(ctx, a.A0)
		return r0, err
	},
	"MintDelegatedAccessToken": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 authkit.DelegatedAccessParams `json:"p"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.MintDelegatedAccessToken(ctx, a.A0)
		return r0, err
	},
	"MintRemoteApplicationAccessToken": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 authkit.RemoteApplicationAccessParams `json:"p"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.MintRemoteApplicationAccessToken(ctx, a.A0)
		return r0, err
	},
	"MintServiceJWT": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 authkit.ServiceJWTMintOptions `json:"opts"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, r1, err := c.MintServiceJWT(ctx, a.A0)
		return map[string]any{"r0": r0, "r1": r1}, err
	},
	"PatchUserMetadata": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string         `json:"userID"`
			A1 map[string]any `json:"patch"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.PatchUserMetadata(ctx, a.A0, a.A1)
	},
	"RecordFailedPasswordlessCode": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"identifier"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		c.RecordFailedPasswordlessCode(ctx, a.A0)
		return nil, nil
	},
	"RedeemGroupInviteLink": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"code"`
			A1 string `json:"redeemerUserID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.RedeemGroupInviteLink(ctx, a.A0, a.A1)
		return r0, err
	},
	"RemoveGroupSubjectAs": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"actorUserID"`
			A1 string `json:"persona"`
			A2 string `json:"instanceSlug"`
			A3 string `json:"subjectID"`
			A4 string `json:"subjectKind"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.RemoveGroupSubjectAs(ctx, a.A0, a.A1, a.A2, a.A3, a.A4)
	},
	"RemoveRoleBySlug": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
			A1 string `json:"slug"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.RemoveRoleBySlug(ctx, a.A0, a.A1)
	},
	"RemoveRoleBySlugAs": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"actorUserID"`
			A1 string `json:"userID"`
			A2 string `json:"slug"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.RemoveRoleBySlugAs(ctx, a.A0, a.A1, a.A2)
	},
	"ResolveAPIKey": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"keyID"`
			A1 string `json:"secret"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, r1, err := c.ResolveAPIKey(ctx, a.A0, a.A1)
		return map[string]any{"r0": r0, "r1": r1}, err
	},
	"ResolveAPIKeyDetailed": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"keyID"`
			A1 string `json:"secret"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ResolveAPIKeyDetailed(ctx, a.A0, a.A1)
		return r0, err
	},
	"ResolveGroupIDForSlug": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"persona"`
			A1 string `json:"instanceSlug"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ResolveGroupIDForSlug(ctx, a.A0, a.A1)
		return r0, err
	},
	"ResolveRemoteAppAttributeDef": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"appID"`
			A1 string `json:"key"`
			A2 int32  `json:"version"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ResolveRemoteAppAttributeDef(ctx, a.A0, a.A1, a.A2)
		return r0, err
	},
	"ResolveRemoteApplicationAuthority": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"appID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.ResolveRemoteApplicationAuthority(ctx, a.A0)
		return r0, err
	},
	"RestoreUser": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"id"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.RestoreUser(ctx, a.A0)
	},
	"RevokeAPIKey": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"persona"`
			A1 string `json:"instanceSlug"`
			A2 string `json:"tokenID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.RevokeAPIKey(ctx, a.A0, a.A1, a.A2)
		return r0, err
	},
	"RevokeAccountRegistrationInvite": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"inviteID"`
			A1 string `json:"actorUserID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.RevokeAccountRegistrationInvite(ctx, a.A0, a.A1)
	},
	"RevokeAllSessions": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string  `json:"userID"`
			A1 *string `json:"keepSessionID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.RevokeAllSessions(ctx, a.A0, a.A1)
	},
	"RevokeGroupInviteLink": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"persona"`
			A1 string `json:"instanceSlug"`
			A2 string `json:"linkID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.RevokeGroupInviteLink(ctx, a.A0, a.A1, a.A2)
	},
	"SMSAvailable": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		return c.SMSAvailable(), nil
	},
	"SeedPermissionGroupContainment": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		return nil, c.SeedPermissionGroupContainment(ctx)
	},
	"SetEmailVerified": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"id"`
			A1 bool   `json:"v"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.SetEmailVerified(ctx, a.A0, a.A1)
	},
	"SoftDeleteUser": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"id"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.SoftDeleteUser(ctx, a.A0)
	},
	"StartPasswordless": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 authkit.PasswordlessStartRequest `json:"req"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.StartPasswordless(ctx, a.A0)
		return r0, err
	},
	"TimeUntilUsernameRenameAvailable": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string    `json:"userID"`
			A1 time.Time `json:"now"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.TimeUntilUsernameRenameAvailable(ctx, a.A0, a.A1)
		return r0, err
	},
	"UnassignGroupRoleAs": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"actorUserID"`
			A1 string `json:"persona"`
			A2 string `json:"instanceSlug"`
			A3 string `json:"subjectID"`
			A4 string `json:"subjectKind"`
			A5 string `json:"role"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.UnassignGroupRoleAs(ctx, a.A0, a.A1, a.A2, a.A3, a.A4, a.A5)
	},
	"UnbanUser": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.UnbanUser(ctx, a.A0)
	},
	"UnlinkProvider": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
			A1 string `json:"provider"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.UnlinkProvider(ctx, a.A0, a.A1)
	},
	"UpdateBiography": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string  `json:"id"`
			A1 *string `json:"bio"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.UpdateBiography(ctx, a.A0, a.A1)
	},
	"UpdateEmail": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"id"`
			A1 string `json:"email"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.UpdateEmail(ctx, a.A0, a.A1)
	},
	"UpdateImportedUser": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string                  `json:"userID"`
			A1 authkit.ImportUserInput `json:"input"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.UpdateImportedUser(ctx, a.A0, a.A1)
		return r0, err
	},
	"UpdateUsername": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"id"`
			A1 string `json:"username"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.UpdateUsername(ctx, a.A0, a.A1)
	},
	"UpsertPasswordHash": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
			A1 string `json:"hash"`
			A2 string `json:"algo"`
			A3 []byte `json:"params"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.UpsertPasswordHash(ctx, a.A0, a.A1, a.A2, a.A3)
	},
	"UpsertRemoteApplication": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 authkit.RemoteApplication `json:"in"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.UpsertRemoteApplication(ctx, a.A0)
		return r0, err
	},
	"UpsertRoleBySlug": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string  `json:"name"`
			A1 string  `json:"slug"`
			A2 *string `json:"description"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return nil, c.UpsertRoleBySlug(ctx, a.A0, a.A1, a.A2)
	},
	"UsersByIDs": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 []string `json:"ids"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		r0, err := c.UsersByIDs(ctx, a.A0)
		return r0, err
	},
	"ValidateVerificationConfiguration": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		return nil, c.ValidateVerificationConfiguration()
	},
	"VerifyUserPassword": func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {
		var a struct {
			A0 string `json:"userID"`
			A1 string `json:"pass"`
		}
		if err := decodeArgs(raw, &a); err != nil {
			return nil, err
		}
		return c.VerifyUserPassword(ctx, a.A0, a.A1), nil
	},
}

// pin imports used only by some signatures.
var (
	_ net.IP
	_ time.Time
)
