// Command contract writes AuthKit's error-code catalog and the e2e server's
// mounted route catalog into src/client/generated.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime/debug"
	"sort"

	authkit "github.com/open-rails/authkit"

	"github.com/open-rails/auth-ui/e2e/server/harness"
)

const authkitModule = "github.com/open-rails/authkit"

type errorCode struct {
	Code   string `json:"code"`
	Status int    `json:"status"`
}

type route struct {
	Method     string `json:"method"`
	Path       string `json:"path"`
	Group      string `json:"group"`
	Auth       string `json:"auth"`
	Permission string `json:"permission,omitempty"`
}

type contract struct {
	AuthKitVersion string      `json:"authkit_version"`
	ErrorCodes     []errorCode `json:"error_codes"`
	Routes         []route     `json:"routes"`
}

func main() {
	out := flag.String("out", "../../src/client/generated", "output directory")
	dsn := flag.String("dsn", os.Getenv("DATABASE_URL"), "migratable Postgres DSN")
	flag.Parse()
	if err := run(*out, *dsn); err != nil {
		log.Fatal(err)
	}
}

func run(out, dsn string) error {
	version := authkitVersion()
	pool, err := harness.Open(context.Background(), dsn)
	if err != nil {
		return err
	}
	defer pool.Close()
	rt, err := harness.New("http://localhost", pool)
	if err != nil {
		return err
	}
	defer rt.Close()

	c := contract{AuthKitVersion: version}
	for _, code := range authkit.Codes() {
		status, _, _ := authkit.DescribeCode(code)
		c.ErrorCodes = append(c.ErrorCodes, errorCode{Code: code.String(), Status: status})
	}
	for _, r := range rt.Mount.Routes() {
		c.Routes = append(c.Routes, route{Method: r.Method, Path: r.Path, Group: string(r.Group), Auth: string(r.Auth), Permission: string(r.Permission)})
	}
	sort.Slice(c.Routes, func(i, j int) bool {
		if c.Routes[i].Path != c.Routes[j].Path {
			return c.Routes[i].Path < c.Routes[j].Path
		}
		return c.Routes[i].Method < c.Routes[j].Method
	})

	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	var js bytes.Buffer
	enc := json.NewEncoder(&js)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(c); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(out, "authkit-contract.json"), js.Bytes(), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(out, "error-codes.ts"), errorCodesTS(c), 0o644)
}

func errorCodesTS(c contract) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Generated by `pnpm contract` from AuthKit %s. Do not edit.\n\n", c.AuthKitVersion)
	fmt.Fprintf(&b, "export const AUTHKIT_VERSION = %q\n\n", c.AuthKitVersion)
	b.WriteString("export type AuthErrorCode =\n")
	for _, e := range c.ErrorCodes {
		fmt.Fprintf(&b, "  | %q\n", e.Code)
	}
	b.WriteString("\nexport const AUTH_ERROR_STATUS: Readonly<Record<AuthErrorCode, number>> = {\n")
	for _, e := range c.ErrorCodes {
		fmt.Fprintf(&b, "  %q: %d,\n", e.Code, e.Status)
	}
	b.WriteString("}\n")
	return b.Bytes()
}

func authkitVersion() string {
	if info, ok := debug.ReadBuildInfo(); ok {
		for _, dep := range info.Deps {
			if dep.Path == authkitModule {
				if dep.Replace != nil {
					return dep.Replace.Version
				}
				return dep.Version
			}
		}
	}
	return "unknown"
}
