// Code generated by internal/genremote; DO NOT EDIT.

package remote

import (
	"context"
	"net"
	"time"

	authkit "github.com/open-rails/authkit"
)

func (c *Client) AdminCountUsers(ctx context.Context, opts authkit.AdminUserListOptions) (int64, error) {
	args := map[string]any{"opts": opts}
	var out int64
	err := c.call(ctx, "AdminCountUsers", args, &out)
	return out, err
}

func (c *Client) AdminGetUser(ctx context.Context, id string) (*authkit.AdminUser, error) {
	args := map[string]any{"id": id}
	var out *authkit.AdminUser
	err := c.call(ctx, "AdminGetUser", args, &out)
	return out, err
}

func (c *Client) AdminListUserSessions(ctx context.Context, userID string) ([]authkit.Session, error) {
	args := map[string]any{"userID": userID}
	var out []authkit.Session
	err := c.call(ctx, "AdminListUserSessions", args, &out)
	return out, err
}

func (c *Client) AdminListUsers(ctx context.Context, opts authkit.AdminUserListOptions) (*authkit.AdminListUsersResult, error) {
	args := map[string]any{"opts": opts}
	var out *authkit.AdminListUsersResult
	err := c.call(ctx, "AdminListUsers", args, &out)
	return out, err
}

func (c *Client) AdminRevokeUserSessions(ctx context.Context, userID string) error {
	args := map[string]any{"userID": userID}
	return c.call(ctx, "AdminRevokeUserSessions", args, nil)
}

func (c *Client) AdminSetPassword(ctx context.Context, userID string, new string) error {
	args := map[string]any{"userID": userID, "new": new}
	return c.call(ctx, "AdminSetPassword", args, nil)
}

func (c *Client) ApplyBootstrapManifest(ctx context.Context, manifest authkit.BootstrapManifest, opts authkit.BootstrapReconcileOptions) (authkit.BootstrapManifestResult, error) {
	args := map[string]any{"manifest": manifest, "opts": opts}
	var out authkit.BootstrapManifestResult
	err := c.call(ctx, "ApplyBootstrapManifest", args, &out)
	return out, err
}

func (c *Client) AssignGroupRole(ctx context.Context, persona string, instanceSlug string, subjectID string, subjectKind string, role string) error {
	args := map[string]any{"persona": persona, "instanceSlug": instanceSlug, "subjectID": subjectID, "subjectKind": subjectKind, "role": role}
	return c.call(ctx, "AssignGroupRole", args, nil)
}

func (c *Client) AssignGroupRoleAs(ctx context.Context, actorUserID string, persona string, instanceSlug string, subjectID string, subjectKind string, role string) error {
	args := map[string]any{"actorUserID": actorUserID, "persona": persona, "instanceSlug": instanceSlug, "subjectID": subjectID, "subjectKind": subjectKind, "role": role}
	return c.call(ctx, "AssignGroupRoleAs", args, nil)
}

func (c *Client) AssignRoleBySlug(ctx context.Context, userID string, slug string) error {
	args := map[string]any{"userID": userID, "slug": slug}
	return c.call(ctx, "AssignRoleBySlug", args, nil)
}

func (c *Client) AssignRoleBySlugAs(ctx context.Context, actorUserID string, userID string, slug string) error {
	args := map[string]any{"actorUserID": actorUserID, "userID": userID, "slug": slug}
	return c.call(ctx, "AssignRoleBySlugAs", args, nil)
}

func (c *Client) BanUser(ctx context.Context, userID string, reason *string, until *time.Time, bannedBy string) error {
	args := map[string]any{"userID": userID, "reason": reason, "until": until, "bannedBy": bannedBy}
	return c.call(ctx, "BanUser", args, nil)
}

func (c *Client) Can(ctx context.Context, subjectID string, subjectKind string, persona string, instanceSlug string, perm string) (bool, error) {
	args := map[string]any{"subjectID": subjectID, "subjectKind": subjectKind, "persona": persona, "instanceSlug": instanceSlug, "perm": perm}
	var out bool
	err := c.call(ctx, "Can", args, &out)
	return out, err
}

func (c *Client) ChangePassword(ctx context.Context, userID string, current string, new string, keepSessionID *string) error {
	args := map[string]any{"userID": userID, "current": current, "new": new, "keepSessionID": keepSessionID}
	return c.call(ctx, "ChangePassword", args, nil)
}

func (c *Client) CheckSMSHealth(ctx context.Context) error {
	return c.call(ctx, "CheckSMSHealth", nil, nil)
}

func (c *Client) CleanupExpiredAuthState(ctx context.Context) error {
	return c.call(ctx, "CleanupExpiredAuthState", nil, nil)
}

func (c *Client) ClearPasswordlessCodeAttempts(ctx context.Context, identifier string) {
	args := map[string]any{"identifier": identifier}
	_ = c.call(ctx, "ClearPasswordlessCodeAttempts", args, nil)
}

func (c *Client) ConfirmPasswordlessCode(ctx context.Context, identifier string, code string) (authkit.PasswordlessConfirmResult, error) {
	args := map[string]any{"identifier": identifier, "code": code}
	var out authkit.PasswordlessConfirmResult
	err := c.call(ctx, "ConfirmPasswordlessCode", args, &out)
	return out, err
}

func (c *Client) ConfirmPasswordlessToken(ctx context.Context, token string) (authkit.PasswordlessConfirmResult, error) {
	args := map[string]any{"token": token}
	var out authkit.PasswordlessConfirmResult
	err := c.call(ctx, "ConfirmPasswordlessToken", args, &out)
	return out, err
}

func (c *Client) CreateAccountRegistrationInvite(ctx context.Context, req authkit.CreateAccountRegistrationInviteRequest) (authkit.AccountRegistrationInviteCreated, error) {
	args := map[string]any{"req": req}
	var out authkit.AccountRegistrationInviteCreated
	err := c.call(ctx, "CreateAccountRegistrationInvite", args, &out)
	return out, err
}

func (c *Client) CreateGroupInviteLink(ctx context.Context, req authkit.CreateGroupInviteLinkRequest) (authkit.GroupInviteLinkCreated, error) {
	args := map[string]any{"req": req}
	var out authkit.GroupInviteLinkCreated
	err := c.call(ctx, "CreateGroupInviteLink", args, &out)
	return out, err
}

func (c *Client) CreatePermissionGroup(ctx context.Context, req authkit.CreatePermissionGroupRequest) (string, error) {
	args := map[string]any{"req": req}
	var out string
	err := c.call(ctx, "CreatePermissionGroup", args, &out)
	return out, err
}

func (c *Client) CreateUser(ctx context.Context, email string, username string) (*authkit.User, error) {
	args := map[string]any{"email": email, "username": username}
	var out *authkit.User
	err := c.call(ctx, "CreateUser", args, &out)
	return out, err
}

func (c *Client) DeleteRemoteApplication(ctx context.Context, issuer string) error {
	args := map[string]any{"issuer": issuer}
	return c.call(ctx, "DeleteRemoteApplication", args, nil)
}

func (c *Client) EnsureRootGroup(ctx context.Context) (string, error) {
	var out string
	err := c.call(ctx, "EnsureRootGroup", nil, &out)
	return out, err
}

func (c *Client) ExchangeRefreshToken(ctx context.Context, refreshToken string, ua string, ip net.IP) (string, time.Time, string, error) {
	args := map[string]any{"refreshToken": refreshToken, "ua": ua, "ip": ip}
	var out struct {
		R0 string    `json:"r0"`
		R1 time.Time `json:"r1"`
		R2 string    `json:"r2"`
	}
	err := c.call(ctx, "ExchangeRefreshToken", args, &out)
	return out.R0, out.R1, out.R2, err
}

func (c *Client) ExternalInvitesEnabled() bool {
	ctx := context.Background()
	var out bool
	err := c.call(ctx, "ExternalInvitesEnabled", nil, &out)
	_ = err
	return out
}

func (c *Client) GetEmailByUserID(ctx context.Context, id string) (string, error) {
	args := map[string]any{"id": id}
	var out string
	err := c.call(ctx, "GetEmailByUserID", args, &out)
	return out, err
}

func (c *Client) GetProviderUsername(ctx context.Context, userID string, provider string) (string, error) {
	args := map[string]any{"userID": userID, "provider": provider}
	var out string
	err := c.call(ctx, "GetProviderUsername", args, &out)
	return out, err
}

func (c *Client) GetRemoteApplication(ctx context.Context, issuer string) (*authkit.RemoteApplication, error) {
	args := map[string]any{"issuer": issuer}
	var out *authkit.RemoteApplication
	err := c.call(ctx, "GetRemoteApplication", args, &out)
	return out, err
}

func (c *Client) GetUserByEmail(ctx context.Context, email string) (*authkit.User, error) {
	args := map[string]any{"email": email}
	var out *authkit.User
	err := c.call(ctx, "GetUserByEmail", args, &out)
	return out, err
}

func (c *Client) GetUserByPhone(ctx context.Context, phone string) (*authkit.User, error) {
	args := map[string]any{"phone": phone}
	var out *authkit.User
	err := c.call(ctx, "GetUserByPhone", args, &out)
	return out, err
}

func (c *Client) GetUserBySolanaAddress(ctx context.Context, address string) (*authkit.User, error) {
	args := map[string]any{"address": address}
	var out *authkit.User
	err := c.call(ctx, "GetUserBySolanaAddress", args, &out)
	return out, err
}

func (c *Client) GetUserByUsername(ctx context.Context, username string) (*authkit.User, error) {
	args := map[string]any{"username": username}
	var out *authkit.User
	err := c.call(ctx, "GetUserByUsername", args, &out)
	return out, err
}

func (c *Client) GetUserMetadata(ctx context.Context, userID string) (map[string]any, error) {
	args := map[string]any{"userID": userID}
	var out map[string]any
	err := c.call(ctx, "GetUserMetadata", args, &out)
	return out, err
}

func (c *Client) HardDeleteUser(ctx context.Context, userID string) error {
	args := map[string]any{"userID": userID}
	return c.call(ctx, "HardDeleteUser", args, nil)
}

func (c *Client) HasEmailSender() bool {
	ctx := context.Background()
	var out bool
	err := c.call(ctx, "HasEmailSender", nil, &out)
	_ = err
	return out
}

func (c *Client) HasSMSSender() bool {
	ctx := context.Background()
	var out bool
	err := c.call(ctx, "HasSMSSender", nil, &out)
	_ = err
	return out
}

func (c *Client) ImportUsers(ctx context.Context, inputs []authkit.ImportUserInput) (authkit.ImportUsersResult, error) {
	args := map[string]any{"inputs": inputs}
	var out authkit.ImportUsersResult
	err := c.call(ctx, "ImportUsers", args, &out)
	return out, err
}

func (c *Client) IsUserAllowed(ctx context.Context, userID string) (bool, error) {
	args := map[string]any{"userID": userID}
	var out bool
	err := c.call(ctx, "IsUserAllowed", args, &out)
	return out, err
}

func (c *Client) IssueAccessToken(ctx context.Context, userID string, email string, extra map[string]any) (string, time.Time, error) {
	args := map[string]any{"userID": userID, "email": email, "extra": extra}
	var out struct {
		R0 string    `json:"r0"`
		R1 time.Time `json:"r1"`
	}
	err := c.call(ctx, "IssueAccessToken", args, &out)
	return out.R0, out.R1, err
}

func (c *Client) LinkProvider(ctx context.Context, userID string, provider string, subject string, email *string) error {
	args := map[string]any{"userID": userID, "provider": provider, "subject": subject, "email": email}
	return c.call(ctx, "LinkProvider", args, nil)
}

func (c *Client) LinkProviderByIssuer(ctx context.Context, userID string, issuer string, providerSlug string, subject string, email *string) error {
	args := map[string]any{"userID": userID, "issuer": issuer, "providerSlug": providerSlug, "subject": subject, "email": email}
	return c.call(ctx, "LinkProviderByIssuer", args, nil)
}

func (c *Client) ListAPIKeys(ctx context.Context, persona string, instanceSlug string) ([]authkit.APIKey, error) {
	args := map[string]any{"persona": persona, "instanceSlug": instanceSlug}
	var out []authkit.APIKey
	err := c.call(ctx, "ListAPIKeys", args, &out)
	return out, err
}

func (c *Client) ListEffectivePermissions(ctx context.Context, subjectID string, subjectKind string, persona string, instanceSlug string) ([]string, error) {
	args := map[string]any{"subjectID": subjectID, "subjectKind": subjectKind, "persona": persona, "instanceSlug": instanceSlug}
	var out []string
	err := c.call(ctx, "ListEffectivePermissions", args, &out)
	return out, err
}

func (c *Client) ListEntitlements(ctx context.Context, userID string) []string {
	args := map[string]any{"userID": userID}
	var out []string
	err := c.call(ctx, "ListEntitlements", args, &out)
	_ = err
	return out
}

func (c *Client) ListGroupInviteLinks(ctx context.Context, persona string, instanceSlug string) ([]authkit.GroupInviteLink, error) {
	args := map[string]any{"persona": persona, "instanceSlug": instanceSlug}
	var out []authkit.GroupInviteLink
	err := c.call(ctx, "ListGroupInviteLinks", args, &out)
	return out, err
}

func (c *Client) ListGroupMembers(ctx context.Context, persona string, instanceSlug string) ([]authkit.GroupMember, error) {
	args := map[string]any{"persona": persona, "instanceSlug": instanceSlug}
	var out []authkit.GroupMember
	err := c.call(ctx, "ListGroupMembers", args, &out)
	return out, err
}

func (c *Client) ListRemoteApplications(ctx context.Context, activeOnly bool) ([]authkit.RemoteApplication, error) {
	args := map[string]any{"activeOnly": activeOnly}
	var out []authkit.RemoteApplication
	err := c.call(ctx, "ListRemoteApplications", args, &out)
	return out, err
}

func (c *Client) ListRoleSlugsByUser(ctx context.Context, userID string) []string {
	args := map[string]any{"userID": userID}
	var out []string
	err := c.call(ctx, "ListRoleSlugsByUser", args, &out)
	_ = err
	return out
}

func (c *Client) ListRoleSlugsByUserErr(ctx context.Context, userID string) ([]string, error) {
	args := map[string]any{"userID": userID}
	var out []string
	err := c.call(ctx, "ListRoleSlugsByUserErr", args, &out)
	return out, err
}

func (c *Client) ListSubjectGroups(ctx context.Context, subjectID string, subjectKind string) ([]authkit.SubjectGroupMembership, error) {
	args := map[string]any{"subjectID": subjectID, "subjectKind": subjectKind}
	var out []authkit.SubjectGroupMembership
	err := c.call(ctx, "ListSubjectGroups", args, &out)
	return out, err
}

func (c *Client) ListUserSessions(ctx context.Context, userID string) ([]authkit.Session, error) {
	args := map[string]any{"userID": userID}
	var out []authkit.Session
	err := c.call(ctx, "ListUserSessions", args, &out)
	return out, err
}

func (c *Client) ListUsersDeletedBefore(ctx context.Context, cutoff time.Time, limit int) ([]string, error) {
	args := map[string]any{"cutoff": cutoff, "limit": limit}
	var out []string
	err := c.call(ctx, "ListUsersDeletedBefore", args, &out)
	return out, err
}

func (c *Client) MintAPIKey(ctx context.Context, persona string, instanceSlug string, name string, role string, createdBy string, expiresAt *time.Time) (authkit.APIKey, string, error) {
	args := map[string]any{"persona": persona, "instanceSlug": instanceSlug, "name": name, "role": role, "createdBy": createdBy, "expiresAt": expiresAt}
	var out struct {
		R0 authkit.APIKey `json:"r0"`
		R1 string         `json:"r1"`
	}
	err := c.call(ctx, "MintAPIKey", args, &out)
	return out.R0, out.R1, err
}

func (c *Client) MintAPIKeyWithOptions(ctx context.Context, persona string, instanceSlug string, opts authkit.APIKeyMintOptions) (authkit.APIKey, string, error) {
	args := map[string]any{"persona": persona, "instanceSlug": instanceSlug, "opts": opts}
	var out struct {
		R0 authkit.APIKey `json:"r0"`
		R1 string         `json:"r1"`
	}
	err := c.call(ctx, "MintAPIKeyWithOptions", args, &out)
	return out.R0, out.R1, err
}

func (c *Client) MintCustomJWT(ctx context.Context, opts authkit.CustomJWTMintOptions) (string, error) {
	args := map[string]any{"opts": opts}
	var out string
	err := c.call(ctx, "MintCustomJWT", args, &out)
	return out, err
}

func (c *Client) MintDelegatedAccessToken(ctx context.Context, p authkit.DelegatedAccessParams) (string, error) {
	args := map[string]any{"p": p}
	var out string
	err := c.call(ctx, "MintDelegatedAccessToken", args, &out)
	return out, err
}

func (c *Client) MintRemoteApplicationAccessToken(ctx context.Context, p authkit.RemoteApplicationAccessParams) (string, error) {
	args := map[string]any{"p": p}
	var out string
	err := c.call(ctx, "MintRemoteApplicationAccessToken", args, &out)
	return out, err
}

func (c *Client) MintServiceJWT(ctx context.Context, opts authkit.ServiceJWTMintOptions) (string, authkit.ServiceJWTClaims, error) {
	args := map[string]any{"opts": opts}
	var out struct {
		R0 string                   `json:"r0"`
		R1 authkit.ServiceJWTClaims `json:"r1"`
	}
	err := c.call(ctx, "MintServiceJWT", args, &out)
	return out.R0, out.R1, err
}

func (c *Client) PatchUserMetadata(ctx context.Context, userID string, patch map[string]any) error {
	args := map[string]any{"userID": userID, "patch": patch}
	return c.call(ctx, "PatchUserMetadata", args, nil)
}

func (c *Client) RecordFailedPasswordlessCode(ctx context.Context, identifier string) {
	args := map[string]any{"identifier": identifier}
	_ = c.call(ctx, "RecordFailedPasswordlessCode", args, nil)
}

func (c *Client) RedeemGroupInviteLink(ctx context.Context, code string, redeemerUserID string) (authkit.RedeemGroupInviteLinkResult, error) {
	args := map[string]any{"code": code, "redeemerUserID": redeemerUserID}
	var out authkit.RedeemGroupInviteLinkResult
	err := c.call(ctx, "RedeemGroupInviteLink", args, &out)
	return out, err
}

func (c *Client) RemoveGroupSubjectAs(ctx context.Context, actorUserID string, persona string, instanceSlug string, subjectID string, subjectKind string) error {
	args := map[string]any{"actorUserID": actorUserID, "persona": persona, "instanceSlug": instanceSlug, "subjectID": subjectID, "subjectKind": subjectKind}
	return c.call(ctx, "RemoveGroupSubjectAs", args, nil)
}

func (c *Client) RemoveRoleBySlug(ctx context.Context, userID string, slug string) error {
	args := map[string]any{"userID": userID, "slug": slug}
	return c.call(ctx, "RemoveRoleBySlug", args, nil)
}

func (c *Client) RemoveRoleBySlugAs(ctx context.Context, actorUserID string, userID string, slug string) error {
	args := map[string]any{"actorUserID": actorUserID, "userID": userID, "slug": slug}
	return c.call(ctx, "RemoveRoleBySlugAs", args, nil)
}

func (c *Client) ResolveAPIKey(ctx context.Context, keyID string, secret string) (string, []string, error) {
	args := map[string]any{"keyID": keyID, "secret": secret}
	var out struct {
		R0 string   `json:"r0"`
		R1 []string `json:"r1"`
	}
	err := c.call(ctx, "ResolveAPIKey", args, &out)
	return out.R0, out.R1, err
}

func (c *Client) ResolveAPIKeyDetailed(ctx context.Context, keyID string, secret string) (authkit.ResolvedAPIKey, error) {
	args := map[string]any{"keyID": keyID, "secret": secret}
	var out authkit.ResolvedAPIKey
	err := c.call(ctx, "ResolveAPIKeyDetailed", args, &out)
	return out, err
}

func (c *Client) ResolveGroupIDForSlug(ctx context.Context, persona string, instanceSlug string) (string, error) {
	args := map[string]any{"persona": persona, "instanceSlug": instanceSlug}
	var out string
	err := c.call(ctx, "ResolveGroupIDForSlug", args, &out)
	return out, err
}

func (c *Client) ResolveRemoteAppAttributeDef(ctx context.Context, appID string, key string, version int32) (*authkit.RemoteAppAttributeDef, error) {
	args := map[string]any{"appID": appID, "key": key, "version": version}
	var out *authkit.RemoteAppAttributeDef
	err := c.call(ctx, "ResolveRemoteAppAttributeDef", args, &out)
	return out, err
}

func (c *Client) ResolveRemoteApplicationAuthority(ctx context.Context, appID string) ([]string, error) {
	args := map[string]any{"appID": appID}
	var out []string
	err := c.call(ctx, "ResolveRemoteApplicationAuthority", args, &out)
	return out, err
}

func (c *Client) RestoreUser(ctx context.Context, id string) error {
	args := map[string]any{"id": id}
	return c.call(ctx, "RestoreUser", args, nil)
}

func (c *Client) RevokeAPIKey(ctx context.Context, persona string, instanceSlug string, tokenID string) (bool, error) {
	args := map[string]any{"persona": persona, "instanceSlug": instanceSlug, "tokenID": tokenID}
	var out bool
	err := c.call(ctx, "RevokeAPIKey", args, &out)
	return out, err
}

func (c *Client) RevokeAccountRegistrationInvite(ctx context.Context, inviteID string, actorUserID string) error {
	args := map[string]any{"inviteID": inviteID, "actorUserID": actorUserID}
	return c.call(ctx, "RevokeAccountRegistrationInvite", args, nil)
}

func (c *Client) RevokeAllSessions(ctx context.Context, userID string, keepSessionID *string) error {
	args := map[string]any{"userID": userID, "keepSessionID": keepSessionID}
	return c.call(ctx, "RevokeAllSessions", args, nil)
}

func (c *Client) RevokeGroupInviteLink(ctx context.Context, persona string, instanceSlug string, linkID string) error {
	args := map[string]any{"persona": persona, "instanceSlug": instanceSlug, "linkID": linkID}
	return c.call(ctx, "RevokeGroupInviteLink", args, nil)
}

func (c *Client) SMSAvailable() bool {
	ctx := context.Background()
	var out bool
	err := c.call(ctx, "SMSAvailable", nil, &out)
	_ = err
	return out
}

func (c *Client) SeedPermissionGroupContainment(ctx context.Context) error {
	return c.call(ctx, "SeedPermissionGroupContainment", nil, nil)
}

func (c *Client) SetEmailVerified(ctx context.Context, id string, v bool) error {
	args := map[string]any{"id": id, "v": v}
	return c.call(ctx, "SetEmailVerified", args, nil)
}

func (c *Client) SoftDeleteUser(ctx context.Context, id string) error {
	args := map[string]any{"id": id}
	return c.call(ctx, "SoftDeleteUser", args, nil)
}

func (c *Client) StartPasswordless(ctx context.Context, req authkit.PasswordlessStartRequest) (authkit.PasswordlessStartResult, error) {
	args := map[string]any{"req": req}
	var out authkit.PasswordlessStartResult
	err := c.call(ctx, "StartPasswordless", args, &out)
	return out, err
}

func (c *Client) TimeUntilUsernameRenameAvailable(ctx context.Context, userID string, now time.Time) (int64, error) {
	args := map[string]any{"userID": userID, "now": now}
	var out int64
	err := c.call(ctx, "TimeUntilUsernameRenameAvailable", args, &out)
	return out, err
}

func (c *Client) UnassignGroupRoleAs(ctx context.Context, actorUserID string, persona string, instanceSlug string, subjectID string, subjectKind string, role string) error {
	args := map[string]any{"actorUserID": actorUserID, "persona": persona, "instanceSlug": instanceSlug, "subjectID": subjectID, "subjectKind": subjectKind, "role": role}
	return c.call(ctx, "UnassignGroupRoleAs", args, nil)
}

func (c *Client) UnbanUser(ctx context.Context, userID string) error {
	args := map[string]any{"userID": userID}
	return c.call(ctx, "UnbanUser", args, nil)
}

func (c *Client) UnlinkProvider(ctx context.Context, userID string, provider string) error {
	args := map[string]any{"userID": userID, "provider": provider}
	return c.call(ctx, "UnlinkProvider", args, nil)
}

func (c *Client) UpdateBiography(ctx context.Context, id string, bio *string) error {
	args := map[string]any{"id": id, "bio": bio}
	return c.call(ctx, "UpdateBiography", args, nil)
}

func (c *Client) UpdateEmail(ctx context.Context, id string, email string) error {
	args := map[string]any{"id": id, "email": email}
	return c.call(ctx, "UpdateEmail", args, nil)
}

func (c *Client) UpdateImportedUser(ctx context.Context, userID string, input authkit.ImportUserInput) (*authkit.User, error) {
	args := map[string]any{"userID": userID, "input": input}
	var out *authkit.User
	err := c.call(ctx, "UpdateImportedUser", args, &out)
	return out, err
}

func (c *Client) UpdateUsername(ctx context.Context, id string, username string) error {
	args := map[string]any{"id": id, "username": username}
	return c.call(ctx, "UpdateUsername", args, nil)
}

func (c *Client) UpsertPasswordHash(ctx context.Context, userID string, hash string, algo string, params []byte) error {
	args := map[string]any{"userID": userID, "hash": hash, "algo": algo, "params": params}
	return c.call(ctx, "UpsertPasswordHash", args, nil)
}

func (c *Client) UpsertRemoteApplication(ctx context.Context, in authkit.RemoteApplication) (*authkit.RemoteApplication, error) {
	args := map[string]any{"in": in}
	var out *authkit.RemoteApplication
	err := c.call(ctx, "UpsertRemoteApplication", args, &out)
	return out, err
}

func (c *Client) UpsertRoleBySlug(ctx context.Context, name string, slug string, description *string) error {
	args := map[string]any{"name": name, "slug": slug, "description": description}
	return c.call(ctx, "UpsertRoleBySlug", args, nil)
}

func (c *Client) UsersByIDs(ctx context.Context, ids []string) ([]authkit.UserRef, error) {
	args := map[string]any{"ids": ids}
	var out []authkit.UserRef
	err := c.call(ctx, "UsersByIDs", args, &out)
	return out, err
}

func (c *Client) ValidateVerificationConfiguration() error {
	ctx := context.Background()
	return c.call(ctx, "ValidateVerificationConfiguration", nil, nil)
}

func (c *Client) VerifyUserPassword(ctx context.Context, userID string, pass string) bool {
	args := map[string]any{"userID": userID, "pass": pass}
	var out bool
	err := c.call(ctx, "VerifyUserPassword", args, &out)
	_ = err
	return out
}
