// Command genremote generates the AuthKit remote SDK (authkit/remote) and the
// management-API method registry (authkit/server) from the authkit.Client
// interface in client.go — ONE source of truth for both transports (#142).
//
// Run via `go generate ./...` (see the directive in remote/remote.go). It parses
// client.go with go/ast (stdlib only — no external deps), and for each interface
// method emits:
//   - remote/methods_gen.go: a concrete method that marshals args to the wire and
//     decodes the result, so *remote.Client satisfies authkit.Client.
//   - server/methods_gen.go: a registry entry that decodes args, calls the method
//     on any authkit.Client, and returns the result.
//
// The wire is the generic POST /v1/call/{Method} contract: args are a JSON object
// keyed by parameter name; the result is the single non-error return (or, for
// multi-return methods, an object keyed r0/r1/…). Because both sides are generated
// from the same signatures, the transports cannot drift.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

// builtins are the type idents that must NOT be qualified with the authkit
// package prefix when rendered in the generated (non-authkit) packages.
var builtins = map[string]bool{
	"bool": true, "string": true, "error": true, "any": true,
	"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
	"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true, "uintptr": true,
	"byte": true, "rune": true, "float32": true, "float64": true,
	"complex64": true, "complex128": true,
}

// renderType renders an ast.Expr from client.go (package authkit) as Go source
// usable in the generated packages: bare authkit type idents get the "authkit."
// prefix; builtins and already-qualified selectors (context.Context, time.Time,
// net.IP) are kept as-is.
func renderType(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		if builtins[t.Name] {
			return t.Name
		}
		return "authkit." + t.Name
	case *ast.StarExpr:
		return "*" + renderType(t.X)
	case *ast.ArrayType:
		if t.Len != nil {
			panic("genremote: fixed-size arrays unsupported")
		}
		return "[]" + renderType(t.Elt)
	case *ast.MapType:
		return "map[" + renderType(t.Key) + "]" + renderType(t.Value)
	case *ast.SelectorExpr:
		pkg, ok := t.X.(*ast.Ident)
		if !ok {
			panic("genremote: unexpected selector base")
		}
		return pkg.Name + "." + t.Sel.Name
	case *ast.InterfaceType:
		return "any"
	case *ast.Ellipsis:
		return "..." + renderType(t.Elt)
	}
	panic(fmt.Sprintf("genremote: unhandled type %T", e))
}

// param is one flattened (name, renderedType) argument or result.
type param struct {
	name string
	typ  string
}

type method struct {
	name    string
	params  []param // includes ctx if present
	results []param // includes trailing error if present
	hasCtx  bool
	hasErr  bool
	values  []param // results minus the trailing error
}

func flatten(fl *ast.FieldList) []param {
	var out []param
	if fl == nil {
		return out
	}
	for i, f := range fl.List {
		typ := renderType(f.Type)
		if len(f.Names) == 0 {
			out = append(out, param{name: fmt.Sprintf("r%d", i), typ: typ})
			continue
		}
		for _, n := range f.Names {
			out = append(out, param{name: n.Name, typ: typ})
		}
	}
	return out
}

func parseMethods(file string) []method {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, file, nil, 0)
	if err != nil {
		panic(err)
	}
	var methods []method
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || ts.Name.Name != "Client" {
			return true
		}
		it, ok := ts.Type.(*ast.InterfaceType)
		if !ok {
			return true
		}
		for _, fld := range it.Methods.List {
			ft, ok := fld.Type.(*ast.FuncType)
			if !ok || len(fld.Names) == 0 {
				continue
			}
			m := method{name: fld.Names[0].Name}
			m.params = flatten(ft.Params)
			m.results = flatten(ft.Results)
			if len(m.params) > 0 && m.params[0].typ == "context.Context" {
				m.hasCtx = true
			}
			m.values = m.results
			if n := len(m.results); n > 0 && m.results[n-1].typ == "error" {
				m.hasErr = true
				m.values = m.results[:n-1]
			}
			methods = append(methods, m)
		}
		return false
	})
	sort.Slice(methods, func(i, j int) bool { return methods[i].name < methods[j].name })
	return methods
}

// argParams returns the wire arguments (params minus the leading ctx).
func (m method) argParams() []param {
	if m.hasCtx {
		return m.params[1:]
	}
	return m.params
}

func genRemote(methods []method) []byte {
	var b bytes.Buffer
	b.WriteString(`// Code generated by internal/genremote; DO NOT EDIT.

package remote

import (
	"context"
	"net"
	"time"

	authkit "github.com/open-rails/authkit"
)
`)
	for _, m := range methods {
		// signature — the FULL parameter list (including ctx) so the method
		// matches the interface; only the wire args exclude ctx.
		var sigParams []string
		for _, p := range m.params {
			sigParams = append(sigParams, p.name+" "+p.typ)
		}
		var sigResults []string
		for _, r := range m.results {
			sigResults = append(sigResults, r.typ)
		}
		results := strings.Join(sigResults, ", ")
		if len(sigResults) > 1 {
			results = "(" + results + ")"
		}
		fmt.Fprintf(&b, "\nfunc (c *Client) %s(%s)", m.name, strings.Join(sigParams, ", "))
		if results != "" {
			fmt.Fprintf(&b, " %s", results)
		}
		b.WriteString(" {\n")

		ctxExpr := "ctx"
		if m.hasCtx {
			ctxExpr = m.params[0].name
		} else {
			b.WriteString("\tctx := context.Background()\n")
		}

		// args map
		args := m.argParams()
		argsExpr := "nil"
		if len(args) > 0 {
			var kvs []string
			for _, p := range args {
				kvs = append(kvs, fmt.Sprintf("%q: %s", p.name, p.name))
			}
			fmt.Fprintf(&b, "\targs := map[string]any{%s}\n", strings.Join(kvs, ", "))
			argsExpr = "args"
		}

		switch len(m.values) {
		case 0:
			if m.hasErr {
				fmt.Fprintf(&b, "\treturn c.call(%s, %q, %s, nil)\n", ctxExpr, m.name, argsExpr)
			} else {
				fmt.Fprintf(&b, "\t_ = c.call(%s, %q, %s, nil)\n", ctxExpr, m.name, argsExpr)
			}
		case 1:
			fmt.Fprintf(&b, "\tvar out %s\n", m.values[0].typ)
			fmt.Fprintf(&b, "\terr := c.call(%s, %q, %s, &out)\n", ctxExpr, m.name, argsExpr)
			if m.hasErr {
				b.WriteString("\treturn out, err\n")
			} else {
				b.WriteString("\t_ = err\n\treturn out\n")
			}
		default:
			b.WriteString("\tvar out struct {\n")
			for i, v := range m.values {
				fmt.Fprintf(&b, "\t\tR%d %s `json:\"r%d\"`\n", i, v.typ, i)
			}
			b.WriteString("\t}\n")
			fmt.Fprintf(&b, "\terr := c.call(%s, %q, %s, &out)\n", ctxExpr, m.name, argsExpr)
			var rets []string
			for i := range m.values {
				rets = append(rets, fmt.Sprintf("out.R%d", i))
			}
			if m.hasErr {
				fmt.Fprintf(&b, "\treturn %s, err\n", strings.Join(rets, ", "))
			} else {
				fmt.Fprintf(&b, "\t_ = err\n\treturn %s\n", strings.Join(rets, ", "))
			}
		}
		b.WriteString("}\n")
	}
	return b.Bytes()
}

func genServer(methods []method) []byte {
	var b bytes.Buffer
	b.WriteString(`// Code generated by internal/genremote; DO NOT EDIT.

package server

import (
	"context"
	"encoding/json"
	"net"
	"time"

	authkit "github.com/open-rails/authkit"
)

// generatedMethods is the management-API dispatch table, one entry per
// authkit.Client method.
var generatedMethods = map[string]MethodFunc{
`)
	// keep stdlib imports used even if a particular build elides them
	b.WriteString("\t// types referenced below pin the net/time imports\n")
	for _, m := range methods {
		fmt.Fprintf(&b, "\t%q: func(ctx context.Context, c authkit.Client, raw json.RawMessage) (any, error) {\n", m.name)
		args := m.argParams()
		callArgs := []string{}
		if m.hasCtx {
			callArgs = append(callArgs, "ctx")
		}
		if len(args) > 0 {
			b.WriteString("\t\tvar a struct {\n")
			for i, p := range args {
				fmt.Fprintf(&b, "\t\t\tA%d %s `json:\"%s\"`\n", i, p.typ, p.name)
			}
			b.WriteString("\t\t}\n")
			b.WriteString("\t\tif err := decodeArgs(raw, &a); err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
			for i := range args {
				callArgs = append(callArgs, fmt.Sprintf("a.A%d", i))
			}
		}
		call := fmt.Sprintf("c.%s(%s)", m.name, strings.Join(callArgs, ", "))

		switch len(m.values) {
		case 0:
			if m.hasErr {
				fmt.Fprintf(&b, "\t\treturn nil, %s\n", call)
			} else {
				fmt.Fprintf(&b, "\t\t%s\n\t\treturn nil, nil\n", call)
			}
		case 1:
			if m.hasErr {
				fmt.Fprintf(&b, "\t\tr0, err := %s\n\t\treturn r0, err\n", call)
			} else {
				fmt.Fprintf(&b, "\t\treturn %s, nil\n", call)
			}
		default:
			var lhs []string
			for i := range m.values {
				lhs = append(lhs, fmt.Sprintf("r%d", i))
			}
			if m.hasErr {
				lhs = append(lhs, "err")
			}
			fmt.Fprintf(&b, "\t\t%s := %s\n", strings.Join(lhs, ", "), call)
			var kvs []string
			for i := range m.values {
				kvs = append(kvs, fmt.Sprintf("%q: r%d", fmt.Sprintf("r%d", i), i))
			}
			if m.hasErr {
				fmt.Fprintf(&b, "\t\treturn map[string]any{%s}, err\n", strings.Join(kvs, ", "))
			} else {
				fmt.Fprintf(&b, "\t\treturn map[string]any{%s}, nil\n", strings.Join(kvs, ", "))
			}
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n// pin imports used only by some signatures.\nvar (\n\t_ net.IP\n\t_ time.Time\n)\n")
	return b.Bytes()
}

func main() {
	methods := parseMethods("client.go")
	if len(methods) == 0 {
		panic("genremote: no methods found on authkit.Client")
	}
	write := func(path string, data []byte) {
		formatted, err := format.Source(data)
		if err != nil {
			panic(fmt.Errorf("%s: %w", path, err))
		}
		if err := os.WriteFile(path, formatted, 0o644); err != nil {
			panic(err)
		}
	}
	write("remote/methods_gen.go", genRemote(methods))
	write("server/methods_gen.go", genServer(methods))
	fmt.Printf("genremote: generated %d methods\n", len(methods))
}
