// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"
	"time"
)

const aPIKeyByKeyID = `-- name: APIKeyByKeyID :one
SELECT t.id::text AS id, t.secret_hash, t.expires_at, t.revoked_at,
       o.id::text AS org_id, o.slug, o.deleted_at AS org_deleted_at
FROM profiles.service_tokens t
JOIN profiles.orgs o ON o.id = t.org_id
WHERE t.key_id = $1
`

type APIKeyByKeyIDRow struct {
	ID           string
	SecretHash   []byte
	ExpiresAt    *time.Time
	RevokedAt    *time.Time
	OrgID        string
	Slug         string
	OrgDeletedAt *time.Time
}

func (q *Queries) APIKeyByKeyID(ctx context.Context, keyID string) (APIKeyByKeyIDRow, error) {
	row := q.db.QueryRow(ctx, aPIKeyByKeyID, keyID)
	var i APIKeyByKeyIDRow
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.OrgID,
		&i.Slug,
		&i.OrgDeletedAt,
	)
	return i, err
}

const aPIKeyInsert = `-- name: APIKeyInsert :one

INSERT INTO profiles.service_tokens
  (org_id, key_id, secret_hash, name, created_by, expires_at)
VALUES ($1::uuid, $2, $3, $4, $5::uuid, $6)
RETURNING id::text, created_at
`

type APIKeyInsertParams struct {
	OrgID      string
	KeyID      string
	SecretHash []byte
	Name       string
	CreatedBy  *string
	ExpiresAt  *time.Time
}

type APIKeyInsertRow struct {
	ID        string
	CreatedAt time.Time
}

// API key queries (core/api_keys.go).
func (q *Queries) APIKeyInsert(ctx context.Context, arg APIKeyInsertParams) (APIKeyInsertRow, error) {
	row := q.db.QueryRow(ctx, aPIKeyInsert,
		arg.OrgID,
		arg.KeyID,
		arg.SecretHash,
		arg.Name,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i APIKeyInsertRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const aPIKeyPermissionInsert = `-- name: APIKeyPermissionInsert :exec
INSERT INTO profiles.service_token_permissions (service_token_id, permission)
VALUES ($1::uuid, $2)
`

type APIKeyPermissionInsertParams struct {
	ApiKeyID   string
	Permission string
}

func (q *Queries) APIKeyPermissionInsert(ctx context.Context, arg APIKeyPermissionInsertParams) error {
	_, err := q.db.Exec(ctx, aPIKeyPermissionInsert, arg.ApiKeyID, arg.Permission)
	return err
}

const aPIKeyPermissionsByAPIKeyID = `-- name: APIKeyPermissionsByAPIKeyID :many
SELECT permission
FROM profiles.service_token_permissions
WHERE service_token_id = $1::uuid
ORDER BY permission
`

func (q *Queries) APIKeyPermissionsByAPIKeyID(ctx context.Context, apiKeyID string) ([]string, error) {
	rows, err := q.db.Query(ctx, aPIKeyPermissionsByAPIKeyID, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPIKeyPermissionsByAPIKeyIDs = `-- name: APIKeyPermissionsByAPIKeyIDs :many
SELECT service_token_id::text AS api_key_id, permission
FROM profiles.service_token_permissions
WHERE service_token_id = ANY($1::uuid[])
ORDER BY service_token_id::text, permission
`

type APIKeyPermissionsByAPIKeyIDsRow struct {
	ApiKeyID   string
	Permission string
}

func (q *Queries) APIKeyPermissionsByAPIKeyIDs(ctx context.Context, ids []string) ([]APIKeyPermissionsByAPIKeyIDsRow, error) {
	rows, err := q.db.Query(ctx, aPIKeyPermissionsByAPIKeyIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIKeyPermissionsByAPIKeyIDsRow
	for rows.Next() {
		var i APIKeyPermissionsByAPIKeyIDsRow
		if err := rows.Scan(&i.ApiKeyID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPIKeyResourceInsert = `-- name: APIKeyResourceInsert :exec
INSERT INTO profiles.service_token_resources (token_id, kind, resource_id)
VALUES ($1::uuid, $2, $3)
`

type APIKeyResourceInsertParams struct {
	ApiKeyID   string
	Kind       string
	ResourceID string
}

func (q *Queries) APIKeyResourceInsert(ctx context.Context, arg APIKeyResourceInsertParams) error {
	_, err := q.db.Exec(ctx, aPIKeyResourceInsert, arg.ApiKeyID, arg.Kind, arg.ResourceID)
	return err
}

const aPIKeyResourcesByAPIKeyID = `-- name: APIKeyResourcesByAPIKeyID :many
SELECT kind, resource_id
FROM profiles.service_token_resources
WHERE token_id = $1::uuid
ORDER BY kind, resource_id
`

type APIKeyResourcesByAPIKeyIDRow struct {
	Kind       string
	ResourceID string
}

func (q *Queries) APIKeyResourcesByAPIKeyID(ctx context.Context, apiKeyID string) ([]APIKeyResourcesByAPIKeyIDRow, error) {
	rows, err := q.db.Query(ctx, aPIKeyResourcesByAPIKeyID, apiKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIKeyResourcesByAPIKeyIDRow
	for rows.Next() {
		var i APIKeyResourcesByAPIKeyIDRow
		if err := rows.Scan(&i.Kind, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPIKeyResourcesByAPIKeyIDs = `-- name: APIKeyResourcesByAPIKeyIDs :many
SELECT token_id::text AS api_key_id, kind, resource_id
FROM profiles.service_token_resources
WHERE token_id = ANY($1::uuid[])
ORDER BY token_id::text, kind, resource_id
`

type APIKeyResourcesByAPIKeyIDsRow struct {
	ApiKeyID   string
	Kind       string
	ResourceID string
}

func (q *Queries) APIKeyResourcesByAPIKeyIDs(ctx context.Context, ids []string) ([]APIKeyResourcesByAPIKeyIDsRow, error) {
	rows, err := q.db.Query(ctx, aPIKeyResourcesByAPIKeyIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIKeyResourcesByAPIKeyIDsRow
	for rows.Next() {
		var i APIKeyResourcesByAPIKeyIDsRow
		if err := rows.Scan(&i.ApiKeyID, &i.Kind, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPIKeyRevoke = `-- name: APIKeyRevoke :execrows
UPDATE profiles.service_tokens
SET revoked_at = now()
WHERE id = $1::uuid AND org_id = $2::uuid AND revoked_at IS NULL
`

type APIKeyRevokeParams struct {
	ID    string
	OrgID string
}

func (q *Queries) APIKeyRevoke(ctx context.Context, arg APIKeyRevokeParams) (int64, error) {
	result, err := q.db.Exec(ctx, aPIKeyRevoke, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const aPIKeyTouchLastUsed = `-- name: APIKeyTouchLastUsed :exec
UPDATE profiles.service_tokens SET last_used_at = now() WHERE id = $1::uuid
`

func (q *Queries) APIKeyTouchLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, aPIKeyTouchLastUsed, id)
	return err
}

const aPIKeysByOrg = `-- name: APIKeysByOrg :many
SELECT id::text, key_id, name, COALESCE(created_by::text, '')::text AS created_by,
       created_at, last_used_at, expires_at, revoked_at
FROM profiles.service_tokens
WHERE org_id = $1::uuid
ORDER BY created_at DESC
`

type APIKeysByOrgRow struct {
	ID         string
	KeyID      string
	Name       string
	CreatedBy  string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	ExpiresAt  *time.Time
	RevokedAt  *time.Time
}

func (q *Queries) APIKeysByOrg(ctx context.Context, orgID string) ([]APIKeysByOrgRow, error) {
	rows, err := q.db.Query(ctx, aPIKeysByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIKeysByOrgRow
	for rows.Next() {
		var i APIKeysByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
