// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authority.sql

package db

import (
	"context"
)

const aPIKeyRetire = `-- name: APIKeyRetire :exec
UPDATE api_keys SET revoked_at = now() WHERE id = $1
`

func (q *Queries) APIKeyRetire(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, aPIKeyRetire, id)
	return err
}

const accountInviteRetire = `-- name: AccountInviteRetire :exec
UPDATE account_registration_invites SET revoked_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) AccountInviteRetire(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, accountInviteRetire, id)
	return err
}

const authorityAPIKeyRole = `-- name: AuthorityAPIKeyRole :one
SELECT k.permission_group_id, k.role FROM api_keys k JOIN permission_groups g ON g.id = k.permission_group_id
WHERE k.id = $1 AND k.revoked_at IS NULL AND (k.expires_at IS NULL OR k.expires_at > now()) AND g.deleted_at IS NULL
  AND (k.created_by IS NULL OR EXISTS(SELECT 1 FROM usable_users WHERE id = k.created_by))
`

type AuthorityAPIKeyRoleRow struct {
	PermissionGroupID string
	Role              string
}

// The group and role of a live key in a live group whose creator is the
// system (NULL) or usable.
func (q *Queries) AuthorityAPIKeyRole(ctx context.Context, id string) (AuthorityAPIKeyRoleRow, error) {
	row := q.db.QueryRow(ctx, authorityAPIKeyRole, id)
	var i AuthorityAPIKeyRoleRow
	err := row.Scan(&i.PermissionGroupID, &i.Role)
	return i, err
}

const authorityApplicationGroup = `-- name: AuthorityApplicationGroup :one
SELECT a.permission_group_id FROM remote_applications a JOIN permission_groups g ON g.id = a.permission_group_id
WHERE a.id = $1 AND a.enabled AND g.deleted_at IS NULL
  AND (a.trust_root <> 'user' OR EXISTS(SELECT 1 FROM usable_users WHERE id = a.registered_by))
`

// The controlling group of an enabled application in a live group whose
// registrar is usable.
func (q *Queries) AuthorityApplicationGroup(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, authorityApplicationGroup, id)
	var permission_group_id string
	err := row.Scan(&permission_group_id)
	return permission_group_id, err
}

const authorityApplicationOwnsGroup = `-- name: AuthorityApplicationOwnsGroup :one
SELECT (a.permission_group_id = $1::uuid)::boolean AS controls, g.persona
FROM remote_applications a JOIN permission_groups g ON g.id = $1::uuid
WHERE a.id = $2::uuid
`

type AuthorityApplicationOwnsGroupParams struct {
	GroupID       string
	ApplicationID string
}

type AuthorityApplicationOwnsGroupRow struct {
	Controls bool
	Persona  string
}

// Whether group_id controls the application, and the group's persona.
func (q *Queries) AuthorityApplicationOwnsGroup(ctx context.Context, arg AuthorityApplicationOwnsGroupParams) (AuthorityApplicationOwnsGroupRow, error) {
	row := q.db.QueryRow(ctx, authorityApplicationOwnsGroup, arg.GroupID, arg.ApplicationID)
	var i AuthorityApplicationOwnsGroupRow
	err := row.Scan(&i.Controls, &i.Persona)
	return i, err
}

const authorityGroup = `-- name: AuthorityGroup :one
SELECT id, persona, created_at, deleted_at FROM permission_groups WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) AuthorityGroup(ctx context.Context, id string) (PermissionGroup, error) {
	row := q.db.QueryRow(ctx, authorityGroup, id)
	var i PermissionGroup
	err := row.Scan(
		&i.ID,
		&i.Persona,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const authorityGroupState = `-- name: AuthorityGroupState :one
SELECT id, persona, created_at, deleted_at FROM permission_groups WHERE id = $1
`

func (q *Queries) AuthorityGroupState(ctx context.Context, id string) (PermissionGroup, error) {
	row := q.db.QueryRow(ctx, authorityGroupState, id)
	var i PermissionGroup
	err := row.Scan(
		&i.ID,
		&i.Persona,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const authorityOutsideApplicationOwnerGroups = `-- name: AuthorityOutsideApplicationOwnerGroups :many
SELECT DISTINCT r.permission_group_id FROM group_remote_application_roles r
JOIN remote_applications a ON a.id = r.remote_application_id
WHERE a.permission_group_id = $1::uuid AND a.enabled AND r.role LIKE '%:owner'
  AND r.permission_group_id <> $1::uuid
`

// The other groups owned by enabled applications that group_id controls.
func (q *Queries) AuthorityOutsideApplicationOwnerGroups(ctx context.Context, groupID string) ([]string, error) {
	rows, err := q.db.Query(ctx, authorityOutsideApplicationOwnerGroups, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_group_id string
		if err := rows.Scan(&permission_group_id); err != nil {
			return nil, err
		}
		items = append(items, permission_group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorityUncoveredCredentials = `-- name: AuthorityUncoveredCredentials :many
WITH scope AS (
  SELECT g.id, g.persona FROM permission_groups t JOIN permission_groups g
    ON g.id = t.id OR (t.persona = 'root' AND g.deleted_at IS NULL)
  WHERE t.id = $1::uuid)
SELECT 'group_invite_links'::text AS kind, l.id::text AS id, l.permission_group_id::text AS group_id, t.persona, l.role,
       COALESCE(l.invited_by::text, '')::text AS creator, false AS needs_creator
  FROM group_invite_links l JOIN scope t ON t.id = l.permission_group_id
 WHERE l.revoked_at IS NULL AND l.redeemed_at IS NULL AND (l.expires_at IS NULL OR l.expires_at > now())
   AND l.invited_by IS NOT NULL AND ($2::text = '' OR l.invited_by = NULLIF($2::text, '')::uuid)
   AND (l.catalog_issuer IS NULL OR l.catalog_issuer = $3::text)
UNION ALL
SELECT 'account_registration_invites', a.id::text, a.permission_group_id::text, t.persona, a.role, a.invited_by::text, false
  FROM account_registration_invites a JOIN scope t ON t.id = a.permission_group_id
 WHERE a.revoked_at IS NULL AND a.consumed_at IS NULL AND a.expires_at > now()
   AND a.invited_by IS NOT NULL AND ($2::text = '' OR a.invited_by = NULLIF($2::text, '')::uuid)
   AND (a.catalog_issuer IS NULL OR a.catalog_issuer = $3::text)
UNION ALL
SELECT 'account_registration_invites', a.id::text, t.id::text, t.persona, '', a.invited_by::text, false
  FROM account_registration_invites a JOIN scope t ON t.persona = 'root'
 WHERE a.permission_group_id IS NULL AND a.revoked_at IS NULL AND a.consumed_at IS NULL AND a.expires_at > now()
   AND a.invited_by IS NOT NULL AND ($2::text = '' OR a.invited_by = NULLIF($2::text, '')::uuid)
   AND (a.catalog_issuer IS NULL OR a.catalog_issuer = $3::text)
UNION ALL
SELECT 'api_keys', k.id::text, k.permission_group_id::text, t.persona, k.role, COALESCE(k.created_by::text, ''), false
  FROM api_keys k JOIN scope t ON t.id = k.permission_group_id
 WHERE k.revoked_at IS NULL AND (k.expires_at IS NULL OR k.expires_at > now())
   AND ($2::text = '' OR k.created_by = NULLIF($2::text, '')::uuid)
   AND (k.catalog_issuer IS NULL OR k.catalog_issuer = $3::text)
UNION ALL
SELECT 'group_remote_application_roles', a.id::text, r.permission_group_id::text, t.persona, r.role, COALESCE(a.registered_by::text, ''), a.trust_root = 'user'
  FROM group_remote_application_roles r JOIN scope t ON t.id = r.permission_group_id
  JOIN remote_applications a ON a.id = r.remote_application_id
 WHERE ($2::text = '' OR a.registered_by = NULLIF($2::text, '')::uuid)
   AND (a.catalog_issuer IS NULL OR a.catalog_issuer = $3::text)
`

type AuthorityUncoveredCredentialsParams struct {
	GroupID string
	UserID  string
	Issuer  string
}

type AuthorityUncoveredCredentialsRow struct {
	Kind         string
	ID           string
	GroupID      string
	Persona      string
	Role         string
	Creator      string
	NeedsCreator bool
}

// Live credentials in the scope of a grant change to group_id (root: every
// live group) issued by user_id (” = anyone) through issuer's app, or before
// per-app catalogs: invite links, account invitations (one without a group
// belongs to root), API keys and the roles of applications (needs_creator: a
// group registration, which confers nothing without its registrar).
func (q *Queries) AuthorityUncoveredCredentials(ctx context.Context, arg AuthorityUncoveredCredentialsParams) ([]AuthorityUncoveredCredentialsRow, error) {
	rows, err := q.db.Query(ctx, authorityUncoveredCredentials, arg.GroupID, arg.UserID, arg.Issuer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorityUncoveredCredentialsRow
	for rows.Next() {
		var i AuthorityUncoveredCredentialsRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.GroupID,
			&i.Persona,
			&i.Role,
			&i.Creator,
			&i.NeedsCreator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorityUserGroups = `-- name: AuthorityUserGroups :many
SELECT g.id, g.persona, g.created_at, g.deleted_at FROM group_user_roles r JOIN permission_groups g ON g.id = r.permission_group_id
WHERE r.user_id = $1 AND g.id <> $2 AND g.deleted_at IS NULL
ORDER BY g.id
`

type AuthorityUserGroupsParams struct {
	UserID string
	RootID string
}

// The live groups other than root where the user holds a role.
func (q *Queries) AuthorityUserGroups(ctx context.Context, arg AuthorityUserGroupsParams) ([]PermissionGroup, error) {
	rows, err := q.db.Query(ctx, authorityUserGroups, arg.UserID, arg.RootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionGroup
	for rows.Next() {
		var i PermissionGroup
		if err := rows.Scan(
			&i.ID,
			&i.Persona,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupApplicationRoleName = `-- name: GroupApplicationRoleName :one
SELECT role FROM group_remote_application_roles WHERE permission_group_id = $1 AND remote_application_id = $2
`

type GroupApplicationRoleNameParams struct {
	GroupID       string
	ApplicationID string
}

func (q *Queries) GroupApplicationRoleName(ctx context.Context, arg GroupApplicationRoleNameParams) (string, error) {
	row := q.db.QueryRow(ctx, groupApplicationRoleName, arg.GroupID, arg.ApplicationID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const groupHasOtherUsableOwner = `-- name: GroupHasOtherUsableOwner :one
SELECT EXISTS(
  SELECT 1 FROM group_user_roles r JOIN usable_users u ON u.id = r.user_id
  WHERE r.permission_group_id = $1::uuid AND r.role LIKE '%:owner'
    AND NOT ($2::text = 'user' AND u.id = $3::uuid)
    AND (NOT $4::boolean OR EXISTS(SELECT 1 FROM mfa_settings m WHERE m.user_id = u.id AND m.enabled
      AND EXISTS(SELECT 1 FROM mfa_factors f WHERE f.user_id = u.id)))
  UNION ALL
  SELECT 1 FROM group_remote_application_roles r JOIN remote_applications a ON a.id = r.remote_application_id
  WHERE NOT $4::boolean AND r.permission_group_id = $1::uuid AND r.role LIKE '%:owner'
    AND NOT ($2::text = 'remote_application' AND a.id = $3::uuid)
    AND NOT ($2::text = 'user' AND a.registered_by IS NOT DISTINCT FROM $3::uuid)
    AND a.enabled AND a.permission_group_id = r.permission_group_id
    AND (a.trust_root <> 'user' OR EXISTS(SELECT 1 FROM usable_users WHERE id = a.registered_by))
    AND EXISTS(SELECT 1 FROM permission_groups control WHERE control.id = a.permission_group_id AND control.deleted_at IS NULL)
)::boolean AS remains
`

type GroupHasOtherUsableOwnerParams struct {
	GroupID       string
	ExcludingKind string
	ExcludingID   *string
	NeedsMfa      bool
}

// Whether the group has an owner that counts, other than the subject
// (excluding_kind, excluding_id): a usable user, MFA-enrolled when needs_mfa,
// or, when owners need no MFA, an enabled application of the group itself
// whose registrar is usable. An application a departing user registered
// never stands in for that user: its authority ends with theirs (R1).
func (q *Queries) GroupHasOtherUsableOwner(ctx context.Context, arg GroupHasOtherUsableOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, groupHasOtherUsableOwner,
		arg.GroupID,
		arg.ExcludingKind,
		arg.ExcludingID,
		arg.NeedsMfa,
	)
	var remains bool
	err := row.Scan(&remains)
	return remains, err
}

const groupUserRoleName = `-- name: GroupUserRoleName :one
SELECT role FROM group_user_roles WHERE permission_group_id = $1 AND user_id = $2
`

type GroupUserRoleNameParams struct {
	GroupID string
	UserID  string
}

func (q *Queries) GroupUserRoleName(ctx context.Context, arg GroupUserRoleNameParams) (string, error) {
	row := q.db.QueryRow(ctx, groupUserRoleName, arg.GroupID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const groupsOwnedByApplication = `-- name: GroupsOwnedByApplication :many
SELECT permission_group_id FROM group_remote_application_roles WHERE remote_application_id = $1 AND role LIKE '%:owner' ORDER BY permission_group_id
`

func (q *Queries) GroupsOwnedByApplication(ctx context.Context, remoteApplicationID string) ([]string, error) {
	rows, err := q.db.Query(ctx, groupsOwnedByApplication, remoteApplicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_group_id string
		if err := rows.Scan(&permission_group_id); err != nil {
			return nil, err
		}
		items = append(items, permission_group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inviteLinkRetire = `-- name: InviteLinkRetire :exec
UPDATE group_invite_links SET revoked_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) InviteLinkRetire(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, inviteLinkRetire, id)
	return err
}

const permissionGroupEnsureRoot = `-- name: PermissionGroupEnsureRoot :one
INSERT INTO permission_groups (persona) VALUES ('root') ON CONFLICT DO NOTHING RETURNING id
`

// DO NOTHING keeps a concurrent singleton insert from aborting the caller's
// transaction; no row means another transaction created root.
func (q *Queries) PermissionGroupEnsureRoot(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, permissionGroupEnsureRoot)
	var id string
	err := row.Scan(&id)
	return id, err
}

const remoteApplicationUsable = `-- name: RemoteApplicationUsable :one
SELECT EXISTS(
  SELECT 1 FROM remote_applications a JOIN permission_groups g ON g.id = a.permission_group_id
  WHERE a.id = $1::uuid AND a.enabled AND g.deleted_at IS NULL
    AND (a.trust_root <> 'user' OR EXISTS(SELECT 1 FROM usable_users WHERE id = a.registered_by))
)::boolean AS usable
`

func (q *Queries) RemoteApplicationUsable(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, remoteApplicationUsable, id)
	var usable bool
	err := row.Scan(&usable)
	return usable, err
}

const transactionSettings = `-- name: TransactionSettings :one

SELECT current_setting('transaction_isolation')::text AS isolation, current_setting('search_path')::text AS search_path
`

type TransactionSettingsRow struct {
	Isolation  string
	SearchPath string
}

// Authority: the lock and transaction settings of authority mutations, group
// and actor resolution, ownership invariants and the credential sweep. A
// usable account is a row of usable_users; an application's registrar counts
// only while usable.
func (q *Queries) TransactionSettings(ctx context.Context) (TransactionSettingsRow, error) {
	row := q.db.QueryRow(ctx, transactionSettings)
	var i TransactionSettingsRow
	err := row.Scan(&i.Isolation, &i.SearchPath)
	return i, err
}

const userUsable = `-- name: UserUsable :one
SELECT EXISTS(SELECT 1 FROM usable_users WHERE id = $1::uuid)::boolean AS usable
`

func (q *Queries) UserUsable(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, userUsable, id)
	var usable bool
	err := row.Scan(&usable)
	return usable, err
}
