// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bootstrap.sql

package db

import (
	"context"
)

const bootstrapAccountByCanonicalNameForUpdate = `-- name: BootstrapAccountByCanonicalNameForUpdate :one
SELECT u.id::text AS id, (u.deleted_at IS NOT NULL)::boolean AS deleted
FROM name_claims c JOIN users u ON u.id = c.owner_id
WHERE c.owner_kind = 'user' AND c.persona = '' AND c.name = lower($1::text) AND c.canonical
FOR UPDATE OF u
`

type BootstrapAccountByCanonicalNameForUpdateRow struct {
	ID      string
	Deleted bool
}

// A canonical username only; an alias is never followed.
func (q *Queries) BootstrapAccountByCanonicalNameForUpdate(ctx context.Context, username string) (BootstrapAccountByCanonicalNameForUpdateRow, error) {
	row := q.db.QueryRow(ctx, bootstrapAccountByCanonicalNameForUpdate, username)
	var i BootstrapAccountByCanonicalNameForUpdateRow
	err := row.Scan(&i.ID, &i.Deleted)
	return i, err
}

const bootstrapAccountByEmailForUpdate = `-- name: BootstrapAccountByEmailForUpdate :one
SELECT id::text AS id, email_verified AS verified, (deleted_at IS NOT NULL)::boolean AS deleted
FROM users WHERE email = $1::text::public.citext FOR UPDATE
`

type BootstrapAccountByEmailForUpdateRow struct {
	ID       string
	Verified bool
	Deleted  bool
}

func (q *Queries) BootstrapAccountByEmailForUpdate(ctx context.Context, email string) (BootstrapAccountByEmailForUpdateRow, error) {
	row := q.db.QueryRow(ctx, bootstrapAccountByEmailForUpdate, email)
	var i BootstrapAccountByEmailForUpdateRow
	err := row.Scan(&i.ID, &i.Verified, &i.Deleted)
	return i, err
}

const bootstrapAccountByIDForUpdate = `-- name: BootstrapAccountByIDForUpdate :one

SELECT id::text AS id, true AS verified, (deleted_at IS NOT NULL)::boolean AS deleted
FROM users WHERE id = $1::uuid FOR UPDATE
`

type BootstrapAccountByIDForUpdateRow struct {
	ID       string
	Verified bool
	Deleted  bool
}

// Bootstrap manifests and EnsureUserRole: find and lock the account a
// manifest user or a UserRef names. verified reports whether the key proves
// who holds the account (the id itself, or a verified contact).
func (q *Queries) BootstrapAccountByIDForUpdate(ctx context.Context, id string) (BootstrapAccountByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, bootstrapAccountByIDForUpdate, id)
	var i BootstrapAccountByIDForUpdateRow
	err := row.Scan(&i.ID, &i.Verified, &i.Deleted)
	return i, err
}

const bootstrapAccountByPhoneForUpdate = `-- name: BootstrapAccountByPhoneForUpdate :one
SELECT id::text AS id, phone_verified AS verified, (deleted_at IS NOT NULL)::boolean AS deleted
FROM users WHERE phone_number = $1::text FOR UPDATE
`

type BootstrapAccountByPhoneForUpdateRow struct {
	ID       string
	Verified bool
	Deleted  bool
}

func (q *Queries) BootstrapAccountByPhoneForUpdate(ctx context.Context, phone string) (BootstrapAccountByPhoneForUpdateRow, error) {
	row := q.db.QueryRow(ctx, bootstrapAccountByPhoneForUpdate, phone)
	var i BootstrapAccountByPhoneForUpdateRow
	err := row.Scan(&i.ID, &i.Verified, &i.Deleted)
	return i, err
}

const bootstrapApplyInsert = `-- name: BootstrapApplyInsert :exec
INSERT INTO bootstrap_applies (name) VALUES ($1)
`

func (q *Queries) BootstrapApplyInsert(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, bootstrapApplyInsert, name)
	return err
}

const bootstrapApplyState = `-- name: BootstrapApplyState :one
SELECT
  EXISTS (SELECT 1 FROM bootstrap_applies b WHERE b.name = $1::text)::boolean AS name_claimed,
  EXISTS (SELECT 1 FROM bootstrap_applies)::boolean AS any_claimed,
  (NOT EXISTS (SELECT 1 FROM users WHERE deleted_at IS NULL)
   AND NOT EXISTS (SELECT 1 FROM remote_applications))::boolean AS graph_empty
`

type BootstrapApplyStateRow struct {
	NameClaimed bool
	AnyClaimed  bool
	GraphEmpty  bool
}

func (q *Queries) BootstrapApplyState(ctx context.Context, name string) (BootstrapApplyStateRow, error) {
	row := q.db.QueryRow(ctx, bootstrapApplyState, name)
	var i BootstrapApplyStateRow
	err := row.Scan(&i.NameClaimed, &i.AnyClaimed, &i.GraphEmpty)
	return i, err
}
