// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanup.sql

package db

import (
	"context"
	"time"
)

const aPIKeysDeleteExpiredBatch = `-- name: APIKeysDeleteExpiredBatch :exec
WITH batch AS (
    SELECT id FROM api_keys WHERE LEAST(revoked_at, expires_at) < $1::timestamptz
    ORDER BY LEAST(revoked_at, expires_at), id
    LIMIT $2::bigint FOR UPDATE SKIP LOCKED)
DELETE FROM api_keys WHERE id IN (SELECT id FROM batch)
`

type APIKeysDeleteExpiredBatchParams struct {
	Cutoff    time.Time
	BatchSize int64
}

func (q *Queries) APIKeysDeleteExpiredBatch(ctx context.Context, arg APIKeysDeleteExpiredBatchParams) error {
	_, err := q.db.Exec(ctx, aPIKeysDeleteExpiredBatch, arg.Cutoff, arg.BatchSize)
	return err
}

const accountInvitesDeleteExpiredBatch = `-- name: AccountInvitesDeleteExpiredBatch :exec
WITH batch AS (
    SELECT id FROM account_registration_invites WHERE LEAST(consumed_at, revoked_at, expires_at) < $1::timestamptz
    ORDER BY LEAST(consumed_at, revoked_at, expires_at), id
    LIMIT $2::bigint FOR UPDATE SKIP LOCKED)
DELETE FROM account_registration_invites WHERE id IN (SELECT id FROM batch)
`

type AccountInvitesDeleteExpiredBatchParams struct {
	Cutoff    time.Time
	BatchSize int64
}

func (q *Queries) AccountInvitesDeleteExpiredBatch(ctx context.Context, arg AccountInvitesDeleteExpiredBatchParams) error {
	_, err := q.db.Exec(ctx, accountInvitesDeleteExpiredBatch, arg.Cutoff, arg.BatchSize)
	return err
}

const inviteLinksDeleteExpiredBatch = `-- name: InviteLinksDeleteExpiredBatch :exec

WITH batch AS (
    SELECT id FROM group_invite_links WHERE LEAST(redeemed_at, revoked_at, expires_at) < $1::timestamptz
    ORDER BY LEAST(redeemed_at, revoked_at, expires_at), id
    LIMIT $2::bigint FOR UPDATE SKIP LOCKED)
DELETE FROM group_invite_links WHERE id IN (SELECT id FROM batch)
`

type InviteLinksDeleteExpiredBatchParams struct {
	Cutoff    time.Time
	BatchSize int64
}

// Maintenance sweep of terminal credentials, retained for inspection until
// cutoff. Each call deletes one bounded batch, locking only that batch (SKIP
// LOCKED) so concurrent sweeps make progress.
func (q *Queries) InviteLinksDeleteExpiredBatch(ctx context.Context, arg InviteLinksDeleteExpiredBatchParams) error {
	_, err := q.db.Exec(ctx, inviteLinksDeleteExpiredBatch, arg.Cutoff, arg.BatchSize)
	return err
}
