// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_roles.sql

package db

import (
	"context"
	"time"
)

const customRoleApplicationsRemove = `-- name: CustomRoleApplicationsRemove :many
DELETE FROM group_remote_application_roles WHERE permission_group_id = $1::uuid AND role = $2::text
RETURNING remote_application_id::text
`

type CustomRoleApplicationsRemoveParams struct {
	GroupID string
	Role    string
}

func (q *Queries) CustomRoleApplicationsRemove(ctx context.Context, arg CustomRoleApplicationsRemoveParams) ([]string, error) {
	rows, err := q.db.Query(ctx, customRoleApplicationsRemove, arg.GroupID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var remote_application_id string
		if err := rows.Scan(&remote_application_id); err != nil {
			return nil, err
		}
		items = append(items, remote_application_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const customRoleByName = `-- name: CustomRoleByName :one
SELECT role, permissions, created_at, updated_at FROM group_custom_roles
WHERE permission_group_id = $1::uuid AND role = $2::text
`

type CustomRoleByNameParams struct {
	GroupID string
	Role    string
}

type CustomRoleByNameRow struct {
	Role        string
	Permissions []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CustomRoleByName(ctx context.Context, arg CustomRoleByNameParams) (CustomRoleByNameRow, error) {
	row := q.db.QueryRow(ctx, customRoleByName, arg.GroupID, arg.Role)
	var i CustomRoleByNameRow
	err := row.Scan(
		&i.Role,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const customRoleCount = `-- name: CustomRoleCount :one
SELECT count(*)::bigint FROM group_custom_roles WHERE permission_group_id = $1::uuid
`

func (q *Queries) CustomRoleCount(ctx context.Context, groupID string) (int64, error) {
	row := q.db.QueryRow(ctx, customRoleCount, groupID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const customRoleCredentialsRevoke = `-- name: CustomRoleCredentialsRevoke :exec
WITH keys AS (
  UPDATE api_keys SET revoked_at = now()
  WHERE permission_group_id = $2::uuid AND role = $1::text AND revoked_at IS NULL
), links AS (
  UPDATE group_invite_links SET revoked_at = now()
  WHERE permission_group_id = $2::uuid AND role = $1::text AND revoked_at IS NULL AND redeemed_at IS NULL
), invites AS (
  UPDATE account_registration_invites SET revoked_at = now()
  WHERE permission_group_id = $2::uuid AND role = $1::text AND revoked_at IS NULL AND consumed_at IS NULL
)
UPDATE remote_applications a SET updated_at = now(), role_map = NULLIF(
  (SELECT COALESCE(jsonb_object_agg(m.key, m.value), '{}'::jsonb) FROM jsonb_each_text(a.role_map) m WHERE m.value <> $1::text),
  '{}'::jsonb)
WHERE a.permission_group_id = $2::uuid
  AND EXISTS(SELECT 1 FROM jsonb_each_text(a.role_map) m WHERE m.value = $1::text)
`

type CustomRoleCredentialsRevokeParams struct {
	Role    string
	GroupID string
}

// Revokes the API keys and invitations carrying the role, and drops it from
// role maps.
func (q *Queries) CustomRoleCredentialsRevoke(ctx context.Context, arg CustomRoleCredentialsRevokeParams) error {
	_, err := q.db.Exec(ctx, customRoleCredentialsRevoke, arg.Role, arg.GroupID)
	return err
}

const customRoleDelete = `-- name: CustomRoleDelete :exec
DELETE FROM group_custom_roles WHERE permission_group_id = $1::uuid AND role = $2::text
`

type CustomRoleDeleteParams struct {
	GroupID string
	Role    string
}

func (q *Queries) CustomRoleDelete(ctx context.Context, arg CustomRoleDeleteParams) error {
	_, err := q.db.Exec(ctx, customRoleDelete, arg.GroupID, arg.Role)
	return err
}

const customRoleHolders = `-- name: CustomRoleHolders :one
SELECT
  (EXISTS(SELECT 1 FROM group_user_roles r WHERE r.permission_group_id = $1::uuid AND r.role = $2::text)
   OR EXISTS(SELECT 1 FROM group_remote_user_roles r WHERE r.permission_group_id = $1::uuid AND r.role = $2::text)
   OR EXISTS(SELECT 1 FROM group_invite_links l WHERE l.permission_group_id = $1::uuid AND l.role = $2::text
     AND l.revoked_at IS NULL AND l.redeemed_at IS NULL AND (l.expires_at IS NULL OR l.expires_at > now()))
   OR EXISTS(SELECT 1 FROM account_registration_invites a WHERE a.permission_group_id = $1::uuid AND a.role = $2::text
     AND a.revoked_at IS NULL AND a.consumed_at IS NULL AND a.expires_at > now()))::boolean AS members,
  (EXISTS(SELECT 1 FROM api_keys k WHERE k.permission_group_id = $1::uuid AND k.role = $2::text
     AND k.revoked_at IS NULL AND (k.expires_at IS NULL OR k.expires_at > now()))
   OR EXISTS(SELECT 1 FROM group_remote_application_roles r WHERE r.permission_group_id = $1::uuid AND r.role = $2::text)
   OR EXISTS(SELECT 1 FROM remote_applications a, jsonb_each_text(a.role_map) m
     WHERE a.permission_group_id = $1::uuid AND m.value = $2::text))::boolean AS credentials,
  (EXISTS(SELECT 1 FROM api_keys k WHERE k.permission_group_id = $1::uuid AND k.role = $2::text
     AND k.revoked_at IS NULL AND (k.expires_at IS NULL OR k.expires_at > now()))
   OR EXISTS(SELECT 1 FROM group_remote_application_roles r WHERE r.permission_group_id = $1::uuid AND r.role = $2::text))::boolean AS machines,
  EXISTS(SELECT 1 FROM group_user_roles r WHERE r.permission_group_id = $1::uuid AND r.role = $2::text
    AND NOT EXISTS(SELECT 1 FROM mfa_factors f WHERE f.user_id = r.user_id))::boolean AS users_without_mfa
`

type CustomRoleHoldersParams struct {
	GroupID string
	Role    string
}

type CustomRoleHoldersRow struct {
	Members         bool
	Credentials     bool
	Machines        bool
	UsersWithoutMfa bool
}

// Who holds the role in the group: members (users, remote users and pending
// invitations), credentials (live API keys, applications and role maps),
// machines (API keys and applications, which present no second factor) and
// users with no second factor.
func (q *Queries) CustomRoleHolders(ctx context.Context, arg CustomRoleHoldersParams) (CustomRoleHoldersRow, error) {
	row := q.db.QueryRow(ctx, customRoleHolders, arg.GroupID, arg.Role)
	var i CustomRoleHoldersRow
	err := row.Scan(
		&i.Members,
		&i.Credentials,
		&i.Machines,
		&i.UsersWithoutMfa,
	)
	return i, err
}

const customRoleInsert = `-- name: CustomRoleInsert :one
INSERT INTO group_custom_roles (permission_group_id, role, permissions)
VALUES ($1::uuid, $2::text, $3::text[])
ON CONFLICT DO NOTHING
RETURNING created_at, updated_at
`

type CustomRoleInsertParams struct {
	GroupID     string
	Role        string
	Permissions []string
}

type CustomRoleInsertRow struct {
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CustomRoleInsert(ctx context.Context, arg CustomRoleInsertParams) (CustomRoleInsertRow, error) {
	row := q.db.QueryRow(ctx, customRoleInsert, arg.GroupID, arg.Role, arg.Permissions)
	var i CustomRoleInsertRow
	err := row.Scan(&i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const customRoleRemoteUsersRemove = `-- name: CustomRoleRemoteUsersRemove :exec
DELETE FROM group_remote_user_roles WHERE permission_group_id = $1::uuid AND role = $2::text
`

type CustomRoleRemoteUsersRemoveParams struct {
	GroupID string
	Role    string
}

func (q *Queries) CustomRoleRemoteUsersRemove(ctx context.Context, arg CustomRoleRemoteUsersRemoveParams) error {
	_, err := q.db.Exec(ctx, customRoleRemoteUsersRemove, arg.GroupID, arg.Role)
	return err
}

const customRoleUpdate = `-- name: CustomRoleUpdate :one
UPDATE group_custom_roles SET permissions = $1::text[], updated_at = now()
WHERE permission_group_id = $2::uuid AND role = $3::text
RETURNING created_at, updated_at
`

type CustomRoleUpdateParams struct {
	Permissions []string
	GroupID     string
	Role        string
}

type CustomRoleUpdateRow struct {
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CustomRoleUpdate(ctx context.Context, arg CustomRoleUpdateParams) (CustomRoleUpdateRow, error) {
	row := q.db.QueryRow(ctx, customRoleUpdate, arg.Permissions, arg.GroupID, arg.Role)
	var i CustomRoleUpdateRow
	err := row.Scan(&i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const customRoleUsersRemove = `-- name: CustomRoleUsersRemove :many
DELETE FROM group_user_roles WHERE permission_group_id = $1::uuid AND role = $2::text
RETURNING user_id::text
`

type CustomRoleUsersRemoveParams struct {
	GroupID string
	Role    string
}

func (q *Queries) CustomRoleUsersRemove(ctx context.Context, arg CustomRoleUsersRemoveParams) ([]string, error) {
	rows, err := q.db.Query(ctx, customRoleUsersRemove, arg.GroupID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const customRolesByGroup = `-- name: CustomRolesByGroup :many

SELECT role, permissions, created_at, updated_at FROM group_custom_roles
WHERE permission_group_id = $1::uuid ORDER BY role
`

type CustomRolesByGroupRow struct {
	Role        string
	Permissions []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Custom roles (#448): roles a group defines at run time. Checks read them
// joined into the assignment they resolve; these serve their management.
func (q *Queries) CustomRolesByGroup(ctx context.Context, groupID string) ([]CustomRolesByGroupRow, error) {
	rows, err := q.db.Query(ctx, customRolesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomRolesByGroupRow
	for rows.Next() {
		var i CustomRolesByGroupRow
		if err := rows.Scan(
			&i.Role,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
