// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delegated_users.sql

package db

import (
	"context"
	"time"
)

const delegatedUserByAppSubject = `-- name: DelegatedUserByAppSubject :one
SELECT id::text, remote_application_id::text AS remote_application_id, issuer, subject, first_seen_at, last_seen_at
FROM profiles.delegated_users
WHERE remote_application_id = $1::uuid AND subject = $2
`

type DelegatedUserByAppSubjectParams struct {
	RemoteApplicationID string
	Subject             string
}

type DelegatedUserByAppSubjectRow struct {
	ID                  string
	RemoteApplicationID string
	Issuer              string
	Subject             string
	FirstSeenAt         time.Time
	LastSeenAt          time.Time
}

func (q *Queries) DelegatedUserByAppSubject(ctx context.Context, arg DelegatedUserByAppSubjectParams) (DelegatedUserByAppSubjectRow, error) {
	row := q.db.QueryRow(ctx, delegatedUserByAppSubject, arg.RemoteApplicationID, arg.Subject)
	var i DelegatedUserByAppSubjectRow
	err := row.Scan(
		&i.ID,
		&i.RemoteApplicationID,
		&i.Issuer,
		&i.Subject,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const delegatedUserTouch = `-- name: DelegatedUserTouch :one

INSERT INTO profiles.delegated_users (remote_application_id, issuer, subject)
VALUES ($1::uuid, $2, $3)
ON CONFLICT (remote_application_id, subject) DO UPDATE
  SET last_seen_at = now()
RETURNING id::text, remote_application_id::text AS remote_application_id, issuer, subject, first_seen_at, last_seen_at
`

type DelegatedUserTouchParams struct {
	RemoteApplicationID string
	Issuer              string
	Subject             string
}

type DelegatedUserTouchRow struct {
	ID                  string
	RemoteApplicationID string
	Issuer              string
	Subject             string
	FirstSeenAt         time.Time
	LastSeenAt          time.Time
}

// Delegated-user identity anchor (core/delegated_users.go, #81). A federated
// end-user vouched for by a remote_application (issuer). Cross-domain FK target
// for app + billing; authkit makes NO auth decision off this table.
// Idempotent upsert on the UNIQUE(remote_application_id, subject) natural key.
// The uuidv7 id is minted ONCE and RETURNED; callers stamp the returned value.
func (q *Queries) DelegatedUserTouch(ctx context.Context, arg DelegatedUserTouchParams) (DelegatedUserTouchRow, error) {
	row := q.db.QueryRow(ctx, delegatedUserTouch, arg.RemoteApplicationID, arg.Issuer, arg.Subject)
	var i DelegatedUserTouchRow
	err := row.Scan(
		&i.ID,
		&i.RemoteApplicationID,
		&i.Issuer,
		&i.Subject,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const delegatedUsersByApp = `-- name: DelegatedUsersByApp :many
SELECT id::text, remote_application_id::text AS remote_application_id, issuer, subject, first_seen_at, last_seen_at
FROM profiles.delegated_users
WHERE remote_application_id = $1::uuid
ORDER BY last_seen_at DESC
`

type DelegatedUsersByAppRow struct {
	ID                  string
	RemoteApplicationID string
	Issuer              string
	Subject             string
	FirstSeenAt         time.Time
	LastSeenAt          time.Time
}

func (q *Queries) DelegatedUsersByApp(ctx context.Context, remoteApplicationID string) ([]DelegatedUsersByAppRow, error) {
	rows, err := q.db.Query(ctx, delegatedUsersByApp, remoteApplicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DelegatedUsersByAppRow
	for rows.Next() {
		var i DelegatedUsersByAppRow
		if err := rows.Scan(
			&i.ID,
			&i.RemoteApplicationID,
			&i.Issuer,
			&i.Subject,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
