// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: erasure.sql

package db

import (
	"context"
	"time"
)

const erasureAcknowledge = `-- name: ErasureAcknowledge :execrows
UPDATE account_erasure_acknowledgements SET acknowledged_at = now()
WHERE user_id = $1::uuid AND issuer = $2::text AND acknowledged_at IS NULL
`

type ErasureAcknowledgeParams struct {
	UserID string
	Issuer string
}

func (q *Queries) ErasureAcknowledge(ctx context.Context, arg ErasureAcknowledgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, erasureAcknowledge, arg.UserID, arg.Issuer)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const erasureAcknowledgementsRequire = `-- name: ErasureAcknowledgementsRequire :exec
INSERT INTO account_erasure_acknowledgements (user_id, issuer, obligation_created_at)
SELECT o.user_id, issuer, o.created_at
FROM account_erasure_obligations o, unnest($1::text[]) AS issuer
WHERE o.user_id = $2::uuid
ON CONFLICT (user_id, issuer) DO NOTHING
`

type ErasureAcknowledgementsRequireParams struct {
	Issuers []string
	UserID  string
}

// Adds the deleting deployment's account issuers; an existing acknowledgement
// is never reopened.
func (q *Queries) ErasureAcknowledgementsRequire(ctx context.Context, arg ErasureAcknowledgementsRequireParams) error {
	_, err := q.db.Exec(ctx, erasureAcknowledgementsRequire, arg.Issuers, arg.UserID)
	return err
}

const erasureObligationCloseIfSettled = `-- name: ErasureObligationCloseIfSettled :execrows
DELETE FROM account_erasure_obligations
WHERE user_id = $1::uuid AND purged_at IS NOT NULL AND pending_sites = 0
`

// Closed = identity purged and every required site acknowledged.
func (q *Queries) ErasureObligationCloseIfSettled(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, erasureObligationCloseIfSettled, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const erasureObligationLock = `-- name: ErasureObligationLock :one
SELECT user_id FROM account_erasure_obligations WHERE user_id = $1::uuid FOR UPDATE
`

func (q *Queries) ErasureObligationLock(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, erasureObligationLock, userID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const erasureObligationMarkPurged = `-- name: ErasureObligationMarkPurged :exec
UPDATE account_erasure_obligations SET purged_at = now()
WHERE user_id = $1::uuid AND purged_at IS NULL
`

func (q *Queries) ErasureObligationMarkPurged(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, erasureObligationMarkPurged, userID)
	return err
}

const erasureObligationRecord = `-- name: ErasureObligationRecord :exec

INSERT INTO account_erasure_obligations (user_id, email, username, phone_number)
SELECT id, email, username, phone_number FROM users WHERE id = $1::uuid
ON CONFLICT (user_id) DO NOTHING
`

// Cross-site erasure handoff: obligations outlive the users row; purge selects
// only accounts every required site acknowledged.
// Captures the account's identifiers at deletion; a repeat keeps the original.
func (q *Queries) ErasureObligationRecord(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, erasureObligationRecord, userID)
	return err
}

const erasureObligationRefreshPending = `-- name: ErasureObligationRefreshPending :exec
UPDATE account_erasure_obligations o
SET pending_sites = (
  SELECT count(*) FROM account_erasure_acknowledgements a
  WHERE a.user_id = o.user_id AND a.acknowledged_at IS NULL)
WHERE o.user_id = $1::uuid
`

// Recomputes readiness under the caller-held row lock; never an increment.
func (q *Queries) ErasureObligationRefreshPending(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, erasureObligationRefreshPending, userID)
	return err
}

const erasureObligationsBacklog = `-- name: ErasureObligationsBacklog :many
SELECT a.issuer, count(*)::bigint AS pending, min(a.obligation_created_at)::timestamptz AS oldest_created_at
FROM account_erasure_acknowledgements a
WHERE a.acknowledged_at IS NULL
GROUP BY a.issuer
ORDER BY a.issuer
`

type ErasureObligationsBacklogRow struct {
	Issuer          string
	Pending         int64
	OldestCreatedAt time.Time
}

func (q *Queries) ErasureObligationsBacklog(ctx context.Context) ([]ErasureObligationsBacklogRow, error) {
	rows, err := q.db.Query(ctx, erasureObligationsBacklog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErasureObligationsBacklogRow
	for rows.Next() {
		var i ErasureObligationsBacklogRow
		if err := rows.Scan(&i.Issuer, &i.Pending, &i.OldestCreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const erasureObligationsPendingForIssuer = `-- name: ErasureObligationsPendingForIssuer :many
SELECT o.user_id, o.email, o.username, o.phone_number, a.obligation_created_at AS created_at, o.purged_at
FROM account_erasure_acknowledgements a
JOIN account_erasure_obligations o ON o.user_id = a.user_id
WHERE a.issuer = $1::text AND a.acknowledged_at IS NULL
  AND (a.obligation_created_at, a.user_id) > ($2::timestamptz, $3::uuid)
ORDER BY a.obligation_created_at, a.user_id
LIMIT $4::bigint
`

type ErasureObligationsPendingForIssuerParams struct {
	Issuer         string
	AfterCreatedAt time.Time
	AfterUserID    string
	MaxRows        int64
}

type ErasureObligationsPendingForIssuerRow struct {
	UserID      string
	Email       *string
	Username    *string
	PhoneNumber *string
	CreatedAt   time.Time
	PurgedAt    *time.Time
}

// Keyset page of obligations the issuer has not acknowledged, oldest first.
func (q *Queries) ErasureObligationsPendingForIssuer(ctx context.Context, arg ErasureObligationsPendingForIssuerParams) ([]ErasureObligationsPendingForIssuerRow, error) {
	rows, err := q.db.Query(ctx, erasureObligationsPendingForIssuer,
		arg.Issuer,
		arg.AfterCreatedAt,
		arg.AfterUserID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErasureObligationsPendingForIssuerRow
	for rows.Next() {
		var i ErasureObligationsPendingForIssuerRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Username,
			&i.PhoneNumber,
			&i.CreatedAt,
			&i.PurgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const erasurePurgeCandidates = `-- name: ErasurePurgeCandidates :many
SELECT o.user_id::text
FROM account_erasure_obligations o
WHERE o.purged_at IS NULL AND o.pending_sites = 0 AND o.created_at < $1::timestamptz
ORDER BY o.created_at, o.user_id
LIMIT $2::bigint
`

type ErasurePurgeCandidatesParams struct {
	Cutoff  time.Time
	MaxRows int64
}

// Index-ordered page of accounts deleted before the cutoff that every required
// site acknowledged; an unacknowledged backlog is never walked.
// Qualified ORDER BY: an unqualified user_id would bind to the ::text output
// column and cost an extra sort.
func (q *Queries) ErasurePurgeCandidates(ctx context.Context, arg ErasurePurgeCandidatesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, erasurePurgeCandidates, arg.Cutoff, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var o_user_id string
		if err := rows.Scan(&o_user_id); err != nil {
			return nil, err
		}
		items = append(items, o_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
