// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"time"
)

const accountEventByID = `-- name: AccountEventByID :one
SELECT id, issuer, stream, event_id, kind, occurred_at, user_id, group_id, persona, application_id, previous_value, current_value, reason, until, attempts, retry_at, subject_kind, subject_id, invoker_issuer, invoker_id, credential_kind, credential_id, role, client_id FROM account_events WHERE id = $1
`

func (q *Queries) AccountEventByID(ctx context.Context, id int64) (AccountEvent, error) {
	row := q.db.QueryRow(ctx, accountEventByID, id)
	var i AccountEvent
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Stream,
		&i.EventID,
		&i.Kind,
		&i.OccurredAt,
		&i.UserID,
		&i.GroupID,
		&i.Persona,
		&i.ApplicationID,
		&i.PreviousValue,
		&i.CurrentValue,
		&i.Reason,
		&i.Until,
		&i.Attempts,
		&i.RetryAt,
		&i.SubjectKind,
		&i.SubjectID,
		&i.InvokerIssuer,
		&i.InvokerID,
		&i.CredentialKind,
		&i.CredentialID,
		&i.Role,
		&i.ClientID,
	)
	return i, err
}

const accountEventDelete = `-- name: AccountEventDelete :exec
DELETE FROM account_events WHERE id = $1
`

func (q *Queries) AccountEventDelete(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, accountEventDelete, id)
	return err
}

const accountEventEarlierPending = `-- name: AccountEventEarlierPending :one
SELECT (count(*) > 0)::boolean AS blocked,
       COALESCE(EXTRACT(EPOCH FROM max(retry_at) - statement_timestamp()), 0)::float8 AS wait
FROM account_events
WHERE issuer = $1 AND stream = $2 AND id < $3
`

type AccountEventEarlierPendingParams struct {
	Issuer string
	Stream string
	ID     int64
}

type AccountEventEarlierPendingRow struct {
	Blocked bool
	Wait    float64
}

// Whether an earlier event of the stream is still pending, and the seconds
// until the latest of their retries.
func (q *Queries) AccountEventEarlierPending(ctx context.Context, arg AccountEventEarlierPendingParams) (AccountEventEarlierPendingRow, error) {
	row := q.db.QueryRow(ctx, accountEventEarlierPending, arg.Issuer, arg.Stream, arg.ID)
	var i AccountEventEarlierPendingRow
	err := row.Scan(&i.Blocked, &i.Wait)
	return i, err
}

const accountEventFleetsForShare = `-- name: AccountEventFleetsForShare :many

SELECT issuer, river_schema FROM account_delivery_fleets
WHERE events AND issuer = ANY($1::text[])
ORDER BY issuer FOR KEY SHARE
`

type AccountEventFleetsForShareRow struct {
	Issuer      string
	RiverSchema string
}

// Durable account and group events (Deps.OnEvent): one account_events row per
// subscribed issuer, recorded in the change's transaction, deleted on delivery.
// The subscribed issuers' fleets, key-share locked until the change commits.
func (q *Queries) AccountEventFleetsForShare(ctx context.Context, issuers []string) ([]AccountEventFleetsForShareRow, error) {
	rows, err := q.db.Query(ctx, accountEventFleetsForShare, issuers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountEventFleetsForShareRow
	for rows.Next() {
		var i AccountEventFleetsForShareRow
		if err := rows.Scan(&i.Issuer, &i.RiverSchema); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountEventInsert = `-- name: AccountEventInsert :one
INSERT INTO account_events
    (issuer, stream, event_id, kind, subject_kind, subject_id, invoker_issuer, invoker_id, credential_kind, credential_id,
     user_id, group_id, persona, application_id, previous_value, current_value, reason, until, role, client_id)
VALUES
    ($1, $2, $3, $4, $5, $6,
     $7, $8, $9, $10,
     $11, $12, $13, $14,
     $15, $16, $17, $18, $19, $20)
RETURNING id
`

type AccountEventInsertParams struct {
	Issuer         string
	Stream         string
	EventID        string
	Kind           string
	SubjectKind    string
	SubjectID      string
	InvokerIssuer  string
	InvokerID      string
	CredentialKind string
	CredentialID   string
	UserID         *string
	GroupID        *string
	Persona        string
	ApplicationID  *string
	PreviousValue  string
	CurrentValue   string
	Reason         string
	Until          *time.Time
	Role           string
	ClientID       string
}

func (q *Queries) AccountEventInsert(ctx context.Context, arg AccountEventInsertParams) (int64, error) {
	row := q.db.QueryRow(ctx, accountEventInsert,
		arg.Issuer,
		arg.Stream,
		arg.EventID,
		arg.Kind,
		arg.SubjectKind,
		arg.SubjectID,
		arg.InvokerIssuer,
		arg.InvokerID,
		arg.CredentialKind,
		arg.CredentialID,
		arg.UserID,
		arg.GroupID,
		arg.Persona,
		arg.ApplicationID,
		arg.PreviousValue,
		arg.CurrentValue,
		arg.Reason,
		arg.Until,
		arg.Role,
		arg.ClientID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const accountEventRetry = `-- name: AccountEventRetry :exec
UPDATE account_events
SET attempts = attempts + 1, retry_at = statement_timestamp() + make_interval(secs => $1::float8)
WHERE id = $2
`

type AccountEventRetryParams struct {
	DelaySeconds float64
	ID           int64
}

func (q *Queries) AccountEventRetry(ctx context.Context, arg AccountEventRetryParams) error {
	_, err := q.db.Exec(ctx, accountEventRetry, arg.DelaySeconds, arg.ID)
	return err
}
