// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: global_roles.sql

package db

import (
	"context"
)

const globalActiveAdminCount = `-- name: GlobalActiveAdminCount :one
SELECT COUNT(*)
FROM profiles.global_user_roles ur
JOIN profiles.users u ON u.id = ur.user_id
WHERE ur.role_id = $1
  AND u.deleted_at IS NULL
  AND u.banned_at IS NULL
`

func (q *Queries) GlobalActiveAdminCount(ctx context.Context, roleID string) (int64, error) {
	row := q.db.QueryRow(ctx, globalActiveAdminCount, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const globalAdminRoleIDForUpdate = `-- name: GlobalAdminRoleIDForUpdate :one
SELECT id FROM profiles.global_roles WHERE slug = 'admin' AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) GlobalAdminRoleIDForUpdate(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, globalAdminRoleIDForUpdate)
	var id string
	err := row.Scan(&id)
	return id, err
}

const globalRoleIDBySlug = `-- name: GlobalRoleIDBySlug :one
SELECT id FROM profiles.global_roles WHERE slug = $1
`

func (q *Queries) GlobalRoleIDBySlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRow(ctx, globalRoleIDBySlug, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const globalRoleSlugsByUser = `-- name: GlobalRoleSlugsByUser :many

SELECT r.slug
FROM profiles.global_user_roles ur
JOIN profiles.global_roles r ON ur.role_id = r.id
WHERE ur.user_id = $1 AND r.deleted_at IS NULL
`

// Global (platform) role queries (core/service.go).
func (q *Queries) GlobalRoleSlugsByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, globalRoleSlugsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalRoleUpsert = `-- name: GlobalRoleUpsert :exec
INSERT INTO profiles.global_roles (name, slug, description)
VALUES ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  updated_at = NOW(),
  deleted_at = NULL
`

type GlobalRoleUpsertParams struct {
	Name        string
	Slug        string
	Description *string
}

func (q *Queries) GlobalRoleUpsert(ctx context.Context, arg GlobalRoleUpsertParams) error {
	_, err := q.db.Exec(ctx, globalRoleUpsert, arg.Name, arg.Slug, arg.Description)
	return err
}

const globalUserHasActiveRole = `-- name: GlobalUserHasActiveRole :one
SELECT EXISTS (
  SELECT 1 FROM profiles.global_user_roles ur
  JOIN profiles.global_roles r ON ur.role_id = r.id
  WHERE ur.user_id = $1 AND r.slug = $2
    AND r.deleted_at IS NULL
    AND EXISTS (
      SELECT 1 FROM profiles.users u
      WHERE u.id = $1 AND u.deleted_at IS NULL AND u.banned_at IS NULL
    )
)
`

type GlobalUserHasActiveRoleParams struct {
	UserID string
	Slug   string
}

func (q *Queries) GlobalUserHasActiveRole(ctx context.Context, arg GlobalUserHasActiveRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, globalUserHasActiveRole, arg.UserID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const globalUserRoleDelete = `-- name: GlobalUserRoleDelete :execrows
DELETE FROM profiles.global_user_roles WHERE user_id = $1 AND role_id = $2
`

type GlobalUserRoleDeleteParams struct {
	UserID string
	RoleID string
}

func (q *Queries) GlobalUserRoleDelete(ctx context.Context, arg GlobalUserRoleDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, globalUserRoleDelete, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const globalUserRoleDeleteBySlug = `-- name: GlobalUserRoleDeleteBySlug :execrows
DELETE FROM profiles.global_user_roles ur
USING profiles.global_roles r
WHERE ur.role_id = r.id AND ur.user_id = $1 AND r.slug = $2 AND r.deleted_at IS NULL
`

type GlobalUserRoleDeleteBySlugParams struct {
	UserID string
	Slug   string
}

func (q *Queries) GlobalUserRoleDeleteBySlug(ctx context.Context, arg GlobalUserRoleDeleteBySlugParams) (int64, error) {
	result, err := q.db.Exec(ctx, globalUserRoleDeleteBySlug, arg.UserID, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const globalUserRoleExists = `-- name: GlobalUserRoleExists :one
SELECT EXISTS (SELECT 1 FROM profiles.global_user_roles WHERE user_id = $1 AND role_id = $2)
`

type GlobalUserRoleExistsParams struct {
	UserID string
	RoleID string
}

func (q *Queries) GlobalUserRoleExists(ctx context.Context, arg GlobalUserRoleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, globalUserRoleExists, arg.UserID, arg.RoleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const globalUserRoleInsert = `-- name: GlobalUserRoleInsert :exec
INSERT INTO profiles.global_user_roles (id, user_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type GlobalUserRoleInsertParams struct {
	ID     string
	UserID string
	RoleID string
}

func (q *Queries) GlobalUserRoleInsert(ctx context.Context, arg GlobalUserRoleInsertParams) error {
	_, err := q.db.Exec(ctx, globalUserRoleInsert, arg.ID, arg.UserID, arg.RoleID)
	return err
}
