// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"
)

const identityUsersByIDs = `-- name: IdentityUsersByIDs :many

SELECT id, username, email
FROM profiles.users
WHERE id = ANY($1::uuid[])
`

type IdentityUsersByIDsRow struct {
	ID       string
	Username *string
	Email    *string
}

// Batch user projections (core user enrichment paths).
func (q *Queries) IdentityUsersByIDs(ctx context.Context, ids []string) ([]IdentityUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, identityUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityUsersByIDsRow
	for rows.Next() {
		var i IdentityUsersByIDsRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
