// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"
	"time"
)

const identityPublicUsersByIDs = `-- name: IdentityPublicUsersByIDs :many
SELECT id, username, avatar_url, created_at, deleted_at
FROM users
WHERE id = ANY($1::uuid[])
`

type IdentityPublicUsersByIDsRow struct {
	ID        string
	Username  *string
	AvatarUrl *string
	CreatedAt time.Time
	DeletedAt *time.Time
}

// The PUBLIC-safe display projection (#268): no email column is selected, so a
// caller cannot leak one by forgetting a tag. Soft-deleted rows ARE returned —
// the Go layer tombstones them — so a reference to a deleted author resolves to
// a stable placeholder instead of silently vanishing.
func (q *Queries) IdentityPublicUsersByIDs(ctx context.Context, ids []string) ([]IdentityPublicUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, identityPublicUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityPublicUsersByIDsRow
	for rows.Next() {
		var i IdentityPublicUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
