// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package db

import (
	"context"
	"time"
)

const importHeldProviders = `-- name: ImportHeldProviders :many
SELECT p.issuer, p.subject FROM user_providers p
JOIN unnest($1::text[], $2::text[]) AS k(issuer, subject)
  ON p.issuer = k.issuer AND p.subject = k.subject
`

type ImportHeldProvidersParams struct {
	Issuers  []string
	Subjects []string
}

type ImportHeldProvidersRow struct {
	Issuer  string
	Subject string
}

// The identities some account holds, verified or not.
func (q *Queries) ImportHeldProviders(ctx context.Context, arg ImportHeldProvidersParams) ([]ImportHeldProvidersRow, error) {
	rows, err := q.db.Query(ctx, importHeldProviders, arg.Issuers, arg.Subjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportHeldProvidersRow
	for rows.Next() {
		var i ImportHeldProvidersRow
		if err := rows.Scan(&i.Issuer, &i.Subject); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importHitsByEmail = `-- name: ImportHitsByEmail :many
SELECT lower(email::text)::text AS key, id::text AS user_id, (deleted_at IS NOT NULL)::boolean AS deleted,
       email_verified AS verified, false AS missing
FROM users WHERE email = ANY($1::text[]::public.citext[])
`

type ImportHitsByEmailRow struct {
	Key      string
	UserID   string
	Deleted  bool
	Verified bool
	Missing  bool
}

func (q *Queries) ImportHitsByEmail(ctx context.Context, emails []string) ([]ImportHitsByEmailRow, error) {
	rows, err := q.db.Query(ctx, importHitsByEmail, emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportHitsByEmailRow
	for rows.Next() {
		var i ImportHitsByEmailRow
		if err := rows.Scan(
			&i.Key,
			&i.UserID,
			&i.Deleted,
			&i.Verified,
			&i.Missing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importHitsByID = `-- name: ImportHitsByID :many

SELECT id::text AS key, id::text AS user_id, (deleted_at IS NOT NULL)::boolean AS deleted,
       true AS verified, false AS missing
FROM users WHERE id = ANY($1::uuid[])
`

type ImportHitsByIDRow struct {
	Key      string
	UserID   string
	Deleted  bool
	Verified bool
	Missing  bool
}

// The ImportHits* reads share one row shape: the matched key, the account,
// and whether it is deleted, the key verified on it, or a name reserved for
// a purged account.
func (q *Queries) ImportHitsByID(ctx context.Context, ids []string) ([]ImportHitsByIDRow, error) {
	rows, err := q.db.Query(ctx, importHitsByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportHitsByIDRow
	for rows.Next() {
		var i ImportHitsByIDRow
		if err := rows.Scan(
			&i.Key,
			&i.UserID,
			&i.Deleted,
			&i.Verified,
			&i.Missing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importHitsByName = `-- name: ImportHitsByName :many
SELECT c.name AS key, c.owner_id::text AS user_id, COALESCE(u.deleted_at IS NOT NULL, false)::boolean AS deleted,
       false AS verified, (u.id IS NULL)::boolean AS missing
FROM name_claims c LEFT JOIN users u ON u.id = c.owner_id
WHERE c.name = ANY($1::text[])
  AND (c.canonical OR c.expires_at IS NULL OR c.expires_at > $2::timestamptz)
`

type ImportHitsByNameParams struct {
	Names []string
	Now   time.Time
}

type ImportHitsByNameRow struct {
	Key      string
	UserID   string
	Deleted  bool
	Verified bool
	Missing  bool
}

// A canonical name or a live alias.
func (q *Queries) ImportHitsByName(ctx context.Context, arg ImportHitsByNameParams) ([]ImportHitsByNameRow, error) {
	rows, err := q.db.Query(ctx, importHitsByName, arg.Names, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportHitsByNameRow
	for rows.Next() {
		var i ImportHitsByNameRow
		if err := rows.Scan(
			&i.Key,
			&i.UserID,
			&i.Deleted,
			&i.Verified,
			&i.Missing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importHitsByPhone = `-- name: ImportHitsByPhone :many
SELECT COALESCE(phone_number, '')::text AS key, id::text AS user_id, (deleted_at IS NOT NULL)::boolean AS deleted,
       phone_verified AS verified, false AS missing
FROM users WHERE phone_number = ANY($1::text[])
`

type ImportHitsByPhoneRow struct {
	Key      string
	UserID   string
	Deleted  bool
	Verified bool
	Missing  bool
}

func (q *Queries) ImportHitsByPhone(ctx context.Context, phones []string) ([]ImportHitsByPhoneRow, error) {
	rows, err := q.db.Query(ctx, importHitsByPhone, phones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportHitsByPhoneRow
	for rows.Next() {
		var i ImportHitsByPhoneRow
		if err := rows.Scan(
			&i.Key,
			&i.UserID,
			&i.Deleted,
			&i.Verified,
			&i.Missing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importInsertPasswords = `-- name: ImportInsertPasswords :exec
INSERT INTO user_passwords (user_id, password_hash, hash_algo)
SELECT k.user_id, k.password_hash, k.hash_algo
FROM unnest($1::uuid[], $2::text[], $3::text[])
  AS k(user_id, password_hash, hash_algo)
ON CONFLICT (user_id) DO NOTHING
`

type ImportInsertPasswordsParams struct {
	UserIds        []string
	PasswordHashes []string
	HashAlgos      []string
}

func (q *Queries) ImportInsertPasswords(ctx context.Context, arg ImportInsertPasswordsParams) error {
	_, err := q.db.Exec(ctx, importInsertPasswords, arg.UserIds, arg.PasswordHashes, arg.HashAlgos)
	return err
}

const importInsertProviders = `-- name: ImportInsertProviders :execrows
INSERT INTO user_providers (user_id, issuer, provider_slug, subject, email_at_provider)
SELECT k.user_id, k.issuer, NULLIF(k.provider_slug, ''), k.subject, NULLIF(k.email_at_provider, '')
FROM unnest($1::uuid[], $2::text[], $3::text[],
            $4::text[], $5::text[])
  AS k(user_id, issuer, provider_slug, subject, email_at_provider)
ON CONFLICT DO NOTHING
`

type ImportInsertProvidersParams struct {
	UserIds          []string
	Issuers          []string
	ProviderSlugs    []string
	Subjects         []string
	EmailsAtProvider []string
}

// An empty provider slug or provider email is stored as NULL.
func (q *Queries) ImportInsertProviders(ctx context.Context, arg ImportInsertProvidersParams) (int64, error) {
	result, err := q.db.Exec(ctx, importInsertProviders,
		arg.UserIds,
		arg.Issuers,
		arg.ProviderSlugs,
		arg.Subjects,
		arg.EmailsAtProvider,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importInsertUsers = `-- name: ImportInsertUsers :many
INSERT INTO users (id, email, phone_number, username, email_verified, phone_verified, banned_at, banned_until,
                   ban_reason, metadata, created_at, updated_at, last_login, preferred_language, avatar_url, deleted_at)
SELECT r.id, r.email, r.phone_number, r.username, r.email_verified, r.phone_verified, r.banned_at, r.banned_until,
       r.ban_reason, r.metadata, r.created_at, r.updated_at, r.last_login, r.preferred_language, r.avatar_url, r.deleted_at
FROM jsonb_populate_recordset(NULL::users, $1::jsonb) AS r
ON CONFLICT DO NOTHING
RETURNING id::text
`

// users is a JSON array of users rows (column-named keys; a missing key is
// NULL). A row losing a uniqueness race to another writer is not returned.
func (q *Queries) ImportInsertUsers(ctx context.Context, users []byte) ([]string, error) {
	rows, err := q.db.Query(ctx, importInsertUsers, users)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importMergePassword = `-- name: ImportMergePassword :exec
INSERT INTO user_passwords (user_id, password_hash, hash_algo)
VALUES ($1::uuid, $2, $3)
ON CONFLICT (user_id) DO NOTHING
`

type ImportMergePasswordParams struct {
	UserID       string
	PasswordHash string
	HashAlgo     string
}

func (q *Queries) ImportMergePassword(ctx context.Context, arg ImportMergePasswordParams) error {
	_, err := q.db.Exec(ctx, importMergePassword, arg.UserID, arg.PasswordHash, arg.HashAlgo)
	return err
}

const importMergeUser = `-- name: ImportMergeUser :exec
UPDATE users SET
  metadata = COALESCE(metadata, '{}'::jsonb) || $1::jsonb,
  created_at = LEAST(created_at, $2),
  last_login = GREATEST(last_login, $3),
  preferred_language = COALESCE(preferred_language, $4),
  avatar_url = COALESCE(avatar_url, $5),
  updated_at = now()
WHERE id = $6::uuid
`

type ImportMergeUserParams struct {
	Metadata          []byte
	CreatedAt         time.Time
	LastLogin         *time.Time
	PreferredLanguage *string
	AvatarURL         *string
	ID                string
}

func (q *Queries) ImportMergeUser(ctx context.Context, arg ImportMergeUserParams) error {
	_, err := q.db.Exec(ctx, importMergeUser,
		arg.Metadata,
		arg.CreatedAt,
		arg.LastLogin,
		arg.PreferredLanguage,
		arg.AvatarURL,
		arg.ID,
	)
	return err
}

const importReleaseAliases = `-- name: ImportReleaseAliases :exec

DELETE FROM name_claims
WHERE name = ANY($1::text[])
  AND NOT canonical AND expires_at <= $2::timestamptz
`

type ImportReleaseAliasesParams struct {
	Names []string
	Now   time.Time
}

// ImportUsers: bulk account import, one chunk per transaction.
// Expired aliases of the chunk's names neither match nor block.
func (q *Queries) ImportReleaseAliases(ctx context.Context, arg ImportReleaseAliasesParams) error {
	_, err := q.db.Exec(ctx, importReleaseAliases, arg.Names, arg.Now)
	return err
}

const importSetBannedBy = `-- name: ImportSetBannedBy :exec
UPDATE users u SET banned_by = k.banned_by
FROM unnest($1::uuid[], $2::uuid[]) AS k(user_id, banned_by)
WHERE u.id = k.user_id AND u.banned_at IS NOT NULL AND u.banned_by IS NULL
  AND EXISTS(SELECT 1 FROM users b WHERE b.id = k.banned_by)
`

type ImportSetBannedByParams struct {
	UserIds  []string
	BannedBy []string
}

// Records who banned imported accounts; a banner that is no account leaves
// banned_by NULL.
func (q *Queries) ImportSetBannedBy(ctx context.Context, arg ImportSetBannedByParams) error {
	_, err := q.db.Exec(ctx, importSetBannedBy, arg.UserIds, arg.BannedBy)
	return err
}
