// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"
	"time"
)

const accountInviteByCodeForUpdate = `-- name: AccountInviteByCodeForUpdate :one
SELECT i.id, g.id AS group_id, g.persona, COALESCE(i.role, '')::text AS role, i.consumed_at, i.expires_at, i.revoked_at,
  (i.invited_by IS NULL OR EXISTS(SELECT 1 FROM usable_users WHERE id = i.invited_by))::boolean AS issuer_live,
  EXISTS(SELECT 1 FROM users u WHERE u.id = $1::uuid AND lower(u.email::text) = lower(i.email::text) AND u.email_verified)::boolean AS addressed
FROM account_registration_invites i JOIN permission_groups g ON g.id = i.permission_group_id AND g.deleted_at IS NULL
WHERE i.code_hash = $2 AND i.permission_group_id = $3::uuid
FOR UPDATE OF i
`

type AccountInviteByCodeForUpdateParams struct {
	UserID   string
	CodeHash string
	GroupID  string
}

type AccountInviteByCodeForUpdateRow struct {
	ID         string
	GroupID    string
	Persona    string
	Role       string
	ConsumedAt *time.Time
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	IssuerLive bool
	Addressed  bool
}

// AccountInviteByCodeForUpdate: addressed is whether user_id has verified the
// invited address.
func (q *Queries) AccountInviteByCodeForUpdate(ctx context.Context, arg AccountInviteByCodeForUpdateParams) (AccountInviteByCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, accountInviteByCodeForUpdate, arg.UserID, arg.CodeHash, arg.GroupID)
	var i AccountInviteByCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Persona,
		&i.Role,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IssuerLive,
		&i.Addressed,
	)
	return i, err
}

const accountInviteConsume = `-- name: AccountInviteConsume :exec
UPDATE account_registration_invites SET consumed_at = now()
WHERE id = $1
`

func (q *Queries) AccountInviteConsume(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, accountInviteConsume, id)
	return err
}

const accountInviteForRevoke = `-- name: AccountInviteForRevoke :one
SELECT COALESCE(role, '')::text AS role, revoked_at, consumed_at FROM account_registration_invites
WHERE id = $1 AND (permission_group_id = $2::uuid OR ($3::boolean AND permission_group_id IS NULL))
FOR UPDATE
`

type AccountInviteForRevokeParams struct {
	ID      string
	GroupID string
	Root    bool
}

type AccountInviteForRevokeRow struct {
	Role       string
	RevokedAt  *time.Time
	ConsumedAt *time.Time
}

func (q *Queries) AccountInviteForRevoke(ctx context.Context, arg AccountInviteForRevokeParams) (AccountInviteForRevokeRow, error) {
	row := q.db.QueryRow(ctx, accountInviteForRevoke, arg.ID, arg.GroupID, arg.Root)
	var i AccountInviteForRevokeRow
	err := row.Scan(&i.Role, &i.RevokedAt, &i.ConsumedAt)
	return i, err
}

const accountInviteForUpdate = `-- name: AccountInviteForUpdate :one
SELECT i.id, i.permission_group_id, i.role, g.persona
FROM account_registration_invites i LEFT JOIN permission_groups g ON g.id = i.permission_group_id
WHERE i.code_hash = $1 AND i.revoked_at IS NULL AND i.consumed_at IS NULL AND i.expires_at > now()
  AND (i.invited_by IS NULL OR EXISTS(SELECT 1 FROM usable_users WHERE id = i.invited_by))
  AND i.permission_group_id IS NOT DISTINCT FROM $2::uuid
FOR UPDATE OF i
`

type AccountInviteForUpdateParams struct {
	CodeHash string
	GroupID  *string
}

type AccountInviteForUpdateRow struct {
	ID                string
	PermissionGroupID *string
	Role              *string
	Persona           *string
}

func (q *Queries) AccountInviteForUpdate(ctx context.Context, arg AccountInviteForUpdateParams) (AccountInviteForUpdateRow, error) {
	row := q.db.QueryRow(ctx, accountInviteForUpdate, arg.CodeHash, arg.GroupID)
	var i AccountInviteForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PermissionGroupID,
		&i.Role,
		&i.Persona,
	)
	return i, err
}

const accountInviteGroupByCode = `-- name: AccountInviteGroupByCode :one
SELECT permission_group_id::uuid AS group_id FROM account_registration_invites
WHERE code_hash = $1 AND permission_group_id IS NOT NULL
`

func (q *Queries) AccountInviteGroupByCode(ctx context.Context, codeHash string) (string, error) {
	row := q.db.QueryRow(ctx, accountInviteGroupByCode, codeHash)
	var group_id string
	err := row.Scan(&group_id)
	return group_id, err
}

const accountInviteGroupLive = `-- name: AccountInviteGroupLive :one
SELECT i.permission_group_id FROM account_registration_invites i
WHERE i.code_hash = $1 AND i.revoked_at IS NULL AND i.consumed_at IS NULL AND i.expires_at > now()
  AND (i.invited_by IS NULL OR EXISTS(SELECT 1 FROM usable_users WHERE id = i.invited_by))
`

func (q *Queries) AccountInviteGroupLive(ctx context.Context, codeHash string) (*string, error) {
	row := q.db.QueryRow(ctx, accountInviteGroupLive, codeHash)
	var permission_group_id *string
	err := row.Scan(&permission_group_id)
	return permission_group_id, err
}

const accountInviteInsert = `-- name: AccountInviteInsert :one
INSERT INTO account_registration_invites (email, invited_by, code_hash, expires_at, permission_group_id, role, catalog_issuer)
VALUES ($1, $2::uuid, $3, $4, $5::uuid, $6::text, $7::text)
RETURNING id, created_at
`

type AccountInviteInsertParams struct {
	Email         string
	InvitedBy     *string
	CodeHash      string
	ExpiresAt     time.Time
	GroupID       *string
	Role          *string
	CatalogIssuer string
}

type AccountInviteInsertRow struct {
	ID        string
	CreatedAt time.Time
}

func (q *Queries) AccountInviteInsert(ctx context.Context, arg AccountInviteInsertParams) (AccountInviteInsertRow, error) {
	row := q.db.QueryRow(ctx, accountInviteInsert,
		arg.Email,
		arg.InvitedBy,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.GroupID,
		arg.Role,
		arg.CatalogIssuer,
	)
	var i AccountInviteInsertRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const accountInviteValid = `-- name: AccountInviteValid :one
SELECT EXISTS(
  SELECT 1 FROM account_registration_invites i
  WHERE i.code_hash = $1 AND i.revoked_at IS NULL AND i.consumed_at IS NULL AND i.expires_at > now()
    AND (i.invited_by IS NULL OR EXISTS(SELECT 1 FROM usable_users WHERE id = i.invited_by)))::boolean
`

// AccountInviteValid: code_hash names a live registration invite.
func (q *Queries) AccountInviteValid(ctx context.Context, codeHash string) (bool, error) {
	row := q.db.QueryRow(ctx, accountInviteValid, codeHash)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const accountInvitesRevokeInvitedBy = `-- name: AccountInvitesRevokeInvitedBy :exec
UPDATE account_registration_invites SET revoked_at = now()
WHERE invited_by = $1::uuid AND revoked_at IS NULL AND consumed_at IS NULL
`

func (q *Queries) AccountInvitesRevokeInvitedBy(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, accountInvitesRevokeInvitedBy, userID)
	return err
}

const invitationsByGroup = `-- name: InvitationsByGroup :many
SELECT i.id, i.role, i.email, i.created_by, i.created_at, i.expires_at, i.redeemed_at, i.revoked_at FROM (
  SELECT l.id, l.role, ''::text AS email, COALESCE(l.invited_by::text, '')::text AS created_by,
    l.created_at, l.expires_at, l.redeemed_at, l.revoked_at
  FROM group_invite_links l WHERE l.permission_group_id = $1::uuid
  UNION ALL
  SELECT a.id, COALESCE(a.role, '')::text, a.email::text, COALESCE(a.invited_by::text, '')::text,
    a.created_at, a.expires_at, a.consumed_at, a.revoked_at
  FROM account_registration_invites a
  WHERE a.permission_group_id = $1::uuid OR ($2::boolean AND a.permission_group_id IS NULL)) i
WHERE $3::uuid IS NULL OR i.id < $3::uuid
ORDER BY i.id DESC
LIMIT $4::bigint
`

type InvitationsByGroupParams struct {
	GroupID   string
	Root      bool
	After     *string
	PageLimit int64
}

type InvitationsByGroupRow struct {
	ID         string
	Role       string
	Email      string
	CreatedBy  string
	CreatedAt  time.Time
	ExpiresAt  *time.Time
	RedeemedAt *time.Time
	RevokedAt  *time.Time
}

// InvitationsByGroup lists a group's invite links and email invitations,
// newest first, never a code hash. In the root group (root) it includes the
// plain registration invites, which have no group.
func (q *Queries) InvitationsByGroup(ctx context.Context, arg InvitationsByGroupParams) ([]InvitationsByGroupRow, error) {
	rows, err := q.db.Query(ctx, invitationsByGroup,
		arg.GroupID,
		arg.Root,
		arg.After,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvitationsByGroupRow
	for rows.Next() {
		var i InvitationsByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Email,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RedeemedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inviteLinkByCodeForUpdate = `-- name: InviteLinkByCodeForUpdate :one
SELECT l.id, g.id AS group_id, g.persona, l.role, l.redeemed_at, l.expires_at, l.revoked_at,
  (l.invited_by IS NULL OR EXISTS(SELECT 1 FROM usable_users WHERE id = l.invited_by))::boolean AS issuer_live
FROM group_invite_links l JOIN permission_groups g ON g.id = l.permission_group_id
WHERE l.code_hash = $1 AND l.permission_group_id = $2
FOR UPDATE OF l
`

type InviteLinkByCodeForUpdateParams struct {
	CodeHash string
	GroupID  string
}

type InviteLinkByCodeForUpdateRow struct {
	ID         string
	GroupID    string
	Persona    string
	Role       string
	RedeemedAt *time.Time
	ExpiresAt  *time.Time
	RevokedAt  *time.Time
	IssuerLive bool
}

func (q *Queries) InviteLinkByCodeForUpdate(ctx context.Context, arg InviteLinkByCodeForUpdateParams) (InviteLinkByCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, inviteLinkByCodeForUpdate, arg.CodeHash, arg.GroupID)
	var i InviteLinkByCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Persona,
		&i.Role,
		&i.RedeemedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IssuerLive,
	)
	return i, err
}

const inviteLinkForRevoke = `-- name: InviteLinkForRevoke :one
SELECT role, revoked_at, redeemed_at FROM group_invite_links
WHERE id = $1 AND permission_group_id = $2 FOR UPDATE
`

type InviteLinkForRevokeParams struct {
	ID      string
	GroupID string
}

type InviteLinkForRevokeRow struct {
	Role       string
	RevokedAt  *time.Time
	RedeemedAt *time.Time
}

func (q *Queries) InviteLinkForRevoke(ctx context.Context, arg InviteLinkForRevokeParams) (InviteLinkForRevokeRow, error) {
	row := q.db.QueryRow(ctx, inviteLinkForRevoke, arg.ID, arg.GroupID)
	var i InviteLinkForRevokeRow
	err := row.Scan(&i.Role, &i.RevokedAt, &i.RedeemedAt)
	return i, err
}

const inviteLinkGroupByCode = `-- name: InviteLinkGroupByCode :one
SELECT permission_group_id FROM group_invite_links WHERE code_hash = $1
`

func (q *Queries) InviteLinkGroupByCode(ctx context.Context, codeHash string) (string, error) {
	row := q.db.QueryRow(ctx, inviteLinkGroupByCode, codeHash)
	var permission_group_id string
	err := row.Scan(&permission_group_id)
	return permission_group_id, err
}

const inviteLinkInsert = `-- name: InviteLinkInsert :one

INSERT INTO group_invite_links (permission_group_id, role, invited_by, code_hash, expires_at, catalog_issuer)
VALUES ($1, $2, $3::uuid, $4, $5::timestamptz, $6::text)
RETURNING id, created_at
`

type InviteLinkInsertParams struct {
	GroupID       string
	Role          string
	InvitedBy     *string
	CodeHash      string
	ExpiresAt     time.Time
	CatalogIssuer string
}

type InviteLinkInsertRow struct {
	ID        string
	CreatedAt time.Time
}

// An issuer is the system (NULL) or a usable account: a credential never
// outlives its issuer's authority.
func (q *Queries) InviteLinkInsert(ctx context.Context, arg InviteLinkInsertParams) (InviteLinkInsertRow, error) {
	row := q.db.QueryRow(ctx, inviteLinkInsert,
		arg.GroupID,
		arg.Role,
		arg.InvitedBy,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.CatalogIssuer,
	)
	var i InviteLinkInsertRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const inviteLinkRedeem = `-- name: InviteLinkRedeem :exec
UPDATE group_invite_links SET redeemed_at = now() WHERE id = $1
`

func (q *Queries) InviteLinkRedeem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, inviteLinkRedeem, id)
	return err
}

const inviteLinksRevokeInvitedBy = `-- name: InviteLinksRevokeInvitedBy :exec

UPDATE group_invite_links SET revoked_at = now()
WHERE invited_by = $1::uuid AND revoked_at IS NULL AND redeemed_at IS NULL
`

// Group invite links and account registration invites.
func (q *Queries) InviteLinksRevokeInvitedBy(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, inviteLinksRevokeInvitedBy, userID)
	return err
}
