// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type AccountDeletion struct {
	ID         string
	UserID     string
	DeletedAt  time.Time
	PurgeAt    time.Time
	State      string
	Recipients []string
	RestoredAt *time.Time
	PurgedAt   *time.Time
	// The user who deleted the account; NULL = the operator.
	DeletedBy *string
}

type AccountEvent struct {
	ID            int64
	Issuer        string
	Subject       string
	EventID       string
	Kind          string
	OccurredAt    time.Time
	ActorKind     string
	ActorID       string
	UserID        *string
	GroupID       *string
	Persona       string
	ApplicationID *string
	PreviousValue string
	CurrentValue  string
	Reason        string
	Until         *time.Time
	Attempts      int32
	RetryAt       *time.Time
}

// Enrolled 2FA factors per user (hard-deleted on removal); backup codes remain user-scoped on mfa_settings
type MfaFactor struct {
	ID           string
	UserID       string
	Method       string
	PhoneNumber  *string
	TotpSecret   []byte
	LastTotpStep *int64
	// Default factor AuthKit challenges first when 2FA is required
	IsDefault bool
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     *string
}

// Backup codes of an account with a second factor; the row goes with its last factor.
type MfaSetting struct {
	UserID string
	// Hashed backup codes for account recovery
	BackupCodes []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PermissionGroup struct {
	ID        string
	Persona   string
	CreatedAt time.Time
	// Retained inactive group state; the trusted host owns retention and purge.
	DeletedAt *time.Time
}

// Federation principals: external systems that authenticate by signing JWTs verified against configured keys.
type RemoteApplication struct {
	ID         string
	Issuer     string
	JwksUri    string
	Mode       string
	PublicKeys []byte
	Enabled    bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
	// Required controlling permission-group. Authority comes from group_remote_application_roles on it and on root.
	PermissionGroupID string
	// What changes the keys: manual (the system) | user (a credentials manager of the controlling group). Never the keypair alone.
	TrustRoot string
	// The user who supplied the keys of a group registration; NULL = the operator.
	RegisteredBy *string
	// The Token.Issuer of the app its registrar registered it through; only its role catalog judges the application's roles. NULL = every app does.
	CatalogIssuer *string
	// The Token.Issuer of the app whose Config.RemoteApplications declares it; NULL = registered through an operation.
	DeclaredBy *string
}

type SessionEvent struct {
	ID         int64
	OccurredAt time.Time
	Issuer     string
	UserID     string
	SessionID  string
	Event      string
	Method     *string
	Reason     *string
	IpAddr     *string
	UserAgent  *string
}

type User struct {
	ID            string
	Email         *string
	Username      *string
	EmailVerified bool
	// E.164 format phone number (e.g. +14155551234)
	PhoneNumber *string
	// Whether the phone number has been verified via SMS code
	PhoneVerified bool
	// When the user was banned
	BannedAt *time.Time
	// When a temporary ban expires (NULL for permanent)
	BannedUntil *time.Time
	// Reason for ban
	BanReason *string
	// User ID of admin who imposed ban
	BannedBy  *string
	DeletedAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	LastLogin *time.Time
	// User communication/auth language, e.g. en, es, de, ko, zh
	PreferredLanguage *string
	LastRenamedAt     *time.Time
	CredentialVersion int64
	// Host-written application data anyone may read
	PublicMetadata []byte
}

// Ban history: one row per ban put in force (banned) or lifted (unbanned). actor_id NULL = the system.
type UserBanEvent struct {
	ID          string
	UserID      string
	Kind        string
	OccurredAt  time.Time
	BannedUntil *time.Time
	Reason      *string
	ActorID     *string
}

// Ed25519 public keys for native clients. Revoked rows remain tombstones and cannot be re-enrolled.
type UserDeviceKey struct {
	ID          string
	UserID      string
	PublicKey   []byte
	Label       *string
	CreatedAt   time.Time
	LastUsedAt  *time.Time
	RevokedAt   *time.Time
	MfaProvenAt *time.Time
}

type UserPasskey struct {
	ID                      string
	UserID                  string
	Rpid                    string
	CredentialID            []byte
	PublicKey               []byte
	SignCount               int64
	CloneWarning            bool
	Aaguid                  []byte
	Transports              []string
	AuthenticatorAttachment string
	Flags                   []byte
	AttestationType         string
	AttestationFmt          string
	Label                   *string
	CreatedAt               time.Time
	LastUsedAt              *time.Time
}
