// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type ProfilesAccountRegistrationInvite struct {
	ID                string
	Email             string
	InvitedBy         string
	CodeHash          string
	ExpiresAt         time.Time
	RevokedAt         *time.Time
	ConsumedAt        *time.Time
	ConsumedBy        *string
	PermissionGroupID *string
	Role              *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ProfilesApiKey struct {
	ID                string
	PermissionGroupID string
	KeyID             string
	SecretHash        []byte
	Name              string
	CreatedBy         *string
	CreatedAt         time.Time
	LastUsedAt        *time.Time
	ExpiresAt         *time.Time
	RevokedAt         *time.Time
	// The single catalog/custom role this API key holds within its permission-group.
	Role string
}

type ProfilesBootstrapApply struct {
	Name      string
	AppliedAt time.Time
}

type ProfilesGroupCustomRole struct {
	PermissionGroupID string
	Role              string
	Permissions       []string
	RequiresMfa       bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ProfilesGroupInviteLink struct {
	ID                string
	PermissionGroupID string
	Role              string
	InvitedBy         string
	CodeHash          string
	RedeemedAt        *time.Time
	ExpiresAt         *time.Time
	RevokedAt         *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ProfilesGroupMembershipInvite struct {
	ID                string
	PermissionGroupID string
	UserID            string
	Role              string
	InvitedBy         string
	ExpiresAt         time.Time
	AcceptedAt        *time.Time
	DeclinedAt        *time.Time
	RevokedAt         *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Declared containment schema: the single parent persona for each permission-group persona. root is absent.
type ProfilesGroupPersonaParent struct {
	Persona       string
	ParentPersona string
	CreatedAt     time.Time
}

type ProfilesGroupRemoteApplicationRole struct {
	PermissionGroupID   string
	RemoteApplicationID string
	Role                string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           *time.Time
}

type ProfilesGroupUserRole struct {
	PermissionGroupID string
	UserID            string
	Role              string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         *time.Time
}

// Enrolled 2FA factors per user (hard-deleted on removal); backup codes remain user-scoped on mfa_settings
type ProfilesMfaFactor struct {
	ID           string
	UserID       string
	Method       string
	PhoneNumber  *string
	TotpSecret   []byte
	LastTotpStep *int64
	// Default factor AuthKit challenges first when 2FA is required
	IsDefault bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Account-level 2FA gate + backup codes per user. enabled=true ⇒ 2FA required at login. Per-factor data lives in mfa_factors.
type ProfilesMfaSetting struct {
	UserID  string
	Enabled bool
	// Hashed backup codes for account recovery
	BackupCodes []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProfilesPermissionGroup struct {
	ID       string
	Persona  string
	ParentID *string
	// Lowercase URL-safe slug identifying WHICH instance of the persona (e.g. acme-store for a merchant); the API addressing key. The group id is internal only.
	InstanceSlug *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type ProfilesRefreshSession struct {
	ID                  string
	UserID              string
	Issuer              string
	FamilyID            string
	CurrentTokenHash    []byte
	PreviousTokenHash   []byte
	CreatedAt           time.Time
	LastAuthenticatedAt *time.Time
	LastUsedAt          time.Time
	ExpiresAt           *time.Time
	RevokedAt           *time.Time
	UserAgent           *string
	IpAddr              *string
	AuthMethods         []string
}

// Federation principals: external systems that authenticate by signing JWTs verified against configured keys.
type ProfilesRemoteApplication struct {
	ID         string
	Slug       string
	Issuer     string
	JwksUri    string
	Mode       string
	PublicKeys []byte
	Enabled    bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
	// Required controlling permission-group. Authority comes from group_remote_application_roles and the parent walk.
	PermissionGroupID string
}

// Reference-mode attribute definitions: opaque JSON by remote application, key, and version.
type ProfilesRemoteApplicationAttributeDef struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type ProfilesSessionEvent struct {
	ID         int64
	OccurredAt time.Time
	Issuer     string
	UserID     string
	SessionID  string
	Event      string
	Method     *string
	Reason     *string
	IpAddr     *string
	UserAgent  *string
}

type ProfilesUser struct {
	ID            string
	Email         *string
	Username      *string
	EmailVerified bool
	// E.164 format phone number (e.g. +14155551234)
	PhoneNumber *string
	// Whether the phone number has been verified via SMS code
	PhoneVerified bool
	// When the user was banned
	BannedAt *time.Time
	// When a temporary ban expires (NULL for permanent)
	BannedUntil *time.Time
	// Reason for ban
	BanReason *string
	// User ID of admin who imposed ban
	BannedBy  *string
	DeletedAt *time.Time
	Biography *string
	// Arbitrary user metadata (internal/admin flags such as reserved)
	Metadata  []byte
	CreatedAt time.Time
	UpdatedAt time.Time
	LastLogin *time.Time
	// User communication/auth language, e.g. en, es, de, ko, zh
	PreferredLanguage *string
}

type ProfilesUserPasskey struct {
	ID                      string
	UserID                  string
	Rpid                    string
	CredentialID            []byte
	PublicKey               []byte
	SignCount               int64
	CloneWarning            bool
	Aaguid                  []byte
	Transports              []string
	AuthenticatorAttachment string
	BackupEligible          bool
	BackupState             bool
	Flags                   []byte
	AttestationType         string
	AttestationFmt          string
	Label                   *string
	CreatedAt               time.Time
	LastUsedAt              *time.Time
	DeletedAt               *time.Time
}

type ProfilesUserPasskeyHandle struct {
	UserID     string
	UserHandle []byte
	CreatedAt  time.Time
}

type ProfilesUserPassword struct {
	UserID            string
	PasswordHash      string
	HashAlgo          string
	HashParams        []byte
	PasswordUpdatedAt time.Time
}

type ProfilesUserProvider struct {
	ID              string
	UserID          string
	Issuer          string
	ProviderSlug    *string
	Subject         string
	EmailAtProvider *string
	Profile         []byte
	CreatedAt       time.Time
}

type ProfilesUserRename struct {
	ID        int64
	UserID    string
	FromSlug  string
	RenamedAt time.Time
}
