// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_invites.sql

package db

import (
	"context"
	"time"
)

const orgInviteForUpdate = `-- name: OrgInviteForUpdate :one
SELECT org_id::text, user_id::text, role, status, expires_at
FROM profiles.org_invites
WHERE id = $1::uuid AND deleted_at IS NULL
`

type OrgInviteForUpdateRow struct {
	OrgID     string
	UserID    string
	Role      string
	Status    string
	ExpiresAt *time.Time
}

func (q *Queries) OrgInviteForUpdate(ctx context.Context, id string) (OrgInviteForUpdateRow, error) {
	row := q.db.QueryRow(ctx, orgInviteForUpdate, id)
	var i OrgInviteForUpdateRow
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const orgInviteInsert = `-- name: OrgInviteInsert :one

INSERT INTO profiles.org_invites (id, org_id, user_id, invited_by, role, status, expires_at)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4::uuid, $5, 'pending', $6)
RETURNING id::text, user_id::text, invited_by::text, role, status, expires_at, acted_at, created_at
`

type OrgInviteInsertParams struct {
	ID        string
	OrgID     string
	UserID    string
	InvitedBy string
	Role      string
	ExpiresAt *time.Time
}

type OrgInviteInsertRow struct {
	ID        string
	UserID    string
	InvitedBy string
	Role      string
	Status    string
	ExpiresAt *time.Time
	ActedAt   *time.Time
	CreatedAt time.Time
}

// Org invite queries (core/service_org_invites.go).
func (q *Queries) OrgInviteInsert(ctx context.Context, arg OrgInviteInsertParams) (OrgInviteInsertRow, error) {
	row := q.db.QueryRow(ctx, orgInviteInsert,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.InvitedBy,
		arg.Role,
		arg.ExpiresAt,
	)
	var i OrgInviteInsertRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvitedBy,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
		&i.ActedAt,
		&i.CreatedAt,
	)
	return i, err
}

const orgInviteMarkExpired = `-- name: OrgInviteMarkExpired :exec
UPDATE profiles.org_invites
SET status = 'expired', acted_at = now(), updated_at = now()
WHERE id = $1::uuid
`

func (q *Queries) OrgInviteMarkExpired(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, orgInviteMarkExpired, id)
	return err
}

const orgInviteRevoke = `-- name: OrgInviteRevoke :execrows
UPDATE profiles.org_invites
SET status = 'revoked', acted_at = now(), updated_at = now()
WHERE id = $1::uuid AND org_id = $2::uuid AND status = 'pending' AND deleted_at IS NULL
`

type OrgInviteRevokeParams struct {
	ID    string
	OrgID string
}

func (q *Queries) OrgInviteRevoke(ctx context.Context, arg OrgInviteRevokeParams) (int64, error) {
	result, err := q.db.Exec(ctx, orgInviteRevoke, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const orgInviteSetStatus = `-- name: OrgInviteSetStatus :exec
UPDATE profiles.org_invites
SET status = $1, acted_at = now(), updated_at = now()
WHERE id = $2::uuid
`

type OrgInviteSetStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) OrgInviteSetStatus(ctx context.Context, arg OrgInviteSetStatusParams) error {
	_, err := q.db.Exec(ctx, orgInviteSetStatus, arg.Status, arg.ID)
	return err
}

const orgInvitesByOrg = `-- name: OrgInvitesByOrg :many
SELECT id::text, user_id::text, invited_by::text, role, status, expires_at, acted_at, created_at
FROM profiles.org_invites
WHERE org_id = $1::uuid AND deleted_at IS NULL
ORDER BY created_at DESC
`

type OrgInvitesByOrgRow struct {
	ID        string
	UserID    string
	InvitedBy string
	Role      string
	Status    string
	ExpiresAt *time.Time
	ActedAt   *time.Time
	CreatedAt time.Time
}

func (q *Queries) OrgInvitesByOrg(ctx context.Context, orgID string) ([]OrgInvitesByOrgRow, error) {
	rows, err := q.db.Query(ctx, orgInvitesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgInvitesByOrgRow
	for rows.Next() {
		var i OrgInvitesByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InvitedBy,
			&i.Role,
			&i.Status,
			&i.ExpiresAt,
			&i.ActedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgInvitesByOrgStatus = `-- name: OrgInvitesByOrgStatus :many
SELECT id::text, user_id::text, invited_by::text, role, status, expires_at, acted_at, created_at
FROM profiles.org_invites
WHERE org_id = $1::uuid AND status = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type OrgInvitesByOrgStatusParams struct {
	OrgID  string
	Status string
}

type OrgInvitesByOrgStatusRow struct {
	ID        string
	UserID    string
	InvitedBy string
	Role      string
	Status    string
	ExpiresAt *time.Time
	ActedAt   *time.Time
	CreatedAt time.Time
}

func (q *Queries) OrgInvitesByOrgStatus(ctx context.Context, arg OrgInvitesByOrgStatusParams) ([]OrgInvitesByOrgStatusRow, error) {
	rows, err := q.db.Query(ctx, orgInvitesByOrgStatus, arg.OrgID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgInvitesByOrgStatusRow
	for rows.Next() {
		var i OrgInvitesByOrgStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InvitedBy,
			&i.Role,
			&i.Status,
			&i.ExpiresAt,
			&i.ActedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgInvitesByUser = `-- name: OrgInvitesByUser :many
SELECT i.id::text AS id, o.slug, i.user_id::text AS user_id, i.invited_by::text AS invited_by, i.role, i.status, i.expires_at, i.acted_at, i.created_at
FROM profiles.org_invites i
JOIN profiles.orgs o ON o.id = i.org_id
WHERE i.user_id = $1::uuid AND i.deleted_at IS NULL AND o.deleted_at IS NULL
ORDER BY i.created_at DESC
`

type OrgInvitesByUserRow struct {
	ID        string
	Slug      string
	UserID    string
	InvitedBy string
	Role      string
	Status    string
	ExpiresAt *time.Time
	ActedAt   *time.Time
	CreatedAt time.Time
}

func (q *Queries) OrgInvitesByUser(ctx context.Context, userID string) ([]OrgInvitesByUserRow, error) {
	rows, err := q.db.Query(ctx, orgInvitesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgInvitesByUserRow
	for rows.Next() {
		var i OrgInvitesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UserID,
			&i.InvitedBy,
			&i.Role,
			&i.Status,
			&i.ExpiresAt,
			&i.ActedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgInvitesByUserStatus = `-- name: OrgInvitesByUserStatus :many
SELECT i.id::text AS id, o.slug, i.user_id::text AS user_id, i.invited_by::text AS invited_by, i.role, i.status, i.expires_at, i.acted_at, i.created_at
FROM profiles.org_invites i
JOIN profiles.orgs o ON o.id = i.org_id
WHERE i.user_id = $1::uuid AND i.status = $2 AND i.deleted_at IS NULL AND o.deleted_at IS NULL
ORDER BY i.created_at DESC
`

type OrgInvitesByUserStatusParams struct {
	UserID string
	Status string
}

type OrgInvitesByUserStatusRow struct {
	ID        string
	Slug      string
	UserID    string
	InvitedBy string
	Role      string
	Status    string
	ExpiresAt *time.Time
	ActedAt   *time.Time
	CreatedAt time.Time
}

func (q *Queries) OrgInvitesByUserStatus(ctx context.Context, arg OrgInvitesByUserStatusParams) ([]OrgInvitesByUserStatusRow, error) {
	rows, err := q.db.Query(ctx, orgInvitesByUserStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgInvitesByUserStatusRow
	for rows.Next() {
		var i OrgInvitesByUserStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UserID,
			&i.InvitedBy,
			&i.Role,
			&i.Status,
			&i.ExpiresAt,
			&i.ActedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
