// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package db

import (
	"context"
	"time"
)

const orgBySlug = `-- name: OrgBySlug :one

SELECT id::text, slug, is_personal, COALESCE(owner_user_id::text, '')::text AS owner_user_id
FROM profiles.orgs
WHERE slug = $1 AND deleted_at IS NULL
`

type OrgBySlugRow struct {
	ID          string
	Slug        string
	IsPersonal  bool
	OwnerUserID string
}

// Org + membership + role queries (core/service_orgs.go).
func (q *Queries) OrgBySlug(ctx context.Context, slug string) (OrgBySlugRow, error) {
	row := q.db.QueryRow(ctx, orgBySlug, slug)
	var i OrgBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.IsPersonal,
		&i.OwnerUserID,
	)
	return i, err
}

const orgBySlugViaRename = `-- name: OrgBySlugViaRename :one
SELECT o.id::text AS id, o.slug, o.is_personal, COALESCE(o.owner_user_id::text, '')::text AS owner_user_id
FROM profiles.org_renames r
JOIN profiles.orgs o ON o.id = r.org_id AND o.deleted_at IS NULL
WHERE r.from_slug = $1
ORDER BY r.renamed_at DESC
LIMIT 1
`

type OrgBySlugViaRenameRow struct {
	ID          string
	Slug        string
	IsPersonal  bool
	OwnerUserID string
}

// OrgBySlugViaRename resolves a historical slug (issue #58). The
// org_renames row's org_id always points at the live owner, so any
// historical slug resolves to the org currently holding it; most recent
// row wins (hard-delete + reuse).
func (q *Queries) OrgBySlugViaRename(ctx context.Context, fromSlug string) (OrgBySlugViaRenameRow, error) {
	row := q.db.QueryRow(ctx, orgBySlugViaRename, fromSlug)
	var i OrgBySlugViaRenameRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.IsPersonal,
		&i.OwnerUserID,
	)
	return i, err
}

const orgDefinedRoles = `-- name: OrgDefinedRoles :many
SELECT role
FROM profiles.org_roles
WHERE org_id = $1::uuid
ORDER BY role ASC
`

func (q *Queries) OrgDefinedRoles(ctx context.Context, orgID string) ([]string, error) {
	rows, err := q.db.Query(ctx, orgDefinedRoles, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgInsert = `-- name: OrgInsert :one
INSERT INTO profiles.orgs (id, slug, metadata)
VALUES ($1::uuid, $2, jsonb_build_object('namespace_state', 'registered_org', 'reserved', to_jsonb(false)))
RETURNING id::text, slug
`

type OrgInsertParams struct {
	ID   string
	Slug string
}

type OrgInsertRow struct {
	ID   string
	Slug string
}

func (q *Queries) OrgInsert(ctx context.Context, arg OrgInsertParams) (OrgInsertRow, error) {
	row := q.db.QueryRow(ctx, orgInsert, arg.ID, arg.Slug)
	var i OrgInsertRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const orgLastRenamedAt = `-- name: OrgLastRenamedAt :one
SELECT renamed_at
FROM   profiles.org_renames
WHERE  org_id = $1::uuid
ORDER  BY renamed_at DESC
LIMIT  1
`

func (q *Queries) OrgLastRenamedAt(ctx context.Context, orgID string) (time.Time, error) {
	row := q.db.QueryRow(ctx, orgLastRenamedAt, orgID)
	var renamed_at time.Time
	err := row.Scan(&renamed_at)
	return renamed_at, err
}

const orgMemberAdd = `-- name: OrgMemberAdd :exec
INSERT INTO profiles.org_memberships (org_id, member_id, member_kind, role)
VALUES ($1::uuid, $2::uuid, 'user', 'member')
ON CONFLICT (org_id, member_id, member_kind) DO UPDATE SET deleted_at = NULL, updated_at = now()
`

type OrgMemberAddParams struct {
	OrgID  string
	UserID string
}

// OrgMemberAdd intentionally does NOT change role on conflict (re-adding
// an existing member only revives a soft-deleted row).
func (q *Queries) OrgMemberAdd(ctx context.Context, arg OrgMemberAddParams) error {
	_, err := q.db.Exec(ctx, orgMemberAdd, arg.OrgID, arg.UserID)
	return err
}

const orgMemberHasRole = `-- name: OrgMemberHasRole :one
SELECT EXISTS (
  SELECT 1
  FROM profiles.org_memberships
  WHERE org_id = $1::uuid AND member_id = $2::uuid AND member_kind = 'user' AND role = $3 AND deleted_at IS NULL
)
`

type OrgMemberHasRoleParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) OrgMemberHasRole(ctx context.Context, arg OrgMemberHasRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, orgMemberHasRole, arg.OrgID, arg.UserID, arg.Role)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const orgMemberIDs = `-- name: OrgMemberIDs :many
SELECT member_id::text
FROM profiles.org_memberships
WHERE org_id = $1::uuid AND member_kind = 'user' AND deleted_at IS NULL
ORDER BY member_id::text ASC
`

func (q *Queries) OrgMemberIDs(ctx context.Context, orgID string) ([]string, error) {
	rows, err := q.db.Query(ctx, orgMemberIDs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var member_id string
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgMemberRole = `-- name: OrgMemberRole :one
SELECT role
FROM profiles.org_memberships
WHERE org_id = $1::uuid AND member_id = $2::uuid AND member_kind = 'user' AND deleted_at IS NULL
`

type OrgMemberRoleParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) OrgMemberRole(ctx context.Context, arg OrgMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, orgMemberRole, arg.OrgID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const orgMemberRolePrincipal = `-- name: OrgMemberRolePrincipal :one
SELECT role
FROM profiles.org_memberships
WHERE org_id = $1::uuid AND member_id = $2::uuid AND member_kind = $3 AND deleted_at IS NULL
`

type OrgMemberRolePrincipalParams struct {
	OrgID      string
	MemberID   string
	MemberKind string
}

func (q *Queries) OrgMemberRolePrincipal(ctx context.Context, arg OrgMemberRolePrincipalParams) (string, error) {
	row := q.db.QueryRow(ctx, orgMemberRolePrincipal, arg.OrgID, arg.MemberID, arg.MemberKind)
	var role string
	err := row.Scan(&role)
	return role, err
}

const orgMemberSoftDelete = `-- name: OrgMemberSoftDelete :exec
UPDATE profiles.org_memberships SET deleted_at = now(), updated_at = now()
WHERE org_id = $1::uuid AND member_id = $2::uuid AND member_kind = 'user' AND deleted_at IS NULL
`

type OrgMemberSoftDeleteParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) OrgMemberSoftDelete(ctx context.Context, arg OrgMemberSoftDeleteParams) error {
	_, err := q.db.Exec(ctx, orgMemberSoftDelete, arg.OrgID, arg.UserID)
	return err
}

const orgMemberSoftDeletePrincipal = `-- name: OrgMemberSoftDeletePrincipal :exec
UPDATE profiles.org_memberships SET deleted_at = now(), updated_at = now()
WHERE org_id = $1::uuid AND member_id = $2::uuid AND member_kind = $3 AND deleted_at IS NULL
`

type OrgMemberSoftDeletePrincipalParams struct {
	OrgID      string
	MemberID   string
	MemberKind string
}

func (q *Queries) OrgMemberSoftDeletePrincipal(ctx context.Context, arg OrgMemberSoftDeletePrincipalParams) error {
	_, err := q.db.Exec(ctx, orgMemberSoftDeletePrincipal, arg.OrgID, arg.MemberID, arg.MemberKind)
	return err
}

const orgMembershipExists = `-- name: OrgMembershipExists :one
SELECT EXISTS (
  SELECT 1 FROM profiles.org_memberships
  WHERE org_id = $1::uuid AND member_id = $2::uuid AND member_kind = 'user' AND deleted_at IS NULL
)
`

type OrgMembershipExistsParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) OrgMembershipExists(ctx context.Context, arg OrgMembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, orgMembershipExists, arg.OrgID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const orgMembershipResetRole = `-- name: OrgMembershipResetRole :exec
UPDATE profiles.org_memberships
SET role = 'member', updated_at = now()
WHERE org_id = $1::uuid AND member_id = $2::uuid AND member_kind = 'user' AND role = $3 AND deleted_at IS NULL
`

type OrgMembershipResetRoleParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) OrgMembershipResetRole(ctx context.Context, arg OrgMembershipResetRoleParams) error {
	_, err := q.db.Exec(ctx, orgMembershipResetRole, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const orgMembershipSetRole = `-- name: OrgMembershipSetRole :exec
UPDATE profiles.org_memberships
SET role = $1, updated_at = now()
WHERE org_id = $2::uuid
  AND member_id = $3::uuid
  AND member_kind = 'user'
  AND deleted_at IS NULL
  AND EXISTS (SELECT 1 FROM profiles.org_roles WHERE org_id = $2::uuid AND role = $1)
`

type OrgMembershipSetRoleParams struct {
	Role   string
	OrgID  string
	UserID string
}

func (q *Queries) OrgMembershipSetRole(ctx context.Context, arg OrgMembershipSetRoleParams) error {
	_, err := q.db.Exec(ctx, orgMembershipSetRole, arg.Role, arg.OrgID, arg.UserID)
	return err
}

const orgMembershipUpsertRole = `-- name: OrgMembershipUpsertRole :exec
INSERT INTO profiles.org_memberships (org_id, member_id, member_kind, role)
VALUES ($1::uuid, $2::uuid, 'user', $3)
ON CONFLICT (org_id, member_id, member_kind)
DO UPDATE SET role = EXCLUDED.role, deleted_at = NULL, updated_at = now()
`

type OrgMembershipUpsertRoleParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) OrgMembershipUpsertRole(ctx context.Context, arg OrgMembershipUpsertRoleParams) error {
	_, err := q.db.Exec(ctx, orgMembershipUpsertRole, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const orgMembershipUpsertRolePrincipal = `-- name: OrgMembershipUpsertRolePrincipal :exec

INSERT INTO profiles.org_memberships (org_id, member_id, member_kind, role)
VALUES ($1::uuid, $2::uuid, $3, $4)
ON CONFLICT (org_id, member_id, member_kind)
DO UPDATE SET role = EXCLUDED.role, deleted_at = NULL, updated_at = now()
`

type OrgMembershipUpsertRolePrincipalParams struct {
	OrgID      string
	MemberID   string
	MemberKind string
	Role       string
}

// Polymorphic remote_application memberships: a remote_app holds org roles
// via the SAME org_memberships/org_roles machinery as users (#74).
func (q *Queries) OrgMembershipUpsertRolePrincipal(ctx context.Context, arg OrgMembershipUpsertRolePrincipalParams) error {
	_, err := q.db.Exec(ctx, orgMembershipUpsertRolePrincipal,
		arg.OrgID,
		arg.MemberID,
		arg.MemberKind,
		arg.Role,
	)
	return err
}

const orgRenameInsert = `-- name: OrgRenameInsert :exec
INSERT INTO profiles.org_renames (org_id, from_slug)
VALUES ($1::uuid, $2)
`

type OrgRenameInsertParams struct {
	OrgID    string
	FromSlug string
}

func (q *Queries) OrgRenameInsert(ctx context.Context, arg OrgRenameInsertParams) error {
	_, err := q.db.Exec(ctx, orgRenameInsert, arg.OrgID, arg.FromSlug)
	return err
}

const orgRoleDefine = `-- name: OrgRoleDefine :exec
INSERT INTO profiles.org_roles (org_id, role)
VALUES ($1::uuid, $2)
ON CONFLICT (org_id, role) DO NOTHING
`

type OrgRoleDefineParams struct {
	OrgID string
	Role  string
}

func (q *Queries) OrgRoleDefine(ctx context.Context, arg OrgRoleDefineParams) error {
	_, err := q.db.Exec(ctx, orgRoleDefine, arg.OrgID, arg.Role)
	return err
}

const orgRoleDelete = `-- name: OrgRoleDelete :exec
DELETE FROM profiles.org_roles
WHERE org_id = $1::uuid AND role = $2
`

type OrgRoleDeleteParams struct {
	OrgID string
	Role  string
}

func (q *Queries) OrgRoleDelete(ctx context.Context, arg OrgRoleDeleteParams) error {
	_, err := q.db.Exec(ctx, orgRoleDelete, arg.OrgID, arg.Role)
	return err
}

const orgRoleExists = `-- name: OrgRoleExists :one
SELECT EXISTS(SELECT 1 FROM profiles.org_roles WHERE org_id = $1::uuid AND role = $2)
`

type OrgRoleExistsParams struct {
	OrgID string
	Role  string
}

func (q *Queries) OrgRoleExists(ctx context.Context, arg OrgRoleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, orgRoleExists, arg.OrgID, arg.Role)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const orgRoleHasPermissions = `-- name: OrgRoleHasPermissions :one
SELECT EXISTS(SELECT 1 FROM profiles.org_role_permissions WHERE org_id = $1::uuid AND role = $2)
`

type OrgRoleHasPermissionsParams struct {
	OrgID string
	Role  string
}

func (q *Queries) OrgRoleHasPermissions(ctx context.Context, arg OrgRoleHasPermissionsParams) (bool, error) {
	row := q.db.QueryRow(ctx, orgRoleHasPermissions, arg.OrgID, arg.Role)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const orgRoleMemberCount = `-- name: OrgRoleMemberCount :one
SELECT COUNT(*)
FROM profiles.org_memberships
WHERE org_id = $1::uuid AND role = $2 AND deleted_at IS NULL
`

type OrgRoleMemberCountParams struct {
	OrgID string
	Role  string
}

func (q *Queries) OrgRoleMemberCount(ctx context.Context, arg OrgRoleMemberCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, orgRoleMemberCount, arg.OrgID, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const orgRolePermissionInsert = `-- name: OrgRolePermissionInsert :exec
INSERT INTO profiles.org_role_permissions (org_id, role, permission)
VALUES ($1::uuid, $2, $3)
ON CONFLICT DO NOTHING
`

type OrgRolePermissionInsertParams struct {
	OrgID      string
	Role       string
	Permission string
}

func (q *Queries) OrgRolePermissionInsert(ctx context.Context, arg OrgRolePermissionInsertParams) error {
	_, err := q.db.Exec(ctx, orgRolePermissionInsert, arg.OrgID, arg.Role, arg.Permission)
	return err
}

const orgRolePermissions = `-- name: OrgRolePermissions :many

SELECT permission FROM profiles.org_role_permissions
WHERE org_id = $1::uuid AND role = $2
ORDER BY permission ASC
`

type OrgRolePermissionsParams struct {
	OrgID string
	Role  string
}

// Org RBAC role-permission queries (core/org_role_permissions.go).
func (q *Queries) OrgRolePermissions(ctx context.Context, arg OrgRolePermissionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, orgRolePermissions, arg.OrgID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgRolePermissionsDelete = `-- name: OrgRolePermissionsDelete :exec
DELETE FROM profiles.org_role_permissions
WHERE org_id = $1::uuid AND role = $2
`

type OrgRolePermissionsDeleteParams struct {
	OrgID string
	Role  string
}

func (q *Queries) OrgRolePermissionsDelete(ctx context.Context, arg OrgRolePermissionsDeleteParams) error {
	_, err := q.db.Exec(ctx, orgRolePermissionsDelete, arg.OrgID, arg.Role)
	return err
}

const orgRolesForPrincipal = `-- name: OrgRolesForPrincipal :many
SELECT o.slug, m.role
FROM profiles.org_memberships m
JOIN profiles.orgs o ON o.id = m.org_id AND o.deleted_at IS NULL
WHERE m.member_id = $1::uuid AND m.member_kind = $2 AND m.deleted_at IS NULL
ORDER BY o.slug ASC, m.role ASC
`

type OrgRolesForPrincipalParams struct {
	MemberID   string
	MemberKind string
}

type OrgRolesForPrincipalRow struct {
	Slug string
	Role string
}

func (q *Queries) OrgRolesForPrincipal(ctx context.Context, arg OrgRolesForPrincipalParams) ([]OrgRolesForPrincipalRow, error) {
	rows, err := q.db.Query(ctx, orgRolesForPrincipal, arg.MemberID, arg.MemberKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgRolesForPrincipalRow
	for rows.Next() {
		var i OrgRolesForPrincipalRow
		if err := rows.Scan(&i.Slug, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgRolesSeedOwnerMember = `-- name: OrgRolesSeedOwnerMember :exec
INSERT INTO profiles.org_roles (org_id, role)
VALUES ($1::uuid, $2), ($1::uuid, $3)
ON CONFLICT (org_id, role) DO NOTHING
`

type OrgRolesSeedOwnerMemberParams struct {
	OrgID      string
	OwnerRole  string
	MemberRole string
}

func (q *Queries) OrgRolesSeedOwnerMember(ctx context.Context, arg OrgRolesSeedOwnerMemberParams) error {
	_, err := q.db.Exec(ctx, orgRolesSeedOwnerMember, arg.OrgID, arg.OwnerRole, arg.MemberRole)
	return err
}

const orgSlugAndPersonalByID = `-- name: OrgSlugAndPersonalByID :one
SELECT slug, is_personal FROM profiles.orgs
WHERE id = $1::uuid AND deleted_at IS NULL
`

type OrgSlugAndPersonalByIDRow struct {
	Slug       string
	IsPersonal bool
}

func (q *Queries) OrgSlugAndPersonalByID(ctx context.Context, id string) (OrgSlugAndPersonalByIDRow, error) {
	row := q.db.QueryRow(ctx, orgSlugAndPersonalByID, id)
	var i OrgSlugAndPersonalByIDRow
	err := row.Scan(&i.Slug, &i.IsPersonal)
	return i, err
}

const orgSlugsByUser = `-- name: OrgSlugsByUser :many
SELECT o.slug
FROM profiles.org_memberships m
JOIN profiles.orgs o ON o.id = m.org_id
WHERE m.member_id = $1::uuid AND m.member_kind = 'user' AND m.deleted_at IS NULL AND o.deleted_at IS NULL
ORDER BY o.slug ASC
`

func (q *Queries) OrgSlugsByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, orgSlugsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgUpdateSlug = `-- name: OrgUpdateSlug :exec
UPDATE profiles.orgs SET slug = $1, updated_at = now()
WHERE id = $2::uuid AND deleted_at IS NULL
`

type OrgUpdateSlugParams struct {
	Slug string
	ID   string
}

func (q *Queries) OrgUpdateSlug(ctx context.Context, arg OrgUpdateSlugParams) error {
	_, err := q.db.Exec(ctx, orgUpdateSlug, arg.Slug, arg.ID)
	return err
}

const remoteAppAttributeDefDelete = `-- name: RemoteAppAttributeDefDelete :execrows
DELETE FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid AND key = $2
`

type RemoteAppAttributeDefDeleteParams struct {
	RemoteApplicationID string
	Key                 string
}

func (q *Queries) RemoteAppAttributeDefDelete(ctx context.Context, arg RemoteAppAttributeDefDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, remoteAppAttributeDefDelete, arg.RemoteApplicationID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const remoteAppAttributeDefGet = `-- name: RemoteAppAttributeDefGet :one
SELECT remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid AND key = $2 AND version = $3
`

type RemoteAppAttributeDefGetParams struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
}

type RemoteAppAttributeDefGetRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RemoteAppAttributeDefGet(ctx context.Context, arg RemoteAppAttributeDefGetParams) (RemoteAppAttributeDefGetRow, error) {
	row := q.db.QueryRow(ctx, remoteAppAttributeDefGet, arg.RemoteApplicationID, arg.Key, arg.Version)
	var i RemoteAppAttributeDefGetRow
	err := row.Scan(
		&i.RemoteApplicationID,
		&i.Key,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteAppAttributeDefGetLatest = `-- name: RemoteAppAttributeDefGetLatest :one
SELECT remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid AND key = $2
ORDER BY version DESC
LIMIT 1
`

type RemoteAppAttributeDefGetLatestParams struct {
	RemoteApplicationID string
	Key                 string
}

type RemoteAppAttributeDefGetLatestRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RemoteAppAttributeDefGetLatest(ctx context.Context, arg RemoteAppAttributeDefGetLatestParams) (RemoteAppAttributeDefGetLatestRow, error) {
	row := q.db.QueryRow(ctx, remoteAppAttributeDefGetLatest, arg.RemoteApplicationID, arg.Key)
	var i RemoteAppAttributeDefGetLatestRow
	err := row.Scan(
		&i.RemoteApplicationID,
		&i.Key,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteAppAttributeDefUpsert = `-- name: RemoteAppAttributeDefUpsert :one

INSERT INTO profiles.remote_application_attribute_defs (remote_application_id, key, version, definition)
VALUES ($1::uuid, $2, $3, $4)
ON CONFLICT (remote_application_id, key, version) DO UPDATE
  SET definition = EXCLUDED.definition, updated_at = now()
RETURNING remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
`

type RemoteAppAttributeDefUpsertParams struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
}

type RemoteAppAttributeDefUpsertRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// Attribute definition registry (#75): REFERENCE-mode opaque definitions.
func (q *Queries) RemoteAppAttributeDefUpsert(ctx context.Context, arg RemoteAppAttributeDefUpsertParams) (RemoteAppAttributeDefUpsertRow, error) {
	row := q.db.QueryRow(ctx, remoteAppAttributeDefUpsert,
		arg.RemoteApplicationID,
		arg.Key,
		arg.Version,
		arg.Definition,
	)
	var i RemoteAppAttributeDefUpsertRow
	err := row.Scan(
		&i.RemoteApplicationID,
		&i.Key,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteAppAttributeDefsList = `-- name: RemoteAppAttributeDefsList :many
SELECT remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid
ORDER BY key ASC, version DESC
`

type RemoteAppAttributeDefsListRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RemoteAppAttributeDefsList(ctx context.Context, remoteApplicationID string) ([]RemoteAppAttributeDefsListRow, error) {
	rows, err := q.db.Query(ctx, remoteAppAttributeDefsList, remoteApplicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteAppAttributeDefsListRow
	for rows.Next() {
		var i RemoteAppAttributeDefsListRow
		if err := rows.Scan(
			&i.RemoteApplicationID,
			&i.Key,
			&i.Version,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const remoteApplicationByIssuer = `-- name: RemoteApplicationByIssuer :one
SELECT id::text, slug, COALESCE(org_id::text, '')::text AS org_id, issuer, jwks_uri, mode, public_keys, audiences, allowed_origins, enabled, created_at, updated_at
FROM profiles.remote_applications
WHERE issuer = $1 AND deleted_at IS NULL
`

type RemoteApplicationByIssuerRow struct {
	ID             string
	Slug           string
	OrgID          string
	Issuer         string
	JwksUri        string
	Mode           string
	PublicKeys     []byte
	Audiences      []string
	AllowedOrigins []string
	Enabled        bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) RemoteApplicationByIssuer(ctx context.Context, issuer string) (RemoteApplicationByIssuerRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationByIssuer, issuer)
	var i RemoteApplicationByIssuerRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OrgID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Audiences,
		&i.AllowedOrigins,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationBySlug = `-- name: RemoteApplicationBySlug :one
SELECT id::text, slug, COALESCE(org_id::text, '')::text AS org_id, issuer, jwks_uri, mode, public_keys, audiences, allowed_origins, enabled, created_at, updated_at
FROM profiles.remote_applications
WHERE slug = $1 AND deleted_at IS NULL
`

type RemoteApplicationBySlugRow struct {
	ID             string
	Slug           string
	OrgID          string
	Issuer         string
	JwksUri        string
	Mode           string
	PublicKeys     []byte
	Audiences      []string
	AllowedOrigins []string
	Enabled        bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) RemoteApplicationBySlug(ctx context.Context, slug string) (RemoteApplicationBySlugRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationBySlug, slug)
	var i RemoteApplicationBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OrgID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Audiences,
		&i.AllowedOrigins,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationDelete = `-- name: RemoteApplicationDelete :execrows
DELETE FROM profiles.remote_applications WHERE issuer = $1
`

func (q *Queries) RemoteApplicationDelete(ctx context.Context, issuer string) (int64, error) {
	result, err := q.db.Exec(ctx, remoteApplicationDelete, issuer)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const remoteApplicationUpsert = `-- name: RemoteApplicationUpsert :one

INSERT INTO profiles.remote_applications (slug, org_id, issuer, jwks_uri, mode, public_keys, audiences, allowed_origins, enabled)
VALUES ($1, $2::uuid, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (issuer) DO UPDATE
  SET slug          = EXCLUDED.slug,
      org_id     = EXCLUDED.org_id,
      jwks_uri      = EXCLUDED.jwks_uri,
      mode          = EXCLUDED.mode,
      public_keys   = EXCLUDED.public_keys,
      audiences     = EXCLUDED.audiences,
      allowed_origins = EXCLUDED.allowed_origins,
      enabled       = EXCLUDED.enabled,
      updated_at    = now()
RETURNING id::text, slug, COALESCE(org_id::text, '')::text AS org_id, issuer, jwks_uri, mode, public_keys, audiences, allowed_origins, enabled, created_at, updated_at
`

type RemoteApplicationUpsertParams struct {
	Slug           string
	OrgID          *string
	Issuer         string
	JwksUri        string
	Mode           string
	PublicKeys     []byte
	Audiences      []string
	AllowedOrigins []string
	Enabled        bool
}

type RemoteApplicationUpsertRow struct {
	ID             string
	Slug           string
	OrgID          string
	Issuer         string
	JwksUri        string
	Mode           string
	PublicKeys     []byte
	Audiences      []string
	AllowedOrigins []string
	Enabled        bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Remote application registry (core/service_remote_applications.go). A
// remote_application is the federation PRINCIPAL: it authenticates by signing
// JWTs verified against its JWKS/public keys (#74).
func (q *Queries) RemoteApplicationUpsert(ctx context.Context, arg RemoteApplicationUpsertParams) (RemoteApplicationUpsertRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationUpsert,
		arg.Slug,
		arg.OrgID,
		arg.Issuer,
		arg.JwksUri,
		arg.Mode,
		arg.PublicKeys,
		arg.Audiences,
		arg.AllowedOrigins,
		arg.Enabled,
	)
	var i RemoteApplicationUpsertRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OrgID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Audiences,
		&i.AllowedOrigins,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationsAll = `-- name: RemoteApplicationsAll :many
SELECT id::text, slug, COALESCE(org_id::text, '')::text AS org_id, issuer, jwks_uri, mode, public_keys, audiences, allowed_origins, enabled, created_at, updated_at
FROM profiles.remote_applications
WHERE deleted_at IS NULL
ORDER BY slug ASC
`

type RemoteApplicationsAllRow struct {
	ID             string
	Slug           string
	OrgID          string
	Issuer         string
	JwksUri        string
	Mode           string
	PublicKeys     []byte
	Audiences      []string
	AllowedOrigins []string
	Enabled        bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) RemoteApplicationsAll(ctx context.Context) ([]RemoteApplicationsAllRow, error) {
	rows, err := q.db.Query(ctx, remoteApplicationsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteApplicationsAllRow
	for rows.Next() {
		var i RemoteApplicationsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OrgID,
			&i.Issuer,
			&i.JwksUri,
			&i.Mode,
			&i.PublicKeys,
			&i.Audiences,
			&i.AllowedOrigins,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const remoteApplicationsEnabled = `-- name: RemoteApplicationsEnabled :many
SELECT id::text, slug, COALESCE(org_id::text, '')::text AS org_id, issuer, jwks_uri, mode, public_keys, audiences, allowed_origins, enabled, created_at, updated_at
FROM profiles.remote_applications
WHERE enabled = true AND deleted_at IS NULL
ORDER BY slug ASC
`

type RemoteApplicationsEnabledRow struct {
	ID             string
	Slug           string
	OrgID          string
	Issuer         string
	JwksUri        string
	Mode           string
	PublicKeys     []byte
	Audiences      []string
	AllowedOrigins []string
	Enabled        bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) RemoteApplicationsEnabled(ctx context.Context) ([]RemoteApplicationsEnabledRow, error) {
	rows, err := q.db.Query(ctx, remoteApplicationsEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteApplicationsEnabledRow
	for rows.Next() {
		var i RemoteApplicationsEnabledRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OrgID,
			&i.Issuer,
			&i.JwksUri,
			&i.Mode,
			&i.PublicKeys,
			&i.Audiences,
			&i.AllowedOrigins,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
