// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owner_namespace.sql

package db

import (
	"context"
)

const ownerReservedNameDelete = `-- name: OwnerReservedNameDelete :execrows
DELETE FROM profiles.owner_reserved_names WHERE slug = $1
`

func (q *Queries) OwnerReservedNameDelete(ctx context.Context, slug string) (int64, error) {
	result, err := q.db.Exec(ctx, ownerReservedNameDelete, slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ownerReservedNameExists = `-- name: OwnerReservedNameExists :one

SELECT EXISTS(
  SELECT 1 FROM profiles.owner_reserved_names WHERE slug = $1
)
`

// Owner-namespace queries (core/service_owner_namespace*.go, core/owner_namespace_lookup.go).
//
// Permission groups own group-scoped routing now. Only the user/owner-reserved
// name namespace queries remain here.
func (q *Queries) OwnerReservedNameExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, ownerReservedNameExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ownerReservedNameUpsert = `-- name: OwnerReservedNameUpsert :exec
INSERT INTO profiles.owner_reserved_names (slug)
VALUES ($1)
ON CONFLICT (slug) DO UPDATE SET updated_at = now()
`

func (q *Queries) OwnerReservedNameUpsert(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, ownerReservedNameUpsert, slug)
	return err
}

const userBySlug = `-- name: UserBySlug :one
SELECT id::text, username::text
FROM profiles.users
WHERE username = $1 AND deleted_at IS NULL
`

type UserBySlugRow struct {
	ID       string
	Username string
}

func (q *Queries) UserBySlug(ctx context.Context, username *string) (UserBySlugRow, error) {
	row := q.db.QueryRow(ctx, userBySlug, username)
	var i UserBySlugRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const userIsReserved = `-- name: UserIsReserved :one
SELECT (CASE
  WHEN jsonb_typeof(COALESCE(metadata, '{}'::jsonb)->'reserved')='boolean'
  THEN (COALESCE(metadata, '{}'::jsonb)->>'reserved')::boolean
  ELSE false
END)::boolean AS reserved
FROM profiles.users
WHERE id = $1::uuid
`

func (q *Queries) UserIsReserved(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, userIsReserved, id)
	var reserved bool
	err := row.Scan(&reserved)
	return reserved, err
}

const userSlugAliases = `-- name: UserSlugAliases :many
SELECT DISTINCT from_slug
FROM profiles.user_renames
WHERE user_id = $1::uuid
ORDER BY from_slug ASC
`

func (q *Queries) UserSlugAliases(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, userSlugAliases, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var from_slug string
		if err := rows.Scan(&from_slug); err != nil {
			return nil, err
		}
		items = append(items, from_slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
