// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkeys.sql

package db

import (
	"context"
)

const passkeysDeleteByUser = `-- name: PasskeysDeleteByUser :exec

UPDATE user_passkeys SET deleted_at = now() WHERE user_id = $1::uuid AND deleted_at IS NULL
`

// Passkey queries.
func (q *Queries) PasskeysDeleteByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, passkeysDeleteByUser, userID)
	return err
}
