// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limits.sql

package db

import (
	"context"
)

const rateLimitSpend = `-- name: RateLimitSpend :one
WITH p AS (
  SELECT floor(extract(epoch FROM clock_timestamp()) * 1000)::bigint AS now_ms,
    $2::bigint AS window_ms,
    $3::bigint AS max_hits,
    $4::bigint AS cooldown_ms
)
INSERT INTO rate_limits AS r (key, hits, expires_at)
SELECT $1::text, ARRAY[p.now_ms],
  'epoch'::timestamptz + (p.now_ms + p.window_ms) * interval '1 millisecond'
FROM p
ON CONFLICT (key) DO UPDATE SET (hits, expires_at) = (
  SELECT
    CASE WHEN d.admit THEN l.live || p.now_ms ELSE l.live END,
    CASE WHEN d.admit THEN EXCLUDED.expires_at ELSE r.expires_at END
  FROM p,
    LATERAL (SELECT ARRAY(
      SELECT h FROM unnest(r.hits) AS h WHERE h > p.now_ms - p.window_ms ORDER BY h
    ) AS live) l,
    LATERAL (SELECT cardinality(l.live) < p.max_hits
      AND (p.cooldown_ms = 0 OR cardinality(l.live) = 0
        OR l.live[cardinality(l.live)] + p.cooldown_ms <= p.now_ms) AS admit) d
)
RETURNING (SELECT now_ms FROM p) AS now_ms, old.hits AS before, new.hits AS after
`

type RateLimitSpendParams struct {
	Key        string
	WindowMs   int64
	MaxHits    int64
	CooldownMs int64
}

type RateLimitSpendRow struct {
	NowMs  *int64
	Before []int64
	After  []int64
}

// Spends one request of key's sliding-window budget in one statement on the
// database clock, so concurrent callers on every replica decide in turn. A
// hit lapses window_ms after it; a request is admitted while fewer than
// max_hits are live and the newest is at least cooldown_ms old, and a refusal
// records nothing. before is the row the decision read (NULL for a new key).
func (q *Queries) RateLimitSpend(ctx context.Context, arg RateLimitSpendParams) (RateLimitSpendRow, error) {
	row := q.db.QueryRow(ctx, rateLimitSpend,
		arg.Key,
		arg.WindowMs,
		arg.MaxHits,
		arg.CooldownMs,
	)
	var i RateLimitSpendRow
	err := row.Scan(&i.NowMs, &i.Before, &i.After)
	return i, err
}

const rateLimitsDeleteExpired = `-- name: RateLimitsDeleteExpired :execrows
DELETE FROM rate_limits
WHERE key IN (
  SELECT l.key FROM rate_limits l
  WHERE l.expires_at <= now()
  ORDER BY l.expires_at LIMIT $1 FOR UPDATE SKIP LOCKED
) AND expires_at <= now()
`

func (q *Queries) RateLimitsDeleteExpired(ctx context.Context, batchSize int64) (int64, error) {
	result, err := q.db.Exec(ctx, rateLimitsDeleteExpired, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
