// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remote_applications.sql

package db

import (
	"context"
	"time"
)

const remoteAppAttributeDefDelete = `-- name: RemoteAppAttributeDefDelete :execrows
DELETE FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid AND key = $2
`

type RemoteAppAttributeDefDeleteParams struct {
	RemoteApplicationID string
	Key                 string
}

func (q *Queries) RemoteAppAttributeDefDelete(ctx context.Context, arg RemoteAppAttributeDefDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, remoteAppAttributeDefDelete, arg.RemoteApplicationID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const remoteAppAttributeDefGet = `-- name: RemoteAppAttributeDefGet :one
SELECT remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid AND key = $2 AND version = $3
`

type RemoteAppAttributeDefGetParams struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
}

type RemoteAppAttributeDefGetRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RemoteAppAttributeDefGet(ctx context.Context, arg RemoteAppAttributeDefGetParams) (RemoteAppAttributeDefGetRow, error) {
	row := q.db.QueryRow(ctx, remoteAppAttributeDefGet, arg.RemoteApplicationID, arg.Key, arg.Version)
	var i RemoteAppAttributeDefGetRow
	err := row.Scan(
		&i.RemoteApplicationID,
		&i.Key,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteAppAttributeDefGetLatest = `-- name: RemoteAppAttributeDefGetLatest :one
SELECT remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid AND key = $2
ORDER BY version DESC
LIMIT 1
`

type RemoteAppAttributeDefGetLatestParams struct {
	RemoteApplicationID string
	Key                 string
}

type RemoteAppAttributeDefGetLatestRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RemoteAppAttributeDefGetLatest(ctx context.Context, arg RemoteAppAttributeDefGetLatestParams) (RemoteAppAttributeDefGetLatestRow, error) {
	row := q.db.QueryRow(ctx, remoteAppAttributeDefGetLatest, arg.RemoteApplicationID, arg.Key)
	var i RemoteAppAttributeDefGetLatestRow
	err := row.Scan(
		&i.RemoteApplicationID,
		&i.Key,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteAppAttributeDefUpsert = `-- name: RemoteAppAttributeDefUpsert :one

INSERT INTO profiles.remote_application_attribute_defs (remote_application_id, key, version, definition)
VALUES ($1::uuid, $2, $3, $4)
ON CONFLICT (remote_application_id, key, version) DO UPDATE
  SET definition = EXCLUDED.definition, updated_at = now()
RETURNING remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
`

type RemoteAppAttributeDefUpsertParams struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
}

type RemoteAppAttributeDefUpsertRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// Attribute definition registry (#75): REFERENCE-mode opaque definitions.
func (q *Queries) RemoteAppAttributeDefUpsert(ctx context.Context, arg RemoteAppAttributeDefUpsertParams) (RemoteAppAttributeDefUpsertRow, error) {
	row := q.db.QueryRow(ctx, remoteAppAttributeDefUpsert,
		arg.RemoteApplicationID,
		arg.Key,
		arg.Version,
		arg.Definition,
	)
	var i RemoteAppAttributeDefUpsertRow
	err := row.Scan(
		&i.RemoteApplicationID,
		&i.Key,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteAppAttributeDefsList = `-- name: RemoteAppAttributeDefsList :many
SELECT remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid
ORDER BY key ASC, version DESC
`

type RemoteAppAttributeDefsListRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RemoteAppAttributeDefsList(ctx context.Context, remoteApplicationID string) ([]RemoteAppAttributeDefsListRow, error) {
	rows, err := q.db.Query(ctx, remoteAppAttributeDefsList, remoteApplicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteAppAttributeDefsListRow
	for rows.Next() {
		var i RemoteAppAttributeDefsListRow
		if err := rows.Scan(
			&i.RemoteApplicationID,
			&i.Key,
			&i.Version,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const remoteApplicationByIssuer = `-- name: RemoteApplicationByIssuer :one
SELECT id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at, created_at, updated_at
FROM profiles.remote_applications
WHERE issuer = $1
`

type RemoteApplicationByIssuerRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	DisplayName       string
	Tier              string
	TrustRoot         string
	DocumentEndpoint  string
	RootVerifiedAt    *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) RemoteApplicationByIssuer(ctx context.Context, issuer string) (RemoteApplicationByIssuerRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationByIssuer, issuer)
	var i RemoteApplicationByIssuerRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.DisplayName,
		&i.Tier,
		&i.TrustRoot,
		&i.DocumentEndpoint,
		&i.RootVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationBySlug = `-- name: RemoteApplicationBySlug :one
SELECT id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at, created_at, updated_at
FROM profiles.remote_applications
WHERE slug = $1
`

type RemoteApplicationBySlugRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	DisplayName       string
	Tier              string
	TrustRoot         string
	DocumentEndpoint  string
	RootVerifiedAt    *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) RemoteApplicationBySlug(ctx context.Context, slug string) (RemoteApplicationBySlugRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationBySlug, slug)
	var i RemoteApplicationBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.DisplayName,
		&i.Tier,
		&i.TrustRoot,
		&i.DocumentEndpoint,
		&i.RootVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationBySlugForUpdate = `-- name: RemoteApplicationBySlugForUpdate :one

SELECT id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at, created_at, updated_at
FROM profiles.remote_applications
WHERE slug = $1
FOR UPDATE
`

type RemoteApplicationBySlugForUpdateRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	DisplayName       string
	Tier              string
	TrustRoot         string
	DocumentEndpoint  string
	RootVerifiedAt    *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Application self-registration (#264). Domain-rooted rows are keyed by slug
// (= the proven domain); the uuid stays stable across every refresh/rotation.
func (q *Queries) RemoteApplicationBySlugForUpdate(ctx context.Context, slug string) (RemoteApplicationBySlugForUpdateRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationBySlugForUpdate, slug)
	var i RemoteApplicationBySlugForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.DisplayName,
		&i.Tier,
		&i.TrustRoot,
		&i.DocumentEndpoint,
		&i.RootVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationDelete = `-- name: RemoteApplicationDelete :execrows
DELETE FROM profiles.remote_applications WHERE issuer = $1
`

func (q *Queries) RemoteApplicationDelete(ctx context.Context, issuer string) (int64, error) {
	result, err := q.db.Exec(ctx, remoteApplicationDelete, issuer)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const remoteApplicationDomainInsert = `-- name: RemoteApplicationDomainInsert :one
INSERT INTO profiles.remote_applications (slug, permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at)
VALUES ($1, $2::uuid, $3, $4, $5, $6, true, $7, 'registered', 'domain', $8, now())
RETURNING id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at, created_at, updated_at
`

type RemoteApplicationDomainInsertParams struct {
	Slug              string
	PermissionGroupID *string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	DisplayName       string
	DocumentEndpoint  string
}

type RemoteApplicationDomainInsertRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	DisplayName       string
	Tier              string
	TrustRoot         string
	DocumentEndpoint  string
	RootVerifiedAt    *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) RemoteApplicationDomainInsert(ctx context.Context, arg RemoteApplicationDomainInsertParams) (RemoteApplicationDomainInsertRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationDomainInsert,
		arg.Slug,
		arg.PermissionGroupID,
		arg.Issuer,
		arg.JwksUri,
		arg.Mode,
		arg.PublicKeys,
		arg.DisplayName,
		arg.DocumentEndpoint,
	)
	var i RemoteApplicationDomainInsertRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.DisplayName,
		&i.Tier,
		&i.TrustRoot,
		&i.DocumentEndpoint,
		&i.RootVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationDomainRefresh = `-- name: RemoteApplicationDomainRefresh :one
UPDATE profiles.remote_applications
SET issuer            = $1,
    jwks_uri          = $2,
    mode              = $3,
    public_keys       = $4,
    display_name      = $5,
    document_endpoint = $6,
    enabled           = true,
    root_verified_at  = now(),
    updated_at        = now()
WHERE slug = $7 AND trust_root = 'domain'
RETURNING id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at, created_at, updated_at
`

type RemoteApplicationDomainRefreshParams struct {
	Issuer           string
	JwksUri          string
	Mode             string
	PublicKeys       []byte
	DisplayName      string
	DocumentEndpoint string
	Slug             string
}

type RemoteApplicationDomainRefreshRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	DisplayName       string
	Tier              string
	TrustRoot         string
	DocumentEndpoint  string
	RootVerifiedAt    *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Idempotent re-registration: the re-fetched document is the trust-root proof,
// so it refreshes issuer/keys/config, re-proves the root, and re-enables a
// sweeper-disabled row. Tier is untouched (approval is an admin act).
func (q *Queries) RemoteApplicationDomainRefresh(ctx context.Context, arg RemoteApplicationDomainRefreshParams) (RemoteApplicationDomainRefreshRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationDomainRefresh,
		arg.Issuer,
		arg.JwksUri,
		arg.Mode,
		arg.PublicKeys,
		arg.DisplayName,
		arg.DocumentEndpoint,
		arg.Slug,
	)
	var i RemoteApplicationDomainRefreshRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.DisplayName,
		&i.Tier,
		&i.TrustRoot,
		&i.DocumentEndpoint,
		&i.RootVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationRepoint = `-- name: RemoteApplicationRepoint :one
UPDATE profiles.remote_applications
SET slug              = $1,
    issuer            = $2,
    jwks_uri          = $3,
    mode              = $4,
    public_keys       = $5,
    display_name      = $6,
    document_endpoint = $7,
    enabled           = true,
    root_verified_at  = now(),
    updated_at        = now()
WHERE slug = $8 AND trust_root = 'domain'
RETURNING id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at, created_at, updated_at
`

type RemoteApplicationRepointParams struct {
	NewSlug          string
	Issuer           string
	JwksUri          string
	Mode             string
	PublicKeys       []byte
	DisplayName      string
	DocumentEndpoint string
	Slug             string
}

type RemoteApplicationRepointRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	DisplayName       string
	Tier              string
	TrustRoot         string
	DocumentEndpoint  string
	RootVerifiedAt    *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Application.json re-point: the app moved domains. Signed request + a fresh
// fetch of the NEW domain's document both verified by the caller. uuid (and
// controlling group) are stable; the slug becomes the new domain.
func (q *Queries) RemoteApplicationRepoint(ctx context.Context, arg RemoteApplicationRepointParams) (RemoteApplicationRepointRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationRepoint,
		arg.NewSlug,
		arg.Issuer,
		arg.JwksUri,
		arg.Mode,
		arg.PublicKeys,
		arg.DisplayName,
		arg.DocumentEndpoint,
		arg.Slug,
	)
	var i RemoteApplicationRepointRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.DisplayName,
		&i.Tier,
		&i.TrustRoot,
		&i.DocumentEndpoint,
		&i.RootVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationRotateTrustSource = `-- name: RemoteApplicationRotateTrustSource :one
UPDATE profiles.remote_applications
SET jwks_uri    = $1,
    mode        = $2,
    public_keys = $3,
    updated_at  = now()
WHERE slug = $4
RETURNING id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at, created_at, updated_at
`

type RemoteApplicationRotateTrustSourceParams struct {
	JwksUri    string
	Mode       string
	PublicKeys []byte
	Slug       string
}

type RemoteApplicationRotateTrustSourceRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	DisplayName       string
	Tier              string
	TrustRoot         string
	DocumentEndpoint  string
	RootVerifiedAt    *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Old-key-signs-new convenience rotation (the trust root remains the ONLY
// mandatory rotation path). Does NOT touch root_verified_at.
func (q *Queries) RemoteApplicationRotateTrustSource(ctx context.Context, arg RemoteApplicationRotateTrustSourceParams) (RemoteApplicationRotateTrustSourceRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationRotateTrustSource,
		arg.JwksUri,
		arg.Mode,
		arg.PublicKeys,
		arg.Slug,
	)
	var i RemoteApplicationRotateTrustSourceRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.DisplayName,
		&i.Tier,
		&i.TrustRoot,
		&i.DocumentEndpoint,
		&i.RootVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationSetEnabled = `-- name: RemoteApplicationSetEnabled :one
UPDATE profiles.remote_applications
SET enabled = $1, updated_at = now()
WHERE slug = $2
RETURNING id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at, created_at, updated_at
`

type RemoteApplicationSetEnabledParams struct {
	Enabled bool
	Slug    string
}

type RemoteApplicationSetEnabledRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	DisplayName       string
	Tier              string
	TrustRoot         string
	DocumentEndpoint  string
	RootVerifiedAt    *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Host-sweeper primitive (#264 ruling 5: re-verification cadence is host
// policy). Re-registration (fresh domain proof) also re-enables.
func (q *Queries) RemoteApplicationSetEnabled(ctx context.Context, arg RemoteApplicationSetEnabledParams) (RemoteApplicationSetEnabledRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationSetEnabled, arg.Enabled, arg.Slug)
	var i RemoteApplicationSetEnabledRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.DisplayName,
		&i.Tier,
		&i.TrustRoot,
		&i.DocumentEndpoint,
		&i.RootVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationSetTier = `-- name: RemoteApplicationSetTier :one
UPDATE profiles.remote_applications
SET tier = $1, updated_at = now()
WHERE slug = $2
RETURNING id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at, created_at, updated_at
`

type RemoteApplicationSetTierParams struct {
	Tier string
	Slug string
}

type RemoteApplicationSetTierRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	DisplayName       string
	Tier              string
	TrustRoot         string
	DocumentEndpoint  string
	RootVerifiedAt    *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) RemoteApplicationSetTier(ctx context.Context, arg RemoteApplicationSetTierParams) (RemoteApplicationSetTierRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationSetTier, arg.Tier, arg.Slug)
	var i RemoteApplicationSetTierRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.DisplayName,
		&i.Tier,
		&i.TrustRoot,
		&i.DocumentEndpoint,
		&i.RootVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationUpsert = `-- name: RemoteApplicationUpsert :one

INSERT INTO profiles.remote_applications (slug, permission_group_id, issuer, jwks_uri, mode, public_keys, enabled)
VALUES ($1, $2::uuid, $3, $4, $5, $6, $7)
ON CONFLICT (issuer) DO UPDATE
  SET slug          = EXCLUDED.slug,
      permission_group_id = EXCLUDED.permission_group_id,
      jwks_uri      = EXCLUDED.jwks_uri,
      mode          = EXCLUDED.mode,
      public_keys   = EXCLUDED.public_keys,
      enabled       = EXCLUDED.enabled,
      updated_at    = now()
RETURNING id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at, created_at, updated_at
`

type RemoteApplicationUpsertParams struct {
	Slug              string
	PermissionGroupID *string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
}

type RemoteApplicationUpsertRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	DisplayName       string
	Tier              string
	TrustRoot         string
	DocumentEndpoint  string
	RootVerifiedAt    *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Remote application registry (core/service_remote_applications.go). A
// remote_application is the federation PRINCIPAL: it authenticates by signing
// JWTs verified against its JWKS/public keys (#74).
//
// The controlling group is addressed as permission_group_id throughout.
func (q *Queries) RemoteApplicationUpsert(ctx context.Context, arg RemoteApplicationUpsertParams) (RemoteApplicationUpsertRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationUpsert,
		arg.Slug,
		arg.PermissionGroupID,
		arg.Issuer,
		arg.JwksUri,
		arg.Mode,
		arg.PublicKeys,
		arg.Enabled,
	)
	var i RemoteApplicationUpsertRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.DisplayName,
		&i.Tier,
		&i.TrustRoot,
		&i.DocumentEndpoint,
		&i.RootVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationsAll = `-- name: RemoteApplicationsAll :many
SELECT id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at, created_at, updated_at
FROM profiles.remote_applications
ORDER BY slug ASC
`

type RemoteApplicationsAllRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	DisplayName       string
	Tier              string
	TrustRoot         string
	DocumentEndpoint  string
	RootVerifiedAt    *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) RemoteApplicationsAll(ctx context.Context) ([]RemoteApplicationsAllRow, error) {
	rows, err := q.db.Query(ctx, remoteApplicationsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteApplicationsAllRow
	for rows.Next() {
		var i RemoteApplicationsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.PermissionGroupID,
			&i.Issuer,
			&i.JwksUri,
			&i.Mode,
			&i.PublicKeys,
			&i.Enabled,
			&i.DisplayName,
			&i.Tier,
			&i.TrustRoot,
			&i.DocumentEndpoint,
			&i.RootVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const remoteApplicationsEnabled = `-- name: RemoteApplicationsEnabled :many
SELECT id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, display_name, tier, trust_root, document_endpoint, root_verified_at, created_at, updated_at
FROM profiles.remote_applications
WHERE enabled = true
ORDER BY slug ASC
`

type RemoteApplicationsEnabledRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	DisplayName       string
	Tier              string
	TrustRoot         string
	DocumentEndpoint  string
	RootVerifiedAt    *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) RemoteApplicationsEnabled(ctx context.Context) ([]RemoteApplicationsEnabledRow, error) {
	rows, err := q.db.Query(ctx, remoteApplicationsEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteApplicationsEnabledRow
	for rows.Next() {
		var i RemoteApplicationsEnabledRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.PermissionGroupID,
			&i.Issuer,
			&i.JwksUri,
			&i.Mode,
			&i.PublicKeys,
			&i.Enabled,
			&i.DisplayName,
			&i.Tier,
			&i.TrustRoot,
			&i.DocumentEndpoint,
			&i.RootVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
