// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remote_applications.sql

package db

import (
	"context"
	"time"
)

const remoteAppAttributeDefDelete = `-- name: RemoteAppAttributeDefDelete :execrows
DELETE FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid AND key = $2
`

type RemoteAppAttributeDefDeleteParams struct {
	RemoteApplicationID string
	Key                 string
}

func (q *Queries) RemoteAppAttributeDefDelete(ctx context.Context, arg RemoteAppAttributeDefDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, remoteAppAttributeDefDelete, arg.RemoteApplicationID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const remoteAppAttributeDefGet = `-- name: RemoteAppAttributeDefGet :one
SELECT remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid AND key = $2 AND version = $3
`

type RemoteAppAttributeDefGetParams struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
}

type RemoteAppAttributeDefGetRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RemoteAppAttributeDefGet(ctx context.Context, arg RemoteAppAttributeDefGetParams) (RemoteAppAttributeDefGetRow, error) {
	row := q.db.QueryRow(ctx, remoteAppAttributeDefGet, arg.RemoteApplicationID, arg.Key, arg.Version)
	var i RemoteAppAttributeDefGetRow
	err := row.Scan(
		&i.RemoteApplicationID,
		&i.Key,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteAppAttributeDefGetLatest = `-- name: RemoteAppAttributeDefGetLatest :one
SELECT remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid AND key = $2
ORDER BY version DESC
LIMIT 1
`

type RemoteAppAttributeDefGetLatestParams struct {
	RemoteApplicationID string
	Key                 string
}

type RemoteAppAttributeDefGetLatestRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RemoteAppAttributeDefGetLatest(ctx context.Context, arg RemoteAppAttributeDefGetLatestParams) (RemoteAppAttributeDefGetLatestRow, error) {
	row := q.db.QueryRow(ctx, remoteAppAttributeDefGetLatest, arg.RemoteApplicationID, arg.Key)
	var i RemoteAppAttributeDefGetLatestRow
	err := row.Scan(
		&i.RemoteApplicationID,
		&i.Key,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteAppAttributeDefUpsert = `-- name: RemoteAppAttributeDefUpsert :one

INSERT INTO profiles.remote_application_attribute_defs (remote_application_id, key, version, definition)
VALUES ($1::uuid, $2, $3, $4)
ON CONFLICT (remote_application_id, key, version) DO UPDATE
  SET definition = EXCLUDED.definition, updated_at = now()
RETURNING remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
`

type RemoteAppAttributeDefUpsertParams struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
}

type RemoteAppAttributeDefUpsertRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// Attribute definition registry (#75): REFERENCE-mode opaque definitions.
func (q *Queries) RemoteAppAttributeDefUpsert(ctx context.Context, arg RemoteAppAttributeDefUpsertParams) (RemoteAppAttributeDefUpsertRow, error) {
	row := q.db.QueryRow(ctx, remoteAppAttributeDefUpsert,
		arg.RemoteApplicationID,
		arg.Key,
		arg.Version,
		arg.Definition,
	)
	var i RemoteAppAttributeDefUpsertRow
	err := row.Scan(
		&i.RemoteApplicationID,
		&i.Key,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteAppAttributeDefsList = `-- name: RemoteAppAttributeDefsList :many
SELECT remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid
ORDER BY key ASC, version DESC
`

type RemoteAppAttributeDefsListRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RemoteAppAttributeDefsList(ctx context.Context, remoteApplicationID string) ([]RemoteAppAttributeDefsListRow, error) {
	rows, err := q.db.Query(ctx, remoteAppAttributeDefsList, remoteApplicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteAppAttributeDefsListRow
	for rows.Next() {
		var i RemoteAppAttributeDefsListRow
		if err := rows.Scan(
			&i.RemoteApplicationID,
			&i.Key,
			&i.Version,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const remoteApplicationByIssuer = `-- name: RemoteApplicationByIssuer :one
SELECT id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, created_at, updated_at
FROM profiles.remote_applications
WHERE issuer = $1 AND deleted_at IS NULL
`

type RemoteApplicationByIssuerRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) RemoteApplicationByIssuer(ctx context.Context, issuer string) (RemoteApplicationByIssuerRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationByIssuer, issuer)
	var i RemoteApplicationByIssuerRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationBySlug = `-- name: RemoteApplicationBySlug :one
SELECT id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, created_at, updated_at
FROM profiles.remote_applications
WHERE slug = $1 AND deleted_at IS NULL
`

type RemoteApplicationBySlugRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) RemoteApplicationBySlug(ctx context.Context, slug string) (RemoteApplicationBySlugRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationBySlug, slug)
	var i RemoteApplicationBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationDelete = `-- name: RemoteApplicationDelete :execrows
DELETE FROM profiles.remote_applications WHERE issuer = $1
`

func (q *Queries) RemoteApplicationDelete(ctx context.Context, issuer string) (int64, error) {
	result, err := q.db.Exec(ctx, remoteApplicationDelete, issuer)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const remoteApplicationUpsert = `-- name: RemoteApplicationUpsert :one

INSERT INTO profiles.remote_applications (slug, permission_group_id, issuer, jwks_uri, mode, public_keys, enabled)
VALUES ($1, $2::uuid, $3, $4, $5, $6, $7)
ON CONFLICT (issuer) DO UPDATE
  SET slug          = EXCLUDED.slug,
      permission_group_id = EXCLUDED.permission_group_id,
      jwks_uri      = EXCLUDED.jwks_uri,
      mode          = EXCLUDED.mode,
      public_keys   = EXCLUDED.public_keys,
      enabled       = EXCLUDED.enabled,
      updated_at    = now()
RETURNING id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, created_at, updated_at
`

type RemoteApplicationUpsertParams struct {
	Slug              string
	PermissionGroupID *string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
}

type RemoteApplicationUpsertRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Remote application registry (core/service_remote_applications.go). A
// remote_application is the federation PRINCIPAL: it authenticates by signing
// JWTs verified against its JWKS/public keys (#74).
//
// The controlling group is addressed as permission_group_id throughout.
func (q *Queries) RemoteApplicationUpsert(ctx context.Context, arg RemoteApplicationUpsertParams) (RemoteApplicationUpsertRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationUpsert,
		arg.Slug,
		arg.PermissionGroupID,
		arg.Issuer,
		arg.JwksUri,
		arg.Mode,
		arg.PublicKeys,
		arg.Enabled,
	)
	var i RemoteApplicationUpsertRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PermissionGroupID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationsAll = `-- name: RemoteApplicationsAll :many
SELECT id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, created_at, updated_at
FROM profiles.remote_applications
WHERE deleted_at IS NULL
ORDER BY slug ASC
`

type RemoteApplicationsAllRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) RemoteApplicationsAll(ctx context.Context) ([]RemoteApplicationsAllRow, error) {
	rows, err := q.db.Query(ctx, remoteApplicationsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteApplicationsAllRow
	for rows.Next() {
		var i RemoteApplicationsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.PermissionGroupID,
			&i.Issuer,
			&i.JwksUri,
			&i.Mode,
			&i.PublicKeys,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const remoteApplicationsEnabled = `-- name: RemoteApplicationsEnabled :many
SELECT id::text, slug, COALESCE(permission_group_id::text, '')::text AS permission_group_id, issuer, jwks_uri, mode, public_keys, enabled, created_at, updated_at
FROM profiles.remote_applications
WHERE enabled = true AND deleted_at IS NULL
ORDER BY slug ASC
`

type RemoteApplicationsEnabledRow struct {
	ID                string
	Slug              string
	PermissionGroupID string
	Issuer            string
	JwksUri           string
	Mode              string
	PublicKeys        []byte
	Enabled           bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) RemoteApplicationsEnabled(ctx context.Context) ([]RemoteApplicationsEnabledRow, error) {
	rows, err := q.db.Query(ctx, remoteApplicationsEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteApplicationsEnabledRow
	for rows.Next() {
		var i RemoteApplicationsEnabledRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.PermissionGroupID,
			&i.Issuer,
			&i.JwksUri,
			&i.Mode,
			&i.PublicKeys,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
