// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reserved_accounts.sql

package db

import (
	"context"
)

const userMetadata = `-- name: UserMetadata :one

SELECT COALESCE(metadata, '{}'::jsonb)::jsonb AS metadata
FROM profiles.users WHERE id = $1::uuid
`

// Reserved-account + metadata queries (core/service_reserved_accounts.go).
func (q *Queries) UserMetadata(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, userMetadata, id)
	var metadata []byte
	err := row.Scan(&metadata)
	return metadata, err
}

const userMetadataPatch = `-- name: UserMetadataPatch :execrows
UPDATE profiles.users
SET metadata = COALESCE(metadata, '{}'::jsonb) || $1::jsonb,
    updated_at = now()
WHERE id = $2::uuid
`

type UserMetadataPatchParams struct {
	Patch []byte
	ID    string
}

func (q *Queries) UserMetadataPatch(ctx context.Context, arg UserMetadataPatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, userMetadataPatch, arg.Patch, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
