// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reserved_accounts.sql

package db

import (
	"context"
)

const orgIDReservedBySlug = `-- name: OrgIDReservedBySlug :one
SELECT id::text,
       (CASE
         WHEN jsonb_typeof(COALESCE(metadata, '{}'::jsonb)->'reserved')='boolean'
         THEN (COALESCE(metadata, '{}'::jsonb)->>'reserved')::boolean
         ELSE false
       END)::boolean AS reserved
FROM profiles.orgs
WHERE slug = $1
  AND deleted_at IS NULL
`

type OrgIDReservedBySlugRow struct {
	ID       string
	Reserved bool
}

func (q *Queries) OrgIDReservedBySlug(ctx context.Context, slug string) (OrgIDReservedBySlugRow, error) {
	row := q.db.QueryRow(ctx, orgIDReservedBySlug, slug)
	var i OrgIDReservedBySlugRow
	err := row.Scan(&i.ID, &i.Reserved)
	return i, err
}

const orgMetadata = `-- name: OrgMetadata :one
SELECT COALESCE(metadata, '{}'::jsonb)::jsonb AS metadata
FROM profiles.orgs WHERE id = $1::uuid AND deleted_at IS NULL
`

func (q *Queries) OrgMetadata(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, orgMetadata, id)
	var metadata []byte
	err := row.Scan(&metadata)
	return metadata, err
}

const orgMetadataPatch = `-- name: OrgMetadataPatch :execrows
UPDATE profiles.orgs
SET metadata = COALESCE(metadata, '{}'::jsonb) || $1::jsonb,
    updated_at = now()
WHERE id = $2::uuid AND deleted_at IS NULL
`

type OrgMetadataPatchParams struct {
	Patch []byte
	ID    string
}

func (q *Queries) OrgMetadataPatch(ctx context.Context, arg OrgMetadataPatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, orgMetadataPatch, arg.Patch, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const orgSetReserved = `-- name: OrgSetReserved :exec
UPDATE profiles.orgs
SET metadata = jsonb_set(COALESCE(metadata, '{}'::jsonb), '{reserved}', to_jsonb($1::boolean), true),
    updated_at = now()
WHERE id = $2::uuid
`

type OrgSetReservedParams struct {
	Reserved bool
	ID       string
}

func (q *Queries) OrgSetReserved(ctx context.Context, arg OrgSetReservedParams) error {
	_, err := q.db.Exec(ctx, orgSetReserved, arg.Reserved, arg.ID)
	return err
}

const personalOrgIDSlugReservedByOwner = `-- name: PersonalOrgIDSlugReservedByOwner :one
SELECT id::text,
       slug,
       (CASE
         WHEN jsonb_typeof(COALESCE(metadata, '{}'::jsonb)->'reserved')='boolean'
         THEN (COALESCE(metadata, '{}'::jsonb)->>'reserved')::boolean
         ELSE false
       END)::boolean AS reserved
FROM profiles.orgs
WHERE owner_user_id = $1::uuid
  AND is_personal = true
  AND deleted_at IS NULL
`

type PersonalOrgIDSlugReservedByOwnerRow struct {
	ID       string
	Slug     string
	Reserved bool
}

func (q *Queries) PersonalOrgIDSlugReservedByOwner(ctx context.Context, ownerUserID string) (PersonalOrgIDSlugReservedByOwnerRow, error) {
	row := q.db.QueryRow(ctx, personalOrgIDSlugReservedByOwner, ownerUserID)
	var i PersonalOrgIDSlugReservedByOwnerRow
	err := row.Scan(&i.ID, &i.Slug, &i.Reserved)
	return i, err
}

const userClearLoginIdentifiers = `-- name: UserClearLoginIdentifiers :exec
UPDATE profiles.users
SET email = NULL,
    email_verified = false,
    phone_number = NULL,
    phone_verified = false,
    updated_at = now()
WHERE id = $1::uuid
`

func (q *Queries) UserClearLoginIdentifiers(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, userClearLoginIdentifiers, id)
	return err
}

const userIDReservedByUsername = `-- name: UserIDReservedByUsername :one
SELECT id::text,
       (CASE
         WHEN jsonb_typeof(COALESCE(metadata, '{}'::jsonb)->'reserved')='boolean'
         THEN (COALESCE(metadata, '{}'::jsonb)->>'reserved')::boolean
         ELSE false
       END)::boolean AS reserved
FROM profiles.users
WHERE username = $1
  AND deleted_at IS NULL
`

type UserIDReservedByUsernameRow struct {
	ID       string
	Reserved bool
}

func (q *Queries) UserIDReservedByUsername(ctx context.Context, username *string) (UserIDReservedByUsernameRow, error) {
	row := q.db.QueryRow(ctx, userIDReservedByUsername, username)
	var i UserIDReservedByUsernameRow
	err := row.Scan(&i.ID, &i.Reserved)
	return i, err
}

const userMetadata = `-- name: UserMetadata :one
SELECT COALESCE(metadata, '{}'::jsonb)::jsonb AS metadata
FROM profiles.users WHERE id = $1::uuid
`

func (q *Queries) UserMetadata(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, userMetadata, id)
	var metadata []byte
	err := row.Scan(&metadata)
	return metadata, err
}

const userMetadataPatch = `-- name: UserMetadataPatch :execrows
UPDATE profiles.users
SET metadata = COALESCE(metadata, '{}'::jsonb) || $1::jsonb,
    updated_at = now()
WHERE id = $2::uuid
`

type UserMetadataPatchParams struct {
	Patch []byte
	ID    string
}

func (q *Queries) UserMetadataPatch(ctx context.Context, arg UserMetadataPatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, userMetadataPatch, arg.Patch, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userPasswordDelete = `-- name: UserPasswordDelete :exec
DELETE FROM profiles.user_passwords WHERE user_id = $1::uuid
`

func (q *Queries) UserPasswordDelete(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, userPasswordDelete, userID)
	return err
}

const userProvidersDeleteByUser = `-- name: UserProvidersDeleteByUser :exec
DELETE FROM profiles.user_providers WHERE user_id = $1::uuid
`

func (q *Queries) UserProvidersDeleteByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, userProvidersDeleteByUser, userID)
	return err
}

const userSetReserved = `-- name: UserSetReserved :exec

UPDATE profiles.users
SET metadata = jsonb_set(COALESCE(metadata, '{}'::jsonb), '{reserved}', to_jsonb($1::boolean), true),
    updated_at = now()
WHERE id = $2::uuid
`

type UserSetReservedParams struct {
	Reserved bool
	ID       string
}

// Reserved-account + metadata queries (core/service_reserved_accounts.go).
func (q *Queries) UserSetReserved(ctx context.Context, arg UserSetReservedParams) error {
	_, err := q.db.Exec(ctx, userSetReserved, arg.Reserved, arg.ID)
	return err
}
