// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reserved_accounts.sql

package db

import (
	"context"
)

const userMetadata = `-- name: UserMetadata :one

SELECT COALESCE(metadata, '{}'::jsonb)::jsonb AS metadata
FROM users WHERE id = $1::uuid
`

// Reserved-account + metadata queries.
func (q *Queries) UserMetadata(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, userMetadata, id)
	var metadata []byte
	err := row.Scan(&metadata)
	return metadata, err
}
