// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_catalog.sql

package db

import (
	"context"
)

const roleCatalogFingerprint = `-- name: RoleCatalogFingerprint :one

SELECT fingerprint FROM role_catalog_state
`

// The role catalog the credential sweep last reconciled.
func (q *Queries) RoleCatalogFingerprint(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, roleCatalogFingerprint)
	var fingerprint string
	err := row.Scan(&fingerprint)
	return fingerprint, err
}

const roleCatalogSetFingerprint = `-- name: RoleCatalogSetFingerprint :exec
INSERT INTO role_catalog_state (fingerprint) VALUES ($1)
ON CONFLICT (singleton) DO UPDATE SET fingerprint = EXCLUDED.fingerprint, swept_at = now()
`

func (q *Queries) RoleCatalogSetFingerprint(ctx context.Context, fingerprint string) error {
	_, err := q.db.Exec(ctx, roleCatalogSetFingerprint, fingerprint)
	return err
}
