// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime.sql

package db

import (
	"context"
)

const advisoryLock = `-- name: AdvisoryLock :exec
SELECT pg_advisory_lock(hashtext(current_database()), hashtext($1::text))
`

// Session-scoped advisory lock on key in this database: hold it on one
// dedicated connection, whose close releases it.
func (q *Queries) AdvisoryLock(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, advisoryLock, key)
	return err
}

const advisoryXactLock = `-- name: AdvisoryXactLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// Transaction-scoped advisory lock on key, released when the transaction ends.
func (q *Queries) AdvisoryXactLock(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, advisoryXactLock, key)
	return err
}

const setSearchPath = `-- name: SetSearchPath :exec

SELECT set_config('search_path', $1::text, $2::boolean)
`

type SetSearchPathParams struct {
	SearchPath string
	IsLocal    bool
}

// Connection setup and migration locks. The schema identifier in CREATE
// SCHEMA stays inline in the engine.
// is_local false sets it for the session, true until the transaction (or
// savepoint) ends.
func (q *Queries) SetSearchPath(ctx context.Context, arg SetSearchPathParams) error {
	_, err := q.db.Exec(ctx, setSearchPath, arg.SearchPath, arg.IsLocal)
	return err
}
