// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_tokens.sql

package db

import (
	"context"
	"time"
)

const serviceTokenByKeyID = `-- name: ServiceTokenByKeyID :one
SELECT t.id::text AS id, t.secret_hash, t.expires_at, t.revoked_at,
       o.id::text AS tenant_id, o.slug, o.deleted_at AS tenant_deleted_at
FROM profiles.service_tokens t
JOIN profiles.tenants o ON o.id = t.tenant_id
WHERE t.key_id = $1
`

type ServiceTokenByKeyIDRow struct {
	ID              string
	SecretHash      []byte
	ExpiresAt       *time.Time
	RevokedAt       *time.Time
	TenantID        string
	Slug            string
	TenantDeletedAt *time.Time
}

func (q *Queries) ServiceTokenByKeyID(ctx context.Context, keyID string) (ServiceTokenByKeyIDRow, error) {
	row := q.db.QueryRow(ctx, serviceTokenByKeyID, keyID)
	var i ServiceTokenByKeyIDRow
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.TenantID,
		&i.Slug,
		&i.TenantDeletedAt,
	)
	return i, err
}

const serviceTokenInsert = `-- name: ServiceTokenInsert :one

INSERT INTO profiles.service_tokens
  (tenant_id, key_id, secret_hash, name, created_by, expires_at)
VALUES ($1::uuid, $2, $3, $4, $5::uuid, $6)
RETURNING id::text, created_at
`

type ServiceTokenInsertParams struct {
	TenantID   string
	KeyID      string
	SecretHash []byte
	Name       string
	CreatedBy  *string
	ExpiresAt  *time.Time
}

type ServiceTokenInsertRow struct {
	ID        string
	CreatedAt time.Time
}

// Service token queries (core/service_tokens.go).
func (q *Queries) ServiceTokenInsert(ctx context.Context, arg ServiceTokenInsertParams) (ServiceTokenInsertRow, error) {
	row := q.db.QueryRow(ctx, serviceTokenInsert,
		arg.TenantID,
		arg.KeyID,
		arg.SecretHash,
		arg.Name,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i ServiceTokenInsertRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const serviceTokenPermissionInsert = `-- name: ServiceTokenPermissionInsert :exec
INSERT INTO profiles.service_token_permissions (service_token_id, permission)
VALUES ($1::uuid, $2)
`

type ServiceTokenPermissionInsertParams struct {
	ServiceTokenID string
	Permission     string
}

func (q *Queries) ServiceTokenPermissionInsert(ctx context.Context, arg ServiceTokenPermissionInsertParams) error {
	_, err := q.db.Exec(ctx, serviceTokenPermissionInsert, arg.ServiceTokenID, arg.Permission)
	return err
}

const serviceTokenPermissionsByTokenID = `-- name: ServiceTokenPermissionsByTokenID :many
SELECT permission
FROM profiles.service_token_permissions
WHERE service_token_id = $1::uuid
ORDER BY permission
`

func (q *Queries) ServiceTokenPermissionsByTokenID(ctx context.Context, serviceTokenID string) ([]string, error) {
	rows, err := q.db.Query(ctx, serviceTokenPermissionsByTokenID, serviceTokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceTokenPermissionsByTokenIDs = `-- name: ServiceTokenPermissionsByTokenIDs :many
SELECT service_token_id::text AS service_token_id, permission
FROM profiles.service_token_permissions
WHERE service_token_id = ANY($1::uuid[])
ORDER BY service_token_id::text, permission
`

type ServiceTokenPermissionsByTokenIDsRow struct {
	ServiceTokenID string
	Permission     string
}

func (q *Queries) ServiceTokenPermissionsByTokenIDs(ctx context.Context, ids []string) ([]ServiceTokenPermissionsByTokenIDsRow, error) {
	rows, err := q.db.Query(ctx, serviceTokenPermissionsByTokenIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceTokenPermissionsByTokenIDsRow
	for rows.Next() {
		var i ServiceTokenPermissionsByTokenIDsRow
		if err := rows.Scan(&i.ServiceTokenID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceTokenResourceInsert = `-- name: ServiceTokenResourceInsert :exec
INSERT INTO profiles.service_token_resources (token_id, kind, resource_id)
VALUES ($1::uuid, $2, $3)
`

type ServiceTokenResourceInsertParams struct {
	TokenID    string
	Kind       string
	ResourceID string
}

func (q *Queries) ServiceTokenResourceInsert(ctx context.Context, arg ServiceTokenResourceInsertParams) error {
	_, err := q.db.Exec(ctx, serviceTokenResourceInsert, arg.TokenID, arg.Kind, arg.ResourceID)
	return err
}

const serviceTokenResourcesByTokenID = `-- name: ServiceTokenResourcesByTokenID :many
SELECT kind, resource_id
FROM profiles.service_token_resources
WHERE token_id = $1::uuid
ORDER BY kind, resource_id
`

type ServiceTokenResourcesByTokenIDRow struct {
	Kind       string
	ResourceID string
}

func (q *Queries) ServiceTokenResourcesByTokenID(ctx context.Context, tokenID string) ([]ServiceTokenResourcesByTokenIDRow, error) {
	rows, err := q.db.Query(ctx, serviceTokenResourcesByTokenID, tokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceTokenResourcesByTokenIDRow
	for rows.Next() {
		var i ServiceTokenResourcesByTokenIDRow
		if err := rows.Scan(&i.Kind, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceTokenResourcesByTokenIDs = `-- name: ServiceTokenResourcesByTokenIDs :many
SELECT token_id::text AS token_id, kind, resource_id
FROM profiles.service_token_resources
WHERE token_id = ANY($1::uuid[])
ORDER BY token_id::text, kind, resource_id
`

type ServiceTokenResourcesByTokenIDsRow struct {
	TokenID    string
	Kind       string
	ResourceID string
}

func (q *Queries) ServiceTokenResourcesByTokenIDs(ctx context.Context, ids []string) ([]ServiceTokenResourcesByTokenIDsRow, error) {
	rows, err := q.db.Query(ctx, serviceTokenResourcesByTokenIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceTokenResourcesByTokenIDsRow
	for rows.Next() {
		var i ServiceTokenResourcesByTokenIDsRow
		if err := rows.Scan(&i.TokenID, &i.Kind, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceTokenRevoke = `-- name: ServiceTokenRevoke :execrows
UPDATE profiles.service_tokens
SET revoked_at = now()
WHERE id = $1::uuid AND tenant_id = $2::uuid AND revoked_at IS NULL
`

type ServiceTokenRevokeParams struct {
	ID       string
	TenantID string
}

func (q *Queries) ServiceTokenRevoke(ctx context.Context, arg ServiceTokenRevokeParams) (int64, error) {
	result, err := q.db.Exec(ctx, serviceTokenRevoke, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const serviceTokenTouchLastUsed = `-- name: ServiceTokenTouchLastUsed :exec
UPDATE profiles.service_tokens SET last_used_at = now() WHERE id = $1::uuid
`

func (q *Queries) ServiceTokenTouchLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, serviceTokenTouchLastUsed, id)
	return err
}

const serviceTokensByTenant = `-- name: ServiceTokensByTenant :many
SELECT id::text, key_id, name, COALESCE(created_by::text, '')::text AS created_by,
       created_at, last_used_at, expires_at, revoked_at
FROM profiles.service_tokens
WHERE tenant_id = $1::uuid
ORDER BY created_at DESC
`

type ServiceTokensByTenantRow struct {
	ID         string
	KeyID      string
	Name       string
	CreatedBy  string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	ExpiresAt  *time.Time
	RevokedAt  *time.Time
}

func (q *Queries) ServiceTokensByTenant(ctx context.Context, tenantID string) ([]ServiceTokensByTenantRow, error) {
	rows, err := q.db.Query(ctx, serviceTokensByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceTokensByTenantRow
	for rows.Next() {
		var i ServiceTokensByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
