// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_events.sql

package db

import (
	"context"
	"time"
)

const sessionEventInsert = `-- name: SessionEventInsert :exec

INSERT INTO profiles.session_events (occurred_at, issuer, user_id, session_id, event, method, reason, ip_addr, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type SessionEventInsertParams struct {
	OccurredAt time.Time
	Issuer     string
	UserID     string
	SessionID  string
	Event      string
	Method     *string
	Reason     *string
	IpAddr     *string
	UserAgent  *string
}

// Session-event history queries (authcore/session_events.go, #245). Best-effort
// append-only log: sign-ins, revocations, password changes. Retention-pruned.
func (q *Queries) SessionEventInsert(ctx context.Context, arg SessionEventInsertParams) error {
	_, err := q.db.Exec(ctx, sessionEventInsert,
		arg.OccurredAt,
		arg.Issuer,
		arg.UserID,
		arg.SessionID,
		arg.Event,
		arg.Method,
		arg.Reason,
		arg.IpAddr,
		arg.UserAgent,
	)
	return err
}

const sessionEventsListByUser = `-- name: SessionEventsListByUser :many
SELECT occurred_at, issuer, user_id, session_id, event, method, reason, ip_addr, user_agent
FROM profiles.session_events
WHERE user_id = $1
  AND (cardinality($2::text[]) = 0 OR event = ANY($2::text[]))
ORDER BY occurred_at DESC
LIMIT $3
`

type SessionEventsListByUserParams struct {
	UserID   string
	Events   []string
	RowLimit int64
}

type SessionEventsListByUserRow struct {
	OccurredAt time.Time
	Issuer     string
	UserID     string
	SessionID  string
	Event      string
	Method     *string
	Reason     *string
	IpAddr     *string
	UserAgent  *string
}

// Per-user history, newest-first. An empty events array means all event types.
func (q *Queries) SessionEventsListByUser(ctx context.Context, arg SessionEventsListByUserParams) ([]SessionEventsListByUserRow, error) {
	rows, err := q.db.Query(ctx, sessionEventsListByUser, arg.UserID, arg.Events, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionEventsListByUserRow
	for rows.Next() {
		var i SessionEventsListByUserRow
		if err := rows.Scan(
			&i.OccurredAt,
			&i.Issuer,
			&i.UserID,
			&i.SessionID,
			&i.Event,
			&i.Method,
			&i.Reason,
			&i.IpAddr,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionEventsPruneBatch = `-- name: SessionEventsPruneBatch :execrows
DELETE FROM profiles.session_events
WHERE id IN (
    SELECT id FROM profiles.session_events
    WHERE occurred_at < $1::timestamptz
    ORDER BY occurred_at
    LIMIT $2::bigint
)
`

type SessionEventsPruneBatchParams struct {
	Cutoff    time.Time
	BatchSize int64
}

// One bounded retention batch: delete up to batch_size rows older than cutoff,
// walking the occurred_at index. Callers loop until a short batch — never an
// unbounded single DELETE.
func (q *Queries) SessionEventsPruneBatch(ctx context.Context, arg SessionEventsPruneBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, sessionEventsPruneBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
