// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"
)

const sessionByCurrentTokenHash = `-- name: SessionByCurrentTokenHash :one
SELECT id::text, user_id, auth_methods, dpop_jkt
FROM refresh_sessions
WHERE current_token_hash = $1 AND issuer = $2 AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

type SessionByCurrentTokenHashParams struct {
	CurrentTokenHash []byte
	Issuer           string
}

type SessionByCurrentTokenHashRow struct {
	ID          string
	UserID      string
	AuthMethods []string
	DpopJkt     *string
}

func (q *Queries) SessionByCurrentTokenHash(ctx context.Context, arg SessionByCurrentTokenHashParams) (SessionByCurrentTokenHashRow, error) {
	row := q.db.QueryRow(ctx, sessionByCurrentTokenHash, arg.CurrentTokenHash, arg.Issuer)
	var i SessionByCurrentTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthMethods,
		&i.DpopJkt,
	)
	return i, err
}

const sessionByHistoricalTokenHash = `-- name: SessionByHistoricalTokenHash :one
SELECT s.id::text AS id, s.user_id, s.auth_methods, s.expires_at,
       s.current_token_hash, s.previous_successor_sealed, s.previous_rotated_at, s.dpop_jkt
FROM refresh_token_history h
JOIN refresh_sessions s ON s.id = h.session_id
WHERE h.token_hash = $1 AND s.issuer = $2 AND s.revoked_at IS NULL
`

type SessionByHistoricalTokenHashParams struct {
	TokenHash []byte
	Issuer    string
}

type SessionByHistoricalTokenHashRow struct {
	ID                      string
	UserID                  string
	AuthMethods             []string
	ExpiresAt               *time.Time
	CurrentTokenHash        []byte
	PreviousSuccessorSealed []byte
	PreviousRotatedAt       *time.Time
	DpopJkt                 *string
}

// A consumed token stays attributable for 90 days (SessionRotate). Only the
// immediate predecessor can open the current grace seal; older hashes still
// identify the session for reuse detection.
func (q *Queries) SessionByHistoricalTokenHash(ctx context.Context, arg SessionByHistoricalTokenHashParams) (SessionByHistoricalTokenHashRow, error) {
	row := q.db.QueryRow(ctx, sessionByHistoricalTokenHash, arg.TokenHash, arg.Issuer)
	var i SessionByHistoricalTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthMethods,
		&i.ExpiresAt,
		&i.CurrentTokenHash,
		&i.PreviousSuccessorSealed,
		&i.PreviousRotatedAt,
		&i.DpopJkt,
	)
	return i, err
}

const sessionFreshSince = `-- name: SessionFreshSince :one
SELECT COALESCE(last_authenticated_at, created_at)::timestamptz AS fresh_since,
       auth_methods, mfa_authenticated_at, dpop_jkt
FROM refresh_sessions
WHERE id = $1::uuid
  AND user_id = $2::uuid
  AND issuer = $3
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

type SessionFreshSinceParams struct {
	SessionID string
	UserID    string
	Issuer    string
}

type SessionFreshSinceRow struct {
	FreshSince         time.Time
	AuthMethods        []string
	MfaAuthenticatedAt *time.Time
	DpopJkt            *string
}

func (q *Queries) SessionFreshSince(ctx context.Context, arg SessionFreshSinceParams) (SessionFreshSinceRow, error) {
	row := q.db.QueryRow(ctx, sessionFreshSince, arg.SessionID, arg.UserID, arg.Issuer)
	var i SessionFreshSinceRow
	err := row.Scan(
		&i.FreshSince,
		&i.AuthMethods,
		&i.MfaAuthenticatedAt,
		&i.DpopJkt,
	)
	return i, err
}

const sessionFreshSinceForUpdate = `-- name: SessionFreshSinceForUpdate :one
SELECT COALESCE(last_authenticated_at, created_at)::timestamptz AS fresh_since, auth_methods, mfa_authenticated_at
FROM refresh_sessions
WHERE id = $1::uuid AND user_id = $2::uuid
  AND issuer = $3 AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
FOR UPDATE
`

type SessionFreshSinceForUpdateParams struct {
	SessionID string
	UserID    string
	Issuer    string
}

type SessionFreshSinceForUpdateRow struct {
	FreshSince         time.Time
	AuthMethods        []string
	MfaAuthenticatedAt *time.Time
}

func (q *Queries) SessionFreshSinceForUpdate(ctx context.Context, arg SessionFreshSinceForUpdateParams) (SessionFreshSinceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, sessionFreshSinceForUpdate, arg.SessionID, arg.UserID, arg.Issuer)
	var i SessionFreshSinceForUpdateRow
	err := row.Scan(&i.FreshSince, &i.AuthMethods, &i.MfaAuthenticatedAt)
	return i, err
}

const sessionInsert = `-- name: SessionInsert :exec

INSERT INTO refresh_sessions (id, user_id, issuer, current_token_hash, expires_at, user_agent, ip_addr, last_authenticated_at, auth_methods, mfa_authenticated_at, dpop_jkt)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), $8, CASE WHEN 'mfa' = ANY($8::text[]) THEN now() END, $9)
`

type SessionInsertParams struct {
	ID               string
	UserID           string
	Issuer           string
	CurrentTokenHash []byte
	ExpiresAt        *time.Time
	UserAgent        *string
	IpAddr           *string
	AuthMethods      []string
	DpopJkt          *string
}

// Refresh-session queries.
func (q *Queries) SessionInsert(ctx context.Context, arg SessionInsertParams) error {
	_, err := q.db.Exec(ctx, sessionInsert,
		arg.ID,
		arg.UserID,
		arg.Issuer,
		arg.CurrentTokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddr,
		arg.AuthMethods,
		arg.DpopJkt,
	)
	return err
}

const sessionMarkAuthenticated = `-- name: SessionMarkAuthenticated :execrows
UPDATE refresh_sessions
SET last_authenticated_at = now(),
    auth_methods = ARRAY(
      SELECT DISTINCT unnest(auth_methods || $1::text[])
    ),
    mfa_authenticated_at = CASE WHEN 'mfa' = ANY($1::text[]) THEN now() ELSE mfa_authenticated_at END
WHERE id = $2::uuid
  AND user_id = $3::uuid
  AND issuer = $4
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

type SessionMarkAuthenticatedParams struct {
	AuthMethods []string
	SessionID   string
	UserID      string
	Issuer      string
}

// Re-proving identity refreshes the freshness window and UNIONS the methods
// just used into what the session proved, so its refresh assurance never
// drops. MFA freshness moves only when these methods include the second factor.
func (q *Queries) SessionMarkAuthenticated(ctx context.Context, arg SessionMarkAuthenticatedParams) (int64, error) {
	result, err := q.db.Exec(ctx, sessionMarkAuthenticated,
		arg.AuthMethods,
		arg.SessionID,
		arg.UserID,
		arg.Issuer,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionProvedPassword = `-- name: SessionProvedPassword :one
SELECT ('pwd' = ANY(auth_methods))::boolean AS proved
FROM refresh_sessions
WHERE id = $1::uuid AND user_id = $2::uuid AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
`

type SessionProvedPasswordParams struct {
	SessionID string
	UserID    string
}

// Whether the user's live session session_id signed in with a password.
func (q *Queries) SessionProvedPassword(ctx context.Context, arg SessionProvedPasswordParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionProvedPassword, arg.SessionID, arg.UserID)
	var proved bool
	err := row.Scan(&proved)
	return proved, err
}

const sessionRevokeByIDForUser = `-- name: SessionRevokeByIDForUser :one
UPDATE refresh_sessions SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND issuer = $3 AND revoked_at IS NULL
RETURNING id::text
`

type SessionRevokeByIDForUserParams struct {
	ID     string
	UserID string
	Issuer string
}

func (q *Queries) SessionRevokeByIDForUser(ctx context.Context, arg SessionRevokeByIDForUserParams) (string, error) {
	row := q.db.QueryRow(ctx, sessionRevokeByIDForUser, arg.ID, arg.UserID, arg.Issuer)
	var id string
	err := row.Scan(&id)
	return id, err
}

const sessionRotate = `-- name: SessionRotate :execrows
WITH rotated AS (
  UPDATE refresh_sessions
  SET current_token_hash = $2, last_used_at = now(),
      user_agent = $3, ip_addr = $4,
      previous_successor_sealed = $5, previous_rotated_at = now()
  WHERE id = $6 AND current_token_hash = $1
    AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
  RETURNING id
), pruned AS (
  DELETE FROM refresh_token_history
  WHERE session_id = (SELECT id FROM rotated) AND consumed_at < now() - interval '90 days'
)
INSERT INTO refresh_token_history (session_id, token_hash)
SELECT id, $1 FROM rotated
`

type SessionRotateParams struct {
	ExpectedCurrentTokenHash []byte
	NewTokenHash             []byte
	UserAgent                *string
	IpAddr                   *string
	PreviousSuccessorSealed  []byte
	ID                       string
}

// Record the consumed hash and rotate in one statement. The CAS admits one
// writer; an insertion failure rolls back the rotation, and a lost CAS inserts
// no history. The row's latest seal still re-delivers the same successor to
// concurrent holders of the immediate predecessor.
//
// The session's history older than 90 days goes. A copied token is caught when
// its second holder presents it; a thief who refreshes first is caught when the
// victim's client next refreshes, so a victim away longer than 90 days no
// longer exposes it. Past the bound, a retired token is refused as unknown.
func (q *Queries) SessionRotate(ctx context.Context, arg SessionRotateParams) (int64, error) {
	result, err := q.db.Exec(ctx, sessionRotate,
		arg.ExpectedCurrentTokenHash,
		arg.NewTokenHash,
		arg.UserAgent,
		arg.IpAddr,
		arg.PreviousSuccessorSealed,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionsCountActive = `-- name: SessionsCountActive :one
SELECT count(*) FROM refresh_sessions
WHERE user_id = $1 AND issuer = $2 AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

type SessionsCountActiveParams struct {
	UserID string
	Issuer string
}

func (q *Queries) SessionsCountActive(ctx context.Context, arg SessionsCountActiveParams) (int64, error) {
	row := q.db.QueryRow(ctx, sessionsCountActive, arg.UserID, arg.Issuer)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sessionsCountActiveOutsideIssuers = `-- name: SessionsCountActiveOutsideIssuers :one
SELECT count(*) FROM refresh_sessions
WHERE user_id = $1 AND NOT (issuer = ANY($2::text[]))
  AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
`

type SessionsCountActiveOutsideIssuersParams struct {
	UserID  string
	Issuers []string
}

// Live sessions an account-wide revocation could not reach: issuers missing
// from the configured account issuer set.
func (q *Queries) SessionsCountActiveOutsideIssuers(ctx context.Context, arg SessionsCountActiveOutsideIssuersParams) (int64, error) {
	row := q.db.QueryRow(ctx, sessionsCountActiveOutsideIssuers, arg.UserID, arg.Issuers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sessionsDeleteRevokedOrExpiredBatch = `-- name: SessionsDeleteRevokedOrExpiredBatch :execrows
DELETE FROM refresh_sessions
WHERE ctid = ANY(ARRAY(
    SELECT ctid FROM refresh_sessions
    WHERE revoked_at IS NOT NULL
    UNION ALL
    SELECT ctid FROM refresh_sessions
    WHERE revoked_at IS NULL AND expires_at IS NOT NULL AND expires_at <= NOW()
    LIMIT $1::bigint
))
`

// One bounded GC batch (#325): collect up to batch_size dead sessions through
// the two partial indexes (revoked / expired), then delete them by tuple id so
// the outer step is a Tid Scan, never a table scan. Callers loop until a short
// batch. History rows cascade.
func (q *Queries) SessionsDeleteRevokedOrExpiredBatch(ctx context.Context, batchSize int64) (int64, error) {
	result, err := q.db.Exec(ctx, sessionsDeleteRevokedOrExpiredBatch, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionsEvictOldest = `-- name: SessionsEvictOldest :many
UPDATE refresh_sessions SET revoked_at = now()
WHERE id IN (
  SELECT id FROM refresh_sessions
  WHERE user_id = $1::uuid AND issuer = $2::text AND revoked_at IS NULL
    AND (expires_at IS NULL OR expires_at > now())
  ORDER BY last_used_at ASC
  LIMIT $3::bigint
)
RETURNING id::text
`

type SessionsEvictOldestParams struct {
	UserID     string
	Issuer     string
	EvictCount int64
}

func (q *Queries) SessionsEvictOldest(ctx context.Context, arg SessionsEvictOldestParams) ([]string, error) {
	rows, err := q.db.Query(ctx, sessionsEvictOldest, arg.UserID, arg.Issuer, arg.EvictCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionsListByUser = `-- name: SessionsListByUser :many
SELECT id::text, created_at, last_used_at, expires_at,
       user_agent, CASE WHEN ip_addr IS NULL THEN NULL ELSE NULLIF(host(ip_addr)::text, '') END AS ip_addr
FROM refresh_sessions
WHERE user_id = $1 AND issuer = $2 AND (revoked_at IS NULL)
`

type SessionsListByUserParams struct {
	UserID string
	Issuer string
}

type SessionsListByUserRow struct {
	ID         string
	CreatedAt  time.Time
	LastUsedAt time.Time
	ExpiresAt  *time.Time
	UserAgent  *string
	IpAddr     *string
}

// last_authenticated_at and revoked_at are intentionally NOT selected: the
// session-list handler never renders them, and revoked_at is always NULL here
// (the WHERE clause filters to non-revoked rows), so reading them was pure
// over-fetch (#230).
func (q *Queries) SessionsListByUser(ctx context.Context, arg SessionsListByUserParams) ([]SessionsListByUserRow, error) {
	rows, err := q.db.Query(ctx, sessionsListByUser, arg.UserID, arg.Issuer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionsListByUserRow
	for rows.Next() {
		var i SessionsListByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.UserAgent,
			&i.IpAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionsRevokeAll = `-- name: SessionsRevokeAll :many
UPDATE refresh_sessions SET revoked_at = now()
WHERE user_id = $1 AND issuer = ANY($2::text[])
  AND ($3::uuid IS NULL OR id <> $3::uuid)
  AND revoked_at IS NULL
RETURNING id::text, issuer
`

type SessionsRevokeAllParams struct {
	UserID        string
	Issuers       []string
	KeepSessionID *string
}

type SessionsRevokeAllRow struct {
	ID     string
	Issuer string
}

// issuers is the revocation scope: this issuer alone, or every account issuer.
// keep_session_id (optional) survives, e.g. the session changing the password.
func (q *Queries) SessionsRevokeAll(ctx context.Context, arg SessionsRevokeAllParams) ([]SessionsRevokeAllRow, error) {
	rows, err := q.db.Query(ctx, sessionsRevokeAll, arg.UserID, arg.Issuers, arg.KeepSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionsRevokeAllRow
	for rows.Next() {
		var i SessionsRevokeAllRow
		if err := rows.Scan(&i.ID, &i.Issuer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userSessionLive = `-- name: UserSessionLive :one
SELECT EXISTS(SELECT 1 FROM usable_users WHERE id = $1::uuid)::boolean AS usable,
  ($2::text = '' AND $3::text = ''
   OR EXISTS(SELECT 1 FROM refresh_sessions WHERE id = NULLIF($2::text, '')::uuid AND user_id = $1::uuid
     AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now()))
   OR EXISTS(SELECT 1 FROM user_device_keys WHERE id = NULLIF($3::text, '')::uuid AND user_id = $1::uuid
     AND revoked_at IS NULL))::boolean AS signed_in
`

type UserSessionLiveParams struct {
	UserID      string
	SessionID   string
	DeviceKeyID string
}

type UserSessionLiveRow struct {
	Usable   bool
	SignedIn bool
}

// The session check (#412): whether the account is usable, and whether the
// sign-in it names (session_id or device_key_id; ” = none) is still a live
// refresh session or device key of the account.
func (q *Queries) UserSessionLive(ctx context.Context, arg UserSessionLiveParams) (UserSessionLiveRow, error) {
	row := q.db.QueryRow(ctx, userSessionLive, arg.UserID, arg.SessionID, arg.DeviceKeyID)
	var i UserSessionLiveRow
	err := row.Scan(&i.Usable, &i.SignedIn)
	return i, err
}
