// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"
	"time"
)

const remoteAppAttributeDefDelete = `-- name: RemoteAppAttributeDefDelete :execrows
DELETE FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid AND key = $2
`

type RemoteAppAttributeDefDeleteParams struct {
	RemoteApplicationID string
	Key                 string
}

func (q *Queries) RemoteAppAttributeDefDelete(ctx context.Context, arg RemoteAppAttributeDefDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, remoteAppAttributeDefDelete, arg.RemoteApplicationID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const remoteAppAttributeDefGet = `-- name: RemoteAppAttributeDefGet :one
SELECT remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid AND key = $2 AND version = $3
`

type RemoteAppAttributeDefGetParams struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
}

type RemoteAppAttributeDefGetRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RemoteAppAttributeDefGet(ctx context.Context, arg RemoteAppAttributeDefGetParams) (RemoteAppAttributeDefGetRow, error) {
	row := q.db.QueryRow(ctx, remoteAppAttributeDefGet, arg.RemoteApplicationID, arg.Key, arg.Version)
	var i RemoteAppAttributeDefGetRow
	err := row.Scan(
		&i.RemoteApplicationID,
		&i.Key,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteAppAttributeDefGetLatest = `-- name: RemoteAppAttributeDefGetLatest :one
SELECT remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid AND key = $2
ORDER BY version DESC
LIMIT 1
`

type RemoteAppAttributeDefGetLatestParams struct {
	RemoteApplicationID string
	Key                 string
}

type RemoteAppAttributeDefGetLatestRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RemoteAppAttributeDefGetLatest(ctx context.Context, arg RemoteAppAttributeDefGetLatestParams) (RemoteAppAttributeDefGetLatestRow, error) {
	row := q.db.QueryRow(ctx, remoteAppAttributeDefGetLatest, arg.RemoteApplicationID, arg.Key)
	var i RemoteAppAttributeDefGetLatestRow
	err := row.Scan(
		&i.RemoteApplicationID,
		&i.Key,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteAppAttributeDefUpsert = `-- name: RemoteAppAttributeDefUpsert :one

INSERT INTO profiles.remote_application_attribute_defs (remote_application_id, key, version, definition)
VALUES ($1::uuid, $2, $3, $4)
ON CONFLICT (remote_application_id, key, version) DO UPDATE
  SET definition = EXCLUDED.definition, updated_at = now()
RETURNING remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
`

type RemoteAppAttributeDefUpsertParams struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
}

type RemoteAppAttributeDefUpsertRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// Attribute definition registry (#75): REFERENCE-mode opaque definitions.
func (q *Queries) RemoteAppAttributeDefUpsert(ctx context.Context, arg RemoteAppAttributeDefUpsertParams) (RemoteAppAttributeDefUpsertRow, error) {
	row := q.db.QueryRow(ctx, remoteAppAttributeDefUpsert,
		arg.RemoteApplicationID,
		arg.Key,
		arg.Version,
		arg.Definition,
	)
	var i RemoteAppAttributeDefUpsertRow
	err := row.Scan(
		&i.RemoteApplicationID,
		&i.Key,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteAppAttributeDefsList = `-- name: RemoteAppAttributeDefsList :many
SELECT remote_application_id::text AS remote_application_id, key, version, definition, created_at, updated_at
FROM profiles.remote_application_attribute_defs
WHERE remote_application_id = $1::uuid
ORDER BY key ASC, version DESC
`

type RemoteAppAttributeDefsListRow struct {
	RemoteApplicationID string
	Key                 string
	Version             int32
	Definition          []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RemoteAppAttributeDefsList(ctx context.Context, remoteApplicationID string) ([]RemoteAppAttributeDefsListRow, error) {
	rows, err := q.db.Query(ctx, remoteAppAttributeDefsList, remoteApplicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteAppAttributeDefsListRow
	for rows.Next() {
		var i RemoteAppAttributeDefsListRow
		if err := rows.Scan(
			&i.RemoteApplicationID,
			&i.Key,
			&i.Version,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const remoteApplicationByIssuer = `-- name: RemoteApplicationByIssuer :one
SELECT id::text, slug, COALESCE(owner_user_id::text, '')::text AS owner_user_id, COALESCE(tenant_id::text, '')::text AS tenant_id, issuer, jwks_uri, mode, public_keys, audiences, enabled, created_at, updated_at
FROM profiles.remote_applications
WHERE issuer = $1 AND deleted_at IS NULL
`

type RemoteApplicationByIssuerRow struct {
	ID          string
	Slug        string
	OwnerUserID string
	TenantID    string
	Issuer      string
	JwksUri     string
	Mode        string
	PublicKeys  []byte
	Audiences   []string
	Enabled     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) RemoteApplicationByIssuer(ctx context.Context, issuer string) (RemoteApplicationByIssuerRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationByIssuer, issuer)
	var i RemoteApplicationByIssuerRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.TenantID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Audiences,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationBySlug = `-- name: RemoteApplicationBySlug :one
SELECT id::text, slug, COALESCE(owner_user_id::text, '')::text AS owner_user_id, COALESCE(tenant_id::text, '')::text AS tenant_id, issuer, jwks_uri, mode, public_keys, audiences, enabled, created_at, updated_at
FROM profiles.remote_applications
WHERE slug = $1 AND deleted_at IS NULL
`

type RemoteApplicationBySlugRow struct {
	ID          string
	Slug        string
	OwnerUserID string
	TenantID    string
	Issuer      string
	JwksUri     string
	Mode        string
	PublicKeys  []byte
	Audiences   []string
	Enabled     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) RemoteApplicationBySlug(ctx context.Context, slug string) (RemoteApplicationBySlugRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationBySlug, slug)
	var i RemoteApplicationBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.TenantID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Audiences,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationDelete = `-- name: RemoteApplicationDelete :execrows
DELETE FROM profiles.remote_applications WHERE issuer = $1
`

func (q *Queries) RemoteApplicationDelete(ctx context.Context, issuer string) (int64, error) {
	result, err := q.db.Exec(ctx, remoteApplicationDelete, issuer)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const remoteApplicationUpsert = `-- name: RemoteApplicationUpsert :one

INSERT INTO profiles.remote_applications (slug, owner_user_id, tenant_id, issuer, jwks_uri, mode, public_keys, audiences, enabled)
VALUES ($1, $2::uuid, $3::uuid, $4, $5, $6, $7, $8, $9)
ON CONFLICT (issuer) DO UPDATE
  SET slug          = EXCLUDED.slug,
      owner_user_id = EXCLUDED.owner_user_id,
      tenant_id     = EXCLUDED.tenant_id,
      jwks_uri      = EXCLUDED.jwks_uri,
      mode          = EXCLUDED.mode,
      public_keys   = EXCLUDED.public_keys,
      audiences     = EXCLUDED.audiences,
      enabled       = EXCLUDED.enabled,
      updated_at    = now()
RETURNING id::text, slug, COALESCE(owner_user_id::text, '')::text AS owner_user_id, COALESCE(tenant_id::text, '')::text AS tenant_id, issuer, jwks_uri, mode, public_keys, audiences, enabled, created_at, updated_at
`

type RemoteApplicationUpsertParams struct {
	Slug        string
	OwnerUserID *string
	TenantID    *string
	Issuer      string
	JwksUri     string
	Mode        string
	PublicKeys  []byte
	Audiences   []string
	Enabled     bool
}

type RemoteApplicationUpsertRow struct {
	ID          string
	Slug        string
	OwnerUserID string
	TenantID    string
	Issuer      string
	JwksUri     string
	Mode        string
	PublicKeys  []byte
	Audiences   []string
	Enabled     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Remote application registry (core/service_remote_applications.go). A
// remote_application is the federation PRINCIPAL: it authenticates by signing
// JWTs verified against its JWKS/public keys (#74).
func (q *Queries) RemoteApplicationUpsert(ctx context.Context, arg RemoteApplicationUpsertParams) (RemoteApplicationUpsertRow, error) {
	row := q.db.QueryRow(ctx, remoteApplicationUpsert,
		arg.Slug,
		arg.OwnerUserID,
		arg.TenantID,
		arg.Issuer,
		arg.JwksUri,
		arg.Mode,
		arg.PublicKeys,
		arg.Audiences,
		arg.Enabled,
	)
	var i RemoteApplicationUpsertRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.TenantID,
		&i.Issuer,
		&i.JwksUri,
		&i.Mode,
		&i.PublicKeys,
		&i.Audiences,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const remoteApplicationsAll = `-- name: RemoteApplicationsAll :many
SELECT id::text, slug, COALESCE(owner_user_id::text, '')::text AS owner_user_id, COALESCE(tenant_id::text, '')::text AS tenant_id, issuer, jwks_uri, mode, public_keys, audiences, enabled, created_at, updated_at
FROM profiles.remote_applications
WHERE deleted_at IS NULL
ORDER BY slug ASC
`

type RemoteApplicationsAllRow struct {
	ID          string
	Slug        string
	OwnerUserID string
	TenantID    string
	Issuer      string
	JwksUri     string
	Mode        string
	PublicKeys  []byte
	Audiences   []string
	Enabled     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) RemoteApplicationsAll(ctx context.Context) ([]RemoteApplicationsAllRow, error) {
	rows, err := q.db.Query(ctx, remoteApplicationsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteApplicationsAllRow
	for rows.Next() {
		var i RemoteApplicationsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OwnerUserID,
			&i.TenantID,
			&i.Issuer,
			&i.JwksUri,
			&i.Mode,
			&i.PublicKeys,
			&i.Audiences,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const remoteApplicationsEnabled = `-- name: RemoteApplicationsEnabled :many
SELECT id::text, slug, COALESCE(owner_user_id::text, '')::text AS owner_user_id, COALESCE(tenant_id::text, '')::text AS tenant_id, issuer, jwks_uri, mode, public_keys, audiences, enabled, created_at, updated_at
FROM profiles.remote_applications
WHERE enabled = true AND deleted_at IS NULL
ORDER BY slug ASC
`

type RemoteApplicationsEnabledRow struct {
	ID          string
	Slug        string
	OwnerUserID string
	TenantID    string
	Issuer      string
	JwksUri     string
	Mode        string
	PublicKeys  []byte
	Audiences   []string
	Enabled     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) RemoteApplicationsEnabled(ctx context.Context) ([]RemoteApplicationsEnabledRow, error) {
	rows, err := q.db.Query(ctx, remoteApplicationsEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteApplicationsEnabledRow
	for rows.Next() {
		var i RemoteApplicationsEnabledRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OwnerUserID,
			&i.TenantID,
			&i.Issuer,
			&i.JwksUri,
			&i.Mode,
			&i.PublicKeys,
			&i.Audiences,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantBySlug = `-- name: TenantBySlug :one

SELECT id::text, slug, is_personal, COALESCE(owner_user_id::text, '')::text AS owner_user_id
FROM profiles.tenants
WHERE slug = $1 AND deleted_at IS NULL
`

type TenantBySlugRow struct {
	ID          string
	Slug        string
	IsPersonal  bool
	OwnerUserID string
}

// Tenant + membership + role queries (core/service_tenants.go).
func (q *Queries) TenantBySlug(ctx context.Context, slug string) (TenantBySlugRow, error) {
	row := q.db.QueryRow(ctx, tenantBySlug, slug)
	var i TenantBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.IsPersonal,
		&i.OwnerUserID,
	)
	return i, err
}

const tenantBySlugViaRename = `-- name: TenantBySlugViaRename :one
SELECT o.id::text AS id, o.slug, o.is_personal, COALESCE(o.owner_user_id::text, '')::text AS owner_user_id
FROM profiles.tenant_renames r
JOIN profiles.tenants o ON o.id = r.tenant_id AND o.deleted_at IS NULL
WHERE r.from_slug = $1
ORDER BY r.renamed_at DESC
LIMIT 1
`

type TenantBySlugViaRenameRow struct {
	ID          string
	Slug        string
	IsPersonal  bool
	OwnerUserID string
}

// TenantBySlugViaRename resolves a historical slug (issue #58). The
// tenant_renames row's tenant_id always points at the live owner, so any
// historical slug resolves to the tenant currently holding it; most recent
// row wins (hard-delete + reuse).
func (q *Queries) TenantBySlugViaRename(ctx context.Context, fromSlug string) (TenantBySlugViaRenameRow, error) {
	row := q.db.QueryRow(ctx, tenantBySlugViaRename, fromSlug)
	var i TenantBySlugViaRenameRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.IsPersonal,
		&i.OwnerUserID,
	)
	return i, err
}

const tenantDefinedRoles = `-- name: TenantDefinedRoles :many
SELECT role
FROM profiles.tenant_roles
WHERE tenant_id = $1::uuid
ORDER BY role ASC
`

func (q *Queries) TenantDefinedRoles(ctx context.Context, tenantID string) ([]string, error) {
	rows, err := q.db.Query(ctx, tenantDefinedRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantInsert = `-- name: TenantInsert :one
INSERT INTO profiles.tenants (id, slug, metadata)
VALUES ($1::uuid, $2, jsonb_build_object('namespace_state', 'registered_tenant', 'reserved', to_jsonb(false)))
RETURNING id::text, slug
`

type TenantInsertParams struct {
	ID   string
	Slug string
}

type TenantInsertRow struct {
	ID   string
	Slug string
}

func (q *Queries) TenantInsert(ctx context.Context, arg TenantInsertParams) (TenantInsertRow, error) {
	row := q.db.QueryRow(ctx, tenantInsert, arg.ID, arg.Slug)
	var i TenantInsertRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const tenantLastRenamedAt = `-- name: TenantLastRenamedAt :one
SELECT renamed_at
FROM   profiles.tenant_renames
WHERE  tenant_id = $1::uuid
ORDER  BY renamed_at DESC
LIMIT  1
`

func (q *Queries) TenantLastRenamedAt(ctx context.Context, tenantID string) (time.Time, error) {
	row := q.db.QueryRow(ctx, tenantLastRenamedAt, tenantID)
	var renamed_at time.Time
	err := row.Scan(&renamed_at)
	return renamed_at, err
}

const tenantMemberAdd = `-- name: TenantMemberAdd :exec
INSERT INTO profiles.tenant_memberships (tenant_id, member_id, member_kind, role)
VALUES ($1::uuid, $2::uuid, 'user', 'member')
ON CONFLICT (tenant_id, member_id, member_kind) DO UPDATE SET deleted_at = NULL, updated_at = now()
`

type TenantMemberAddParams struct {
	TenantID string
	UserID   string
}

// TenantMemberAdd intentionally does NOT change role on conflict (re-adding
// an existing member only revives a soft-deleted row).
func (q *Queries) TenantMemberAdd(ctx context.Context, arg TenantMemberAddParams) error {
	_, err := q.db.Exec(ctx, tenantMemberAdd, arg.TenantID, arg.UserID)
	return err
}

const tenantMemberHasRole = `-- name: TenantMemberHasRole :one
SELECT EXISTS (
  SELECT 1
  FROM profiles.tenant_memberships
  WHERE tenant_id = $1::uuid AND member_id = $2::uuid AND member_kind = 'user' AND role = $3 AND deleted_at IS NULL
)
`

type TenantMemberHasRoleParams struct {
	TenantID string
	UserID   string
	Role     string
}

func (q *Queries) TenantMemberHasRole(ctx context.Context, arg TenantMemberHasRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, tenantMemberHasRole, arg.TenantID, arg.UserID, arg.Role)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const tenantMemberIDs = `-- name: TenantMemberIDs :many
SELECT member_id::text
FROM profiles.tenant_memberships
WHERE tenant_id = $1::uuid AND member_kind = 'user' AND deleted_at IS NULL
ORDER BY member_id::text ASC
`

func (q *Queries) TenantMemberIDs(ctx context.Context, tenantID string) ([]string, error) {
	rows, err := q.db.Query(ctx, tenantMemberIDs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var member_id string
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantMemberRole = `-- name: TenantMemberRole :one
SELECT role
FROM profiles.tenant_memberships
WHERE tenant_id = $1::uuid AND member_id = $2::uuid AND member_kind = 'user' AND deleted_at IS NULL
`

type TenantMemberRoleParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) TenantMemberRole(ctx context.Context, arg TenantMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, tenantMemberRole, arg.TenantID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const tenantMemberRolePrincipal = `-- name: TenantMemberRolePrincipal :one
SELECT role
FROM profiles.tenant_memberships
WHERE tenant_id = $1::uuid AND member_id = $2::uuid AND member_kind = $3 AND deleted_at IS NULL
`

type TenantMemberRolePrincipalParams struct {
	TenantID   string
	MemberID   string
	MemberKind string
}

func (q *Queries) TenantMemberRolePrincipal(ctx context.Context, arg TenantMemberRolePrincipalParams) (string, error) {
	row := q.db.QueryRow(ctx, tenantMemberRolePrincipal, arg.TenantID, arg.MemberID, arg.MemberKind)
	var role string
	err := row.Scan(&role)
	return role, err
}

const tenantMemberSoftDelete = `-- name: TenantMemberSoftDelete :exec
UPDATE profiles.tenant_memberships SET deleted_at = now(), updated_at = now()
WHERE tenant_id = $1::uuid AND member_id = $2::uuid AND member_kind = 'user' AND deleted_at IS NULL
`

type TenantMemberSoftDeleteParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) TenantMemberSoftDelete(ctx context.Context, arg TenantMemberSoftDeleteParams) error {
	_, err := q.db.Exec(ctx, tenantMemberSoftDelete, arg.TenantID, arg.UserID)
	return err
}

const tenantMemberSoftDeletePrincipal = `-- name: TenantMemberSoftDeletePrincipal :exec
UPDATE profiles.tenant_memberships SET deleted_at = now(), updated_at = now()
WHERE tenant_id = $1::uuid AND member_id = $2::uuid AND member_kind = $3 AND deleted_at IS NULL
`

type TenantMemberSoftDeletePrincipalParams struct {
	TenantID   string
	MemberID   string
	MemberKind string
}

func (q *Queries) TenantMemberSoftDeletePrincipal(ctx context.Context, arg TenantMemberSoftDeletePrincipalParams) error {
	_, err := q.db.Exec(ctx, tenantMemberSoftDeletePrincipal, arg.TenantID, arg.MemberID, arg.MemberKind)
	return err
}

const tenantMembershipExists = `-- name: TenantMembershipExists :one
SELECT EXISTS (
  SELECT 1 FROM profiles.tenant_memberships
  WHERE tenant_id = $1::uuid AND member_id = $2::uuid AND member_kind = 'user' AND deleted_at IS NULL
)
`

type TenantMembershipExistsParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) TenantMembershipExists(ctx context.Context, arg TenantMembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tenantMembershipExists, arg.TenantID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const tenantMembershipResetRole = `-- name: TenantMembershipResetRole :exec
UPDATE profiles.tenant_memberships
SET role = 'member', updated_at = now()
WHERE tenant_id = $1::uuid AND member_id = $2::uuid AND member_kind = 'user' AND role = $3 AND deleted_at IS NULL
`

type TenantMembershipResetRoleParams struct {
	TenantID string
	UserID   string
	Role     string
}

func (q *Queries) TenantMembershipResetRole(ctx context.Context, arg TenantMembershipResetRoleParams) error {
	_, err := q.db.Exec(ctx, tenantMembershipResetRole, arg.TenantID, arg.UserID, arg.Role)
	return err
}

const tenantMembershipSetRole = `-- name: TenantMembershipSetRole :exec
UPDATE profiles.tenant_memberships
SET role = $1, updated_at = now()
WHERE tenant_id = $2::uuid
  AND member_id = $3::uuid
  AND member_kind = 'user'
  AND deleted_at IS NULL
  AND EXISTS (SELECT 1 FROM profiles.tenant_roles WHERE tenant_id = $2::uuid AND role = $1)
`

type TenantMembershipSetRoleParams struct {
	Role     string
	TenantID string
	UserID   string
}

func (q *Queries) TenantMembershipSetRole(ctx context.Context, arg TenantMembershipSetRoleParams) error {
	_, err := q.db.Exec(ctx, tenantMembershipSetRole, arg.Role, arg.TenantID, arg.UserID)
	return err
}

const tenantMembershipUpsertRole = `-- name: TenantMembershipUpsertRole :exec
INSERT INTO profiles.tenant_memberships (tenant_id, member_id, member_kind, role)
VALUES ($1::uuid, $2::uuid, 'user', $3)
ON CONFLICT (tenant_id, member_id, member_kind)
DO UPDATE SET role = EXCLUDED.role, deleted_at = NULL, updated_at = now()
`

type TenantMembershipUpsertRoleParams struct {
	TenantID string
	UserID   string
	Role     string
}

func (q *Queries) TenantMembershipUpsertRole(ctx context.Context, arg TenantMembershipUpsertRoleParams) error {
	_, err := q.db.Exec(ctx, tenantMembershipUpsertRole, arg.TenantID, arg.UserID, arg.Role)
	return err
}

const tenantMembershipUpsertRolePrincipal = `-- name: TenantMembershipUpsertRolePrincipal :exec

INSERT INTO profiles.tenant_memberships (tenant_id, member_id, member_kind, role)
VALUES ($1::uuid, $2::uuid, $3, $4)
ON CONFLICT (tenant_id, member_id, member_kind)
DO UPDATE SET role = EXCLUDED.role, deleted_at = NULL, updated_at = now()
`

type TenantMembershipUpsertRolePrincipalParams struct {
	TenantID   string
	MemberID   string
	MemberKind string
	Role       string
}

// Polymorphic remote_application memberships: a remote_app holds tenant roles
// via the SAME tenant_memberships/tenant_roles machinery as users (#74).
func (q *Queries) TenantMembershipUpsertRolePrincipal(ctx context.Context, arg TenantMembershipUpsertRolePrincipalParams) error {
	_, err := q.db.Exec(ctx, tenantMembershipUpsertRolePrincipal,
		arg.TenantID,
		arg.MemberID,
		arg.MemberKind,
		arg.Role,
	)
	return err
}

const tenantRenameInsert = `-- name: TenantRenameInsert :exec
INSERT INTO profiles.tenant_renames (tenant_id, from_slug)
VALUES ($1::uuid, $2)
`

type TenantRenameInsertParams struct {
	TenantID string
	FromSlug string
}

func (q *Queries) TenantRenameInsert(ctx context.Context, arg TenantRenameInsertParams) error {
	_, err := q.db.Exec(ctx, tenantRenameInsert, arg.TenantID, arg.FromSlug)
	return err
}

const tenantRoleDefine = `-- name: TenantRoleDefine :exec
INSERT INTO profiles.tenant_roles (tenant_id, role)
VALUES ($1::uuid, $2)
ON CONFLICT (tenant_id, role) DO NOTHING
`

type TenantRoleDefineParams struct {
	TenantID string
	Role     string
}

func (q *Queries) TenantRoleDefine(ctx context.Context, arg TenantRoleDefineParams) error {
	_, err := q.db.Exec(ctx, tenantRoleDefine, arg.TenantID, arg.Role)
	return err
}

const tenantRoleDelete = `-- name: TenantRoleDelete :exec
DELETE FROM profiles.tenant_roles
WHERE tenant_id = $1::uuid AND role = $2
`

type TenantRoleDeleteParams struct {
	TenantID string
	Role     string
}

func (q *Queries) TenantRoleDelete(ctx context.Context, arg TenantRoleDeleteParams) error {
	_, err := q.db.Exec(ctx, tenantRoleDelete, arg.TenantID, arg.Role)
	return err
}

const tenantRoleExists = `-- name: TenantRoleExists :one
SELECT EXISTS(SELECT 1 FROM profiles.tenant_roles WHERE tenant_id = $1::uuid AND role = $2)
`

type TenantRoleExistsParams struct {
	TenantID string
	Role     string
}

func (q *Queries) TenantRoleExists(ctx context.Context, arg TenantRoleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tenantRoleExists, arg.TenantID, arg.Role)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const tenantRoleHasPermissions = `-- name: TenantRoleHasPermissions :one
SELECT EXISTS(SELECT 1 FROM profiles.tenant_role_permissions WHERE tenant_id = $1::uuid AND role = $2)
`

type TenantRoleHasPermissionsParams struct {
	TenantID string
	Role     string
}

func (q *Queries) TenantRoleHasPermissions(ctx context.Context, arg TenantRoleHasPermissionsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tenantRoleHasPermissions, arg.TenantID, arg.Role)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const tenantRoleMemberCount = `-- name: TenantRoleMemberCount :one
SELECT COUNT(*)
FROM profiles.tenant_memberships
WHERE tenant_id = $1::uuid AND role = $2 AND deleted_at IS NULL
`

type TenantRoleMemberCountParams struct {
	TenantID string
	Role     string
}

func (q *Queries) TenantRoleMemberCount(ctx context.Context, arg TenantRoleMemberCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, tenantRoleMemberCount, arg.TenantID, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const tenantRolePermissionInsert = `-- name: TenantRolePermissionInsert :exec
INSERT INTO profiles.tenant_role_permissions (tenant_id, role, permission)
VALUES ($1::uuid, $2, $3)
ON CONFLICT DO NOTHING
`

type TenantRolePermissionInsertParams struct {
	TenantID   string
	Role       string
	Permission string
}

func (q *Queries) TenantRolePermissionInsert(ctx context.Context, arg TenantRolePermissionInsertParams) error {
	_, err := q.db.Exec(ctx, tenantRolePermissionInsert, arg.TenantID, arg.Role, arg.Permission)
	return err
}

const tenantRolePermissions = `-- name: TenantRolePermissions :many

SELECT permission FROM profiles.tenant_role_permissions
WHERE tenant_id = $1::uuid AND role = $2
ORDER BY permission ASC
`

type TenantRolePermissionsParams struct {
	TenantID string
	Role     string
}

// Tenant RBAC role-permission queries (core/tenant_role_permissions.go).
func (q *Queries) TenantRolePermissions(ctx context.Context, arg TenantRolePermissionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, tenantRolePermissions, arg.TenantID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantRolePermissionsDelete = `-- name: TenantRolePermissionsDelete :exec
DELETE FROM profiles.tenant_role_permissions
WHERE tenant_id = $1::uuid AND role = $2
`

type TenantRolePermissionsDeleteParams struct {
	TenantID string
	Role     string
}

func (q *Queries) TenantRolePermissionsDelete(ctx context.Context, arg TenantRolePermissionsDeleteParams) error {
	_, err := q.db.Exec(ctx, tenantRolePermissionsDelete, arg.TenantID, arg.Role)
	return err
}

const tenantRolesForPrincipal = `-- name: TenantRolesForPrincipal :many
SELECT o.slug, m.role
FROM profiles.tenant_memberships m
JOIN profiles.tenants o ON o.id = m.tenant_id AND o.deleted_at IS NULL
WHERE m.member_id = $1::uuid AND m.member_kind = $2 AND m.deleted_at IS NULL
ORDER BY o.slug ASC, m.role ASC
`

type TenantRolesForPrincipalParams struct {
	MemberID   string
	MemberKind string
}

type TenantRolesForPrincipalRow struct {
	Slug string
	Role string
}

func (q *Queries) TenantRolesForPrincipal(ctx context.Context, arg TenantRolesForPrincipalParams) ([]TenantRolesForPrincipalRow, error) {
	rows, err := q.db.Query(ctx, tenantRolesForPrincipal, arg.MemberID, arg.MemberKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantRolesForPrincipalRow
	for rows.Next() {
		var i TenantRolesForPrincipalRow
		if err := rows.Scan(&i.Slug, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantRolesSeedOwnerMember = `-- name: TenantRolesSeedOwnerMember :exec
INSERT INTO profiles.tenant_roles (tenant_id, role)
VALUES ($1::uuid, $2), ($1::uuid, $3)
ON CONFLICT (tenant_id, role) DO NOTHING
`

type TenantRolesSeedOwnerMemberParams struct {
	TenantID   string
	OwnerRole  string
	MemberRole string
}

func (q *Queries) TenantRolesSeedOwnerMember(ctx context.Context, arg TenantRolesSeedOwnerMemberParams) error {
	_, err := q.db.Exec(ctx, tenantRolesSeedOwnerMember, arg.TenantID, arg.OwnerRole, arg.MemberRole)
	return err
}

const tenantSlugAndPersonalByID = `-- name: TenantSlugAndPersonalByID :one
SELECT slug, is_personal FROM profiles.tenants
WHERE id = $1::uuid AND deleted_at IS NULL
`

type TenantSlugAndPersonalByIDRow struct {
	Slug       string
	IsPersonal bool
}

func (q *Queries) TenantSlugAndPersonalByID(ctx context.Context, id string) (TenantSlugAndPersonalByIDRow, error) {
	row := q.db.QueryRow(ctx, tenantSlugAndPersonalByID, id)
	var i TenantSlugAndPersonalByIDRow
	err := row.Scan(&i.Slug, &i.IsPersonal)
	return i, err
}

const tenantSlugsByUser = `-- name: TenantSlugsByUser :many
SELECT o.slug
FROM profiles.tenant_memberships m
JOIN profiles.tenants o ON o.id = m.tenant_id
WHERE m.member_id = $1::uuid AND m.member_kind = 'user' AND m.deleted_at IS NULL AND o.deleted_at IS NULL
ORDER BY o.slug ASC
`

func (q *Queries) TenantSlugsByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, tenantSlugsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantUpdateSlug = `-- name: TenantUpdateSlug :exec
UPDATE profiles.tenants SET slug = $1, updated_at = now()
WHERE id = $2::uuid AND deleted_at IS NULL
`

type TenantUpdateSlugParams struct {
	Slug string
	ID   string
}

func (q *Queries) TenantUpdateSlug(ctx context.Context, arg TenantUpdateSlugParams) error {
	_, err := q.db.Exec(ctx, tenantUpdateSlug, arg.Slug, arg.ID)
	return err
}
