// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: twofactor.sql

package db

import (
	"context"
)

const twoFactorDisable = `-- name: TwoFactorDisable :exec
UPDATE profiles.two_factor_settings
SET enabled = false, updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) TwoFactorDisable(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, twoFactorDisable, userID)
	return err
}

const twoFactorEnable = `-- name: TwoFactorEnable :exec

INSERT INTO profiles.two_factor_settings (user_id, enabled, method, phone_number, backup_codes, updated_at)
VALUES ($1, true, $2, $3, $4, NOW())
ON CONFLICT (user_id) DO UPDATE SET
  enabled = true,
  method = EXCLUDED.method,
  phone_number = EXCLUDED.phone_number,
  backup_codes = EXCLUDED.backup_codes,
  updated_at = NOW()
`

type TwoFactorEnableParams struct {
	UserID      string
	Method      string
	PhoneNumber *string
	BackupCodes []string
}

// Two-factor settings queries (core/service.go).
func (q *Queries) TwoFactorEnable(ctx context.Context, arg TwoFactorEnableParams) error {
	_, err := q.db.Exec(ctx, twoFactorEnable,
		arg.UserID,
		arg.Method,
		arg.PhoneNumber,
		arg.BackupCodes,
	)
	return err
}

const twoFactorSetBackupCodes = `-- name: TwoFactorSetBackupCodes :exec
UPDATE profiles.two_factor_settings
SET backup_codes = $1, updated_at = NOW()
WHERE user_id = $2
`

type TwoFactorSetBackupCodesParams struct {
	BackupCodes []string
	UserID      string
}

func (q *Queries) TwoFactorSetBackupCodes(ctx context.Context, arg TwoFactorSetBackupCodesParams) error {
	_, err := q.db.Exec(ctx, twoFactorSetBackupCodes, arg.BackupCodes, arg.UserID)
	return err
}

const twoFactorSettingsByUser = `-- name: TwoFactorSettingsByUser :one
SELECT user_id, enabled, method, phone_number, backup_codes, created_at, updated_at
FROM profiles.two_factor_settings
WHERE user_id = $1
`

func (q *Queries) TwoFactorSettingsByUser(ctx context.Context, userID string) (ProfilesTwoFactorSetting, error) {
	row := q.db.QueryRow(ctx, twoFactorSettingsByUser, userID)
	var i ProfilesTwoFactorSetting
	err := row.Scan(
		&i.UserID,
		&i.Enabled,
		&i.Method,
		&i.PhoneNumber,
		&i.BackupCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
