// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const accountDeletionPurgeNow = `-- name: AccountDeletionPurgeNow :one
UPDATE account_deletions SET purge_at = statement_timestamp()
WHERE user_id = $1 AND state = 'deleted'
RETURNING id, user_id, deleted_at, purge_at
`

type AccountDeletionPurgeNowRow struct {
	ID        string
	UserID    string
	DeletedAt time.Time
	PurgeAt   time.Time
}

// Closes the recovery window of a deleted account now.
func (q *Queries) AccountDeletionPurgeNow(ctx context.Context, userID string) (AccountDeletionPurgeNowRow, error) {
	row := q.db.QueryRow(ctx, accountDeletionPurgeNow, userID)
	var i AccountDeletionPurgeNowRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeletedAt,
		&i.PurgeAt,
	)
	return i, err
}

const accountDeletionSetDeletedBy = `-- name: AccountDeletionSetDeletedBy :exec
UPDATE account_deletions SET deleted_by = $1::uuid WHERE user_id = $2 AND state = 'deleted'
`

type AccountDeletionSetDeletedByParams struct {
	DeletedBy *string
	UserID    string
}

// Records who deleted an account that is already deleted.
func (q *Queries) AccountDeletionSetDeletedBy(ctx context.Context, arg AccountDeletionSetDeletedByParams) error {
	_, err := q.db.Exec(ctx, accountDeletionSetDeletedBy, arg.DeletedBy, arg.UserID)
	return err
}

const contactState = `-- name: ContactState :one
SELECT ((email IS NOT NULL OR phone_number IS NOT NULL)
        AND NOT ((email IS NOT NULL AND email_verified) OR (phone_number IS NOT NULL AND phone_verified)))::boolean AS unproven,
       COALESCE(email::text, phone_number, '')::text AS identifier,
       (CASE WHEN email IS NOT NULL THEN 'email' ELSE 'phone' END)::text AS channel
FROM users WHERE id = $1
`

type ContactStateRow struct {
	Unproven   bool
	Identifier string
	Channel    string
}

// An account is unproven when it has an address and none is verified.
func (q *Queries) ContactState(ctx context.Context, id string) (ContactStateRow, error) {
	row := q.db.QueryRow(ctx, contactState, id)
	var i ContactStateRow
	err := row.Scan(&i.Unproven, &i.Identifier, &i.Channel)
	return i, err
}

const contactStateForUpdate = `-- name: ContactStateForUpdate :one
SELECT ((email IS NOT NULL OR phone_number IS NOT NULL)
        AND NOT ((email IS NOT NULL AND email_verified) OR (phone_number IS NOT NULL AND phone_verified)))::boolean AS unproven,
       COALESCE(email::text, phone_number, '')::text AS identifier,
       (CASE WHEN email IS NOT NULL THEN 'email' ELSE 'phone' END)::text AS channel
FROM users WHERE id = $1 FOR UPDATE
`

type ContactStateForUpdateRow struct {
	Unproven   bool
	Identifier string
	Channel    string
}

func (q *Queries) ContactStateForUpdate(ctx context.Context, id string) (ContactStateForUpdateRow, error) {
	row := q.db.QueryRow(ctx, contactStateForUpdate, id)
	var i ContactStateForUpdateRow
	err := row.Scan(&i.Unproven, &i.Identifier, &i.Channel)
	return i, err
}

const mFASettingsDelete = `-- name: MFASettingsDelete :exec
DELETE FROM mfa_settings WHERE user_id = $1
`

func (q *Queries) MFASettingsDelete(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, mFASettingsDelete, userID)
	return err
}

const userAdvanceCredentialVersion = `-- name: UserAdvanceCredentialVersion :exec
UPDATE users SET credential_version = credential_version + 1 WHERE id = $1
`

func (q *Queries) UserAdvanceCredentialVersion(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, userAdvanceCredentialVersion, id)
	return err
}

const userApplyEmailChange = `-- name: UserApplyEmailChange :exec
UPDATE users SET email = lower($2::text), email_verified = true, updated_at = NOW() WHERE id = $1
`

type UserApplyEmailChangeParams struct {
	ID    string
	Email string
}

func (q *Queries) UserApplyEmailChange(ctx context.Context, arg UserApplyEmailChangeParams) error {
	_, err := q.db.Exec(ctx, userApplyEmailChange, arg.ID, arg.Email)
	return err
}

const userApplyPhoneChange = `-- name: UserApplyPhoneChange :exec
UPDATE users SET phone_number = $2, phone_verified = true, updated_at = NOW() WHERE id = $1
`

type UserApplyPhoneChangeParams struct {
	ID          string
	PhoneNumber *string
}

func (q *Queries) UserApplyPhoneChange(ctx context.Context, arg UserApplyPhoneChangeParams) error {
	_, err := q.db.Exec(ctx, userApplyPhoneChange, arg.ID, arg.PhoneNumber)
	return err
}

const userBan = `-- name: UserBan :exec
UPDATE users
SET banned_at = $1, banned_until = $2, ban_reason = $3, banned_by = $4, updated_at = NOW()
WHERE id = $5
`

type UserBanParams struct {
	BannedAt    *time.Time
	BannedUntil *time.Time
	BanReason   *string
	BannedBy    *string
	ID          string
}

func (q *Queries) UserBan(ctx context.Context, arg UserBanParams) error {
	_, err := q.db.Exec(ctx, userBan,
		arg.BannedAt,
		arg.BannedUntil,
		arg.BanReason,
		arg.BannedBy,
		arg.ID,
	)
	return err
}

const userBanInForce = `-- name: UserBanInForce :one
SELECT ban_in_force(banned_at, banned_until)::boolean AS in_force
FROM users WHERE id = $1
`

func (q *Queries) UserBanInForce(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, userBanInForce, id)
	var in_force bool
	err := row.Scan(&in_force)
	return in_force, err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, username, email_verified, phone_number, phone_verified, banned_at, banned_until, ban_reason, banned_by, deleted_at, metadata, created_at, updated_at, last_login, preferred_language, avatar_url, last_renamed_at, credential_version FROM users WHERE email = lower($1::text)::public.citext
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.EmailVerified,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.BannedAt,
		&i.BannedUntil,
		&i.BanReason,
		&i.BannedBy,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.PreferredLanguage,
		&i.AvatarURL,
		&i.LastRenamedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const userByID = `-- name: UserByID :one

SELECT id, email, username, email_verified, phone_number, phone_verified, banned_at, banned_until, ban_reason, banned_by, deleted_at, metadata, created_at, updated_at, last_login, preferred_language, avatar_url, last_renamed_at, credential_version FROM users WHERE id = $1
`

// User-row queries. A user read selects the whole row, so every read returns
// db.User: the engine's one user type.
func (q *Queries) UserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.EmailVerified,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.BannedAt,
		&i.BannedUntil,
		&i.BanReason,
		&i.BannedBy,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.PreferredLanguage,
		&i.AvatarURL,
		&i.LastRenamedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const userByPhone = `-- name: UserByPhone :one
SELECT id, email, username, email_verified, phone_number, phone_verified, banned_at, banned_until, ban_reason, banned_by, deleted_at, metadata, created_at, updated_at, last_login, preferred_language, avatar_url, last_renamed_at, credential_version FROM users WHERE phone_number = $1
`

func (q *Queries) UserByPhone(ctx context.Context, phoneNumber *string) (User, error) {
	row := q.db.QueryRow(ctx, userByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.EmailVerified,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.BannedAt,
		&i.BannedUntil,
		&i.BanReason,
		&i.BannedBy,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.PreferredLanguage,
		&i.AvatarURL,
		&i.LastRenamedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const userByUsername = `-- name: UserByUsername :one
SELECT id, email, username, email_verified, phone_number, phone_verified, banned_at, banned_until, ban_reason, banned_by, deleted_at, metadata, created_at, updated_at, last_login, preferred_language, avatar_url, last_renamed_at, credential_version FROM users WHERE username = $1::text::public.citext
`

func (q *Queries) UserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, userByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.EmailVerified,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.BannedAt,
		&i.BannedUntil,
		&i.BanReason,
		&i.BannedBy,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.PreferredLanguage,
		&i.AvatarURL,
		&i.LastRenamedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const userClearBan = `-- name: UserClearBan :exec
UPDATE users SET banned_at = NULL, banned_until = NULL, ban_reason = NULL, banned_by = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) UserClearBan(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, userClearBan, id)
	return err
}

const userCredentialVersion = `-- name: UserCredentialVersion :one
SELECT credential_version, email, phone_number
FROM users WHERE id = $1
`

type UserCredentialVersionRow struct {
	CredentialVersion int64
	Email             *string
	PhoneNumber       *string
}

func (q *Queries) UserCredentialVersion(ctx context.Context, id string) (UserCredentialVersionRow, error) {
	row := q.db.QueryRow(ctx, userCredentialVersion, id)
	var i UserCredentialVersionRow
	err := row.Scan(&i.CredentialVersion, &i.Email, &i.PhoneNumber)
	return i, err
}

const userCredentialVersionForUpdate = `-- name: UserCredentialVersionForUpdate :one
SELECT credential_version, email, phone_number, deleted_at, banned_at, banned_until
FROM users WHERE id = $1 FOR UPDATE
`

type UserCredentialVersionForUpdateRow struct {
	CredentialVersion int64
	Email             *string
	PhoneNumber       *string
	DeletedAt         *time.Time
	BannedAt          *time.Time
	BannedUntil       *time.Time
}

// All credential changes acquire this account lock before credential/session rows.
func (q *Queries) UserCredentialVersionForUpdate(ctx context.Context, id string) (UserCredentialVersionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, userCredentialVersionForUpdate, id)
	var i UserCredentialVersionForUpdateRow
	err := row.Scan(
		&i.CredentialVersion,
		&i.Email,
		&i.PhoneNumber,
		&i.DeletedAt,
		&i.BannedAt,
		&i.BannedUntil,
	)
	return i, err
}

const userDeleteHard = `-- name: UserDeleteHard :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) UserDeleteHard(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, userDeleteHard, id)
	return err
}

const userEmailOrUsernameTaken = `-- name: UserEmailOrUsernameTaken :one
SELECT
  EXISTS(SELECT 1 FROM users WHERE email = lower($1::text)::public.citext)::boolean AS email_taken,
  EXISTS(SELECT 1 FROM name_claims WHERE owner_kind='user' AND persona='' AND name=lower($2::text) AND (canonical OR expires_at IS NULL OR expires_at>$3::timestamptz))::boolean AS username_taken
`

type UserEmailOrUsernameTakenParams struct {
	Email    string
	Username string
	AtTime   time.Time
}

type UserEmailOrUsernameTakenRow struct {
	EmailTaken    bool
	UsernameTaken bool
}

func (q *Queries) UserEmailOrUsernameTaken(ctx context.Context, arg UserEmailOrUsernameTakenParams) (UserEmailOrUsernameTakenRow, error) {
	row := q.db.QueryRow(ctx, userEmailOrUsernameTaken, arg.Email, arg.Username, arg.AtTime)
	var i UserEmailOrUsernameTakenRow
	err := row.Scan(&i.EmailTaken, &i.UsernameTaken)
	return i, err
}

const userImportInsert = `-- name: UserImportInsert :exec
WITH claim AS MATERIALIZED (
 SELECT claim_canonical_name('user','',$4::text,$1::uuid,$14::timestamptz)
)
INSERT INTO users (
  id, email, phone_number, username, email_verified, phone_verified,
  banned_at, banned_until, ban_reason, banned_by, metadata, created_at, updated_at
)
SELECT
  $1::uuid, $2, $3, $4, $5, $6,
  $7, $8, $9, $10::uuid, $11::jsonb, $12, $13
FROM claim
`

type UserImportInsertParams struct {
	ID            string
	Email         *string
	PhoneNumber   *string
	Username      *string
	EmailVerified bool
	PhoneVerified bool
	BannedAt      *time.Time
	BannedUntil   *time.Time
	BanReason     *string
	BannedBy      *string
	Metadata      []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
	AtTime        time.Time
}

func (q *Queries) UserImportInsert(ctx context.Context, arg UserImportInsertParams) error {
	_, err := q.db.Exec(ctx, userImportInsert,
		arg.ID,
		arg.Email,
		arg.PhoneNumber,
		arg.Username,
		arg.EmailVerified,
		arg.PhoneVerified,
		arg.BannedAt,
		arg.BannedUntil,
		arg.BanReason,
		arg.BannedBy,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.AtTime,
	)
	return err
}

const userImportUpdate = `-- name: UserImportUpdate :one
UPDATE users
SET email = COALESCE($1, email),
    phone_number = COALESCE($2, phone_number),
    username = $3,
    email_verified = $4,
    phone_verified = $5,
    banned_at = $6,
    banned_until = $7,
    ban_reason = $8,
    banned_by = $9::uuid,
    metadata = COALESCE(metadata, '{}'::jsonb) || $10::jsonb,
    created_at = CASE WHEN $11 < created_at THEN $11 ELSE created_at END,
    updated_at = $12
WHERE id = $13::uuid
RETURNING id::text
`

type UserImportUpdateParams struct {
	Email         *string
	PhoneNumber   *string
	Username      *string
	EmailVerified bool
	PhoneVerified bool
	BannedAt      *time.Time
	BannedUntil   *time.Time
	BanReason     *string
	BannedBy      *string
	Metadata      []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ID            string
}

func (q *Queries) UserImportUpdate(ctx context.Context, arg UserImportUpdateParams) (string, error) {
	row := q.db.QueryRow(ctx, userImportUpdate,
		arg.Email,
		arg.PhoneNumber,
		arg.Username,
		arg.EmailVerified,
		arg.PhoneVerified,
		arg.BannedAt,
		arg.BannedUntil,
		arg.BanReason,
		arg.BannedBy,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const userInsert = `-- name: UserInsert :one
WITH claim AS MATERIALIZED (
 SELECT claim_canonical_name('user','',$3::text,$1::uuid,$4::timestamptz)
)
INSERT INTO users (id, email, username)
SELECT $1::uuid, NULLIF(lower($2::text), ''), $3 FROM claim
RETURNING id, email, username, email_verified, phone_number, phone_verified, banned_at, banned_until, ban_reason, banned_by, deleted_at, metadata, created_at, updated_at, last_login, preferred_language, avatar_url, last_renamed_at, credential_version
`

type UserInsertParams struct {
	ID       string
	Email    string
	Username *string
	AtTime   time.Time
}

func (q *Queries) UserInsert(ctx context.Context, arg UserInsertParams) (User, error) {
	row := q.db.QueryRow(ctx, userInsert,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.AtTime,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.EmailVerified,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.BannedAt,
		&i.BannedUntil,
		&i.BanReason,
		&i.BannedBy,
		&i.DeletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
		&i.PreferredLanguage,
		&i.AvatarURL,
		&i.LastRenamedAt,
		&i.CredentialVersion,
	)
	return i, err
}

const userNameForUpdate = `-- name: UserNameForUpdate :one
SELECT username, last_renamed_at FROM users WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

type UserNameForUpdateRow struct {
	Username      *string
	LastRenamedAt *time.Time
}

func (q *Queries) UserNameForUpdate(ctx context.Context, id string) (UserNameForUpdateRow, error) {
	row := q.db.QueryRow(ctx, userNameForUpdate, id)
	var i UserNameForUpdateRow
	err := row.Scan(&i.Username, &i.LastRenamedAt)
	return i, err
}

const userPasswordDelete = `-- name: UserPasswordDelete :exec
DELETE FROM user_passwords WHERE user_id = $1
`

func (q *Queries) UserPasswordDelete(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, userPasswordDelete, userID)
	return err
}

const userPasswordInsert = `-- name: UserPasswordInsert :exec
INSERT INTO user_passwords (user_id, password_hash, hash_algo)
VALUES ($1, $2, 'argon2id')
`

type UserPasswordInsertParams struct {
	UserID       string
	PasswordHash string
}

func (q *Queries) UserPasswordInsert(ctx context.Context, arg UserPasswordInsertParams) error {
	_, err := q.db.Exec(ctx, userPasswordInsert, arg.UserID, arg.PasswordHash)
	return err
}

const userPasswordRehash = `-- name: UserPasswordRehash :exec
UPDATE user_passwords SET password_hash = $1, hash_algo = 'argon2id'
WHERE user_id = $2 AND password_hash = $3
`

type UserPasswordRehashParams struct {
	NewHash string
	UserID  string
	OldHash string
}

// Opportunistic rehash cannot overwrite a password changed after verification.
func (q *Queries) UserPasswordRehash(ctx context.Context, arg UserPasswordRehashParams) error {
	_, err := q.db.Exec(ctx, userPasswordRehash, arg.NewHash, arg.UserID, arg.OldHash)
	return err
}

const userPasswordRow = `-- name: UserPasswordRow :one
SELECT password_hash, hash_algo
FROM user_passwords WHERE user_id = $1
`

type UserPasswordRowRow struct {
	PasswordHash string
	HashAlgo     string
}

func (q *Queries) UserPasswordRow(ctx context.Context, userID string) (UserPasswordRowRow, error) {
	row := q.db.QueryRow(ctx, userPasswordRow, userID)
	var i UserPasswordRowRow
	err := row.Scan(&i.PasswordHash, &i.HashAlgo)
	return i, err
}

const userPasswordUpsert = `-- name: UserPasswordUpsert :exec
INSERT INTO user_passwords (user_id, password_hash, hash_algo)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET password_hash = EXCLUDED.password_hash, hash_algo = EXCLUDED.hash_algo, password_updated_at = NOW()
`

type UserPasswordUpsertParams struct {
	UserID       string
	PasswordHash string
	HashAlgo     string
}

func (q *Queries) UserPasswordUpsert(ctx context.Context, arg UserPasswordUpsertParams) error {
	_, err := q.db.Exec(ctx, userPasswordUpsert, arg.UserID, arg.PasswordHash, arg.HashAlgo)
	return err
}

const userPhoneOrUsernameTaken = `-- name: UserPhoneOrUsernameTaken :one
SELECT
  EXISTS(SELECT 1 FROM users WHERE phone_number = $1::text)::boolean AS phone_taken,
  EXISTS(SELECT 1 FROM name_claims WHERE owner_kind='user' AND persona='' AND name=lower($2::text) AND (canonical OR expires_at IS NULL OR expires_at>$3::timestamptz))::boolean AS username_taken
`

type UserPhoneOrUsernameTakenParams struct {
	Phone    string
	Username string
	AtTime   time.Time
}

type UserPhoneOrUsernameTakenRow struct {
	PhoneTaken    bool
	UsernameTaken bool
}

func (q *Queries) UserPhoneOrUsernameTaken(ctx context.Context, arg UserPhoneOrUsernameTakenParams) (UserPhoneOrUsernameTakenRow, error) {
	row := q.db.QueryRow(ctx, userPhoneOrUsernameTaken, arg.Phone, arg.Username, arg.AtTime)
	var i UserPhoneOrUsernameTakenRow
	err := row.Scan(&i.PhoneTaken, &i.UsernameTaken)
	return i, err
}

const userPreferredLanguage = `-- name: UserPreferredLanguage :one
SELECT COALESCE(preferred_language, '')::text AS language
FROM users
WHERE id = $1::uuid
`

func (q *Queries) UserPreferredLanguage(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, userPreferredLanguage, id)
	var language string
	err := row.Scan(&language)
	return language, err
}

const userRename = `-- name: UserRename :exec
UPDATE users SET username = $1, last_renamed_at = $2::timestamptz, updated_at = $2::timestamptz
WHERE id = $3
`

type UserRenameParams struct {
	Username *string
	AtTime   time.Time
	ID       string
}

func (q *Queries) UserRename(ctx context.Context, arg UserRenameParams) error {
	_, err := q.db.Exec(ctx, userRename, arg.Username, arg.AtTime, arg.ID)
	return err
}

const userSetAvatarURL = `-- name: UserSetAvatarURL :exec
UPDATE users SET avatar_url = $1, updated_at = now() WHERE id = $2
`

type UserSetAvatarURLParams struct {
	AvatarURL *string
	ID        string
}

func (q *Queries) UserSetAvatarURL(ctx context.Context, arg UserSetAvatarURLParams) error {
	_, err := q.db.Exec(ctx, userSetAvatarURL, arg.AvatarURL, arg.ID)
	return err
}

const userSetEmail = `-- name: UserSetEmail :exec
UPDATE users SET email = $1, email_verified = false, updated_at = now()
WHERE id = $2 AND email IS DISTINCT FROM $1::text::public.citext
`

type UserSetEmailParams struct {
	Email *string
	ID    string
}

// A new address is unverified; setting the current one changes nothing.
func (q *Queries) UserSetEmail(ctx context.Context, arg UserSetEmailParams) error {
	_, err := q.db.Exec(ctx, userSetEmail, arg.Email, arg.ID)
	return err
}

const userSetEmailVerified = `-- name: UserSetEmailVerified :exec
UPDATE users SET email_verified = $2, updated_at = NOW() WHERE id = $1
`

type UserSetEmailVerifiedParams struct {
	ID            string
	EmailVerified bool
}

func (q *Queries) UserSetEmailVerified(ctx context.Context, arg UserSetEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, userSetEmailVerified, arg.ID, arg.EmailVerified)
	return err
}

const userSetEmailVerifiedIfPresent = `-- name: UserSetEmailVerifiedIfPresent :execrows
UPDATE users SET email_verified = $1, updated_at = now()
WHERE id = $2 AND (NOT $1::boolean OR email IS NOT NULL)
`

type UserSetEmailVerifiedIfPresentParams struct {
	Verified bool
	ID       string
}

// Verifying needs an address; no row changes without one.
func (q *Queries) UserSetEmailVerifiedIfPresent(ctx context.Context, arg UserSetEmailVerifiedIfPresentParams) (int64, error) {
	result, err := q.db.Exec(ctx, userSetEmailVerifiedIfPresent, arg.Verified, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userSetLastLogin = `-- name: UserSetLastLogin :exec
UPDATE users SET last_login = $2, updated_at = NOW() WHERE id = $1
`

type UserSetLastLoginParams struct {
	ID        string
	LastLogin *time.Time
}

func (q *Queries) UserSetLastLogin(ctx context.Context, arg UserSetLastLoginParams) error {
	_, err := q.db.Exec(ctx, userSetLastLogin, arg.ID, arg.LastLogin)
	return err
}

const userSetMetadata = `-- name: UserSetMetadata :exec
UPDATE users SET metadata = $1::jsonb, updated_at = now()
WHERE id = $2
`

type UserSetMetadataParams struct {
	Metadata []byte
	ID       string
}

// Replaces the metadata document (PatchUserMetadata merges in Go).
func (q *Queries) UserSetMetadata(ctx context.Context, arg UserSetMetadataParams) error {
	_, err := q.db.Exec(ctx, userSetMetadata, arg.Metadata, arg.ID)
	return err
}

const userSetPhone = `-- name: UserSetPhone :exec
UPDATE users SET phone_number = $1, phone_verified = false, updated_at = now()
WHERE id = $2 AND phone_number IS DISTINCT FROM $1
`

type UserSetPhoneParams struct {
	PhoneNumber *string
	ID          string
}

func (q *Queries) UserSetPhone(ctx context.Context, arg UserSetPhoneParams) error {
	_, err := q.db.Exec(ctx, userSetPhone, arg.PhoneNumber, arg.ID)
	return err
}

const userSetPhoneVerifiedByIDAndPhone = `-- name: UserSetPhoneVerifiedByIDAndPhone :exec
UPDATE users
SET phone_verified = true
WHERE id = $1 AND phone_number = $2
`

type UserSetPhoneVerifiedByIDAndPhoneParams struct {
	ID          string
	PhoneNumber *string
}

func (q *Queries) UserSetPhoneVerifiedByIDAndPhone(ctx context.Context, arg UserSetPhoneVerifiedByIDAndPhoneParams) error {
	_, err := q.db.Exec(ctx, userSetPhoneVerifiedByIDAndPhone, arg.ID, arg.PhoneNumber)
	return err
}

const userSetPhoneVerifiedIfPresent = `-- name: UserSetPhoneVerifiedIfPresent :execrows
UPDATE users SET phone_verified = $1, updated_at = now()
WHERE id = $2 AND (NOT $1::boolean OR phone_number IS NOT NULL)
`

type UserSetPhoneVerifiedIfPresentParams struct {
	Verified bool
	ID       string
}

func (q *Queries) UserSetPhoneVerifiedIfPresent(ctx context.Context, arg UserSetPhoneVerifiedIfPresentParams) (int64, error) {
	result, err := q.db.Exec(ctx, userSetPhoneVerifiedIfPresent, arg.Verified, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userSetPreferredLanguage = `-- name: UserSetPreferredLanguage :exec
UPDATE users
SET preferred_language = $2,
    updated_at = now()
WHERE id = $1::uuid
`

type UserSetPreferredLanguageParams struct {
	ID                string
	PreferredLanguage *string
}

func (q *Queries) UserSetPreferredLanguage(ctx context.Context, arg UserSetPreferredLanguageParams) error {
	_, err := q.db.Exec(ctx, userSetPreferredLanguage, arg.ID, arg.PreferredLanguage)
	return err
}

const userSetUsernameSpelling = `-- name: UserSetUsernameSpelling :exec
UPDATE users SET username = $1, updated_at = $2::timestamptz WHERE id = $3
`

type UserSetUsernameSpellingParams struct {
	Username *string
	AtTime   time.Time
	ID       string
}

// Same name, new display spelling: no name claim, alias or cooldown.
func (q *Queries) UserSetUsernameSpelling(ctx context.Context, arg UserSetUsernameSpellingParams) error {
	_, err := q.db.Exec(ctx, userSetUsernameSpelling, arg.Username, arg.AtTime, arg.ID)
	return err
}

const userSoftDelete = `-- name: UserSoftDelete :exec
UPDATE users SET deleted_at = statement_timestamp(), updated_at = statement_timestamp() WHERE id = $1
`

func (q *Queries) UserSoftDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, userSoftDelete, id)
	return err
}

const usersByIDs = `-- name: UsersByIDs :many
SELECT id, email, username, email_verified, phone_number, phone_verified, banned_at, banned_until, ban_reason, banned_by, deleted_at, metadata, created_at, updated_at, last_login, preferred_language, avatar_url, last_renamed_at, credential_version FROM users WHERE id = ANY($1::uuid[])
`

func (q *Queries) UsersByIDs(ctx context.Context, ids []string) ([]User, error) {
	rows, err := q.db.Query(ctx, usersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.EmailVerified,
			&i.PhoneNumber,
			&i.PhoneVerified,
			&i.BannedAt,
			&i.BannedUntil,
			&i.BanReason,
			&i.BannedBy,
			&i.DeletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLogin,
			&i.PreferredLanguage,
			&i.AvatarURL,
			&i.LastRenamedAt,
			&i.CredentialVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
