// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const groupAssignmentsDeleteByUser = `-- name: GroupAssignmentsDeleteByUser :exec

DELETE FROM profiles.group_role_assignments
WHERE subject_id = $1::uuid AND subject_kind = 'user'
`

// #125 D7: pre-delete cleanup for the hard-delete/purge path. group_role_assignments
// uses a polymorphic trigger-FK (no cascade) so user assignments would orphan;
// group_invites.invited_by is ON DELETE RESTRICT so sent invites must be cleared
// before the user row is removed.
func (q *Queries) GroupAssignmentsDeleteByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, groupAssignmentsDeleteByUser, userID)
	return err
}

const groupInvitesDeleteByInviter = `-- name: GroupInvitesDeleteByInviter :exec
DELETE FROM profiles.group_invites
WHERE invited_by = $1::uuid
`

func (q *Queries) GroupInvitesDeleteByInviter(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, groupInvitesDeleteByInviter, userID)
	return err
}

const sessionsRevokeAllQuiet = `-- name: SessionsRevokeAllQuiet :exec
UPDATE profiles.refresh_sessions SET revoked_at = now() WHERE user_id = $1 AND issuer = $2
`

type SessionsRevokeAllQuietParams struct {
	UserID string
	Issuer string
}

// SessionsRevokeAllQuiet is AdminDeleteUser's pre-delete sweep; unlike
// SessionsRevokeAll it returns nothing (no per-session revoke logging).
func (q *Queries) SessionsRevokeAllQuiet(ctx context.Context, arg SessionsRevokeAllQuietParams) error {
	_, err := q.db.Exec(ctx, sessionsRevokeAllQuiet, arg.UserID, arg.Issuer)
	return err
}

const userApplyEmailChange = `-- name: UserApplyEmailChange :exec
UPDATE profiles.users SET email = lower($2::text), email_verified = true, updated_at = NOW() WHERE id = $1
`

type UserApplyEmailChangeParams struct {
	ID    string
	Email string
}

func (q *Queries) UserApplyEmailChange(ctx context.Context, arg UserApplyEmailChangeParams) error {
	_, err := q.db.Exec(ctx, userApplyEmailChange, arg.ID, arg.Email)
	return err
}

const userApplyPhoneChange = `-- name: UserApplyPhoneChange :exec
UPDATE profiles.users SET phone_number = $2, phone_verified = true, updated_at = NOW() WHERE id = $1
`

type UserApplyPhoneChangeParams struct {
	ID          string
	PhoneNumber *string
}

func (q *Queries) UserApplyPhoneChange(ctx context.Context, arg UserApplyPhoneChangeParams) error {
	_, err := q.db.Exec(ctx, userApplyPhoneChange, arg.ID, arg.PhoneNumber)
	return err
}

const userBan = `-- name: UserBan :exec
UPDATE profiles.users
SET banned_at = $1, banned_until = $2, ban_reason = $3, banned_by = $4, updated_at = NOW()
WHERE id = $5
`

type UserBanParams struct {
	BannedAt    *time.Time
	BannedUntil *time.Time
	BanReason   *string
	BannedBy    *string
	ID          string
}

func (q *Queries) UserBan(ctx context.Context, arg UserBanParams) error {
	_, err := q.db.Exec(ctx, userBan,
		arg.BannedAt,
		arg.BannedUntil,
		arg.BanReason,
		arg.BannedBy,
		arg.ID,
	)
	return err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, phone_number, username, email_verified, phone_verified, banned_at, banned_until, ban_reason, banned_by, deleted_at, biography, created_at, updated_at, last_login
FROM profiles.users WHERE email = lower($1::text)::citext
`

type UserByEmailRow struct {
	ID            string
	Email         *string
	PhoneNumber   *string
	Username      *string
	EmailVerified bool
	PhoneVerified bool
	BannedAt      *time.Time
	BannedUntil   *time.Time
	BanReason     *string
	BannedBy      *string
	DeletedAt     *time.Time
	Biography     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastLogin     *time.Time
}

func (q *Queries) UserByEmail(ctx context.Context, email string) (UserByEmailRow, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i UserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.BannedAt,
		&i.BannedUntil,
		&i.BanReason,
		&i.BannedBy,
		&i.DeletedAt,
		&i.Biography,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, email, phone_number, username, email_verified, phone_verified, banned_at, banned_until, ban_reason, banned_by, deleted_at, biography, created_at, updated_at, last_login
FROM profiles.users WHERE id = $1
`

type UserByIDRow struct {
	ID            string
	Email         *string
	PhoneNumber   *string
	Username      *string
	EmailVerified bool
	PhoneVerified bool
	BannedAt      *time.Time
	BannedUntil   *time.Time
	BanReason     *string
	BannedBy      *string
	DeletedAt     *time.Time
	Biography     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastLogin     *time.Time
}

func (q *Queries) UserByID(ctx context.Context, id string) (UserByIDRow, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i UserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.BannedAt,
		&i.BannedUntil,
		&i.BanReason,
		&i.BannedBy,
		&i.DeletedAt,
		&i.Biography,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const userByPhone = `-- name: UserByPhone :one
SELECT id, email, phone_number, username, email_verified, phone_verified, banned_at, banned_until, ban_reason, banned_by, deleted_at, biography, created_at, updated_at, last_login
FROM profiles.users WHERE phone_number = $1
`

type UserByPhoneRow struct {
	ID            string
	Email         *string
	PhoneNumber   *string
	Username      *string
	EmailVerified bool
	PhoneVerified bool
	BannedAt      *time.Time
	BannedUntil   *time.Time
	BanReason     *string
	BannedBy      *string
	DeletedAt     *time.Time
	Biography     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastLogin     *time.Time
}

func (q *Queries) UserByPhone(ctx context.Context, phoneNumber *string) (UserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, userByPhone, phoneNumber)
	var i UserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.BannedAt,
		&i.BannedUntil,
		&i.BanReason,
		&i.BannedBy,
		&i.DeletedAt,
		&i.Biography,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const userByUsername = `-- name: UserByUsername :one
SELECT id, email, phone_number, username, email_verified, phone_verified, banned_at, banned_until, ban_reason, banned_by, deleted_at, biography, created_at, updated_at, last_login
FROM profiles.users WHERE username = $1
`

type UserByUsernameRow struct {
	ID            string
	Email         *string
	PhoneNumber   *string
	Username      *string
	EmailVerified bool
	PhoneVerified bool
	BannedAt      *time.Time
	BannedUntil   *time.Time
	BanReason     *string
	BannedBy      *string
	DeletedAt     *time.Time
	Biography     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastLogin     *time.Time
}

func (q *Queries) UserByUsername(ctx context.Context, username *string) (UserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, userByUsername, username)
	var i UserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.BannedAt,
		&i.BannedUntil,
		&i.BanReason,
		&i.BannedBy,
		&i.DeletedAt,
		&i.Biography,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const userClearBan = `-- name: UserClearBan :exec
UPDATE profiles.users SET banned_at = NULL, banned_until = NULL, ban_reason = NULL, banned_by = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) UserClearBan(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, userClearBan, id)
	return err
}

const userDeleteHard = `-- name: UserDeleteHard :exec
DELETE FROM profiles.users WHERE id = $1
`

func (q *Queries) UserDeleteHard(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, userDeleteHard, id)
	return err
}

const userEmailByID = `-- name: UserEmailByID :one

SELECT email FROM profiles.users WHERE id = $1
`

// User-row queries (core/service.go).
func (q *Queries) UserEmailByID(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, userEmailByID, id)
	var email *string
	err := row.Scan(&email)
	return email, err
}

const userEmailOrUsernameExists = `-- name: UserEmailOrUsernameExists :one
SELECT EXISTS(
  SELECT 1 FROM profiles.users
  WHERE email = lower($1::text)::citext OR username = $2::text::citext
)
`

type UserEmailOrUsernameExistsParams struct {
	Email    string
	Username string
}

func (q *Queries) UserEmailOrUsernameExists(ctx context.Context, arg UserEmailOrUsernameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, userEmailOrUsernameExists, arg.Email, arg.Username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userEmailOrUsernameTaken = `-- name: UserEmailOrUsernameTaken :one
SELECT
  EXISTS(SELECT 1 FROM profiles.users WHERE email = lower($1::text)::citext)::boolean AS email_taken,
  EXISTS(SELECT 1 FROM profiles.users WHERE username = $2::text::citext)::boolean AS username_taken
`

type UserEmailOrUsernameTakenParams struct {
	Email    string
	Username string
}

type UserEmailOrUsernameTakenRow struct {
	EmailTaken    bool
	UsernameTaken bool
}

func (q *Queries) UserEmailOrUsernameTaken(ctx context.Context, arg UserEmailOrUsernameTakenParams) (UserEmailOrUsernameTakenRow, error) {
	row := q.db.QueryRow(ctx, userEmailOrUsernameTaken, arg.Email, arg.Username)
	var i UserEmailOrUsernameTakenRow
	err := row.Scan(&i.EmailTaken, &i.UsernameTaken)
	return i, err
}

const userImportInsert = `-- name: UserImportInsert :exec
INSERT INTO profiles.users (
  id, email, phone_number, username, email_verified, phone_verified,
  banned_at, banned_until, ban_reason, banned_by, metadata, created_at, updated_at
)
VALUES (
  $1::uuid, $2, $3, $4, $5, $6,
  $7, $8, $9, $10::uuid, $11::jsonb, $12, $13
)
`

type UserImportInsertParams struct {
	ID            string
	Email         *string
	PhoneNumber   *string
	Username      *string
	EmailVerified bool
	PhoneVerified bool
	BannedAt      *time.Time
	BannedUntil   *time.Time
	BanReason     *string
	BannedBy      *string
	Metadata      []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UserImportInsert(ctx context.Context, arg UserImportInsertParams) error {
	_, err := q.db.Exec(ctx, userImportInsert,
		arg.ID,
		arg.Email,
		arg.PhoneNumber,
		arg.Username,
		arg.EmailVerified,
		arg.PhoneVerified,
		arg.BannedAt,
		arg.BannedUntil,
		arg.BanReason,
		arg.BannedBy,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const userImportUpdate = `-- name: UserImportUpdate :one
UPDATE profiles.users
SET email = COALESCE($1, email),
    phone_number = COALESCE($2, phone_number),
    username = $3,
    email_verified = $4,
    phone_verified = $5,
    banned_at = $6,
    banned_until = $7,
    ban_reason = $8,
    banned_by = $9::uuid,
    metadata = COALESCE(metadata, '{}'::jsonb) || $10::jsonb,
    created_at = CASE WHEN $11 < created_at THEN $11 ELSE created_at END,
    updated_at = $12
WHERE id = $13::uuid
RETURNING id::text
`

type UserImportUpdateParams struct {
	Email         *string
	PhoneNumber   *string
	Username      *string
	EmailVerified bool
	PhoneVerified bool
	BannedAt      *time.Time
	BannedUntil   *time.Time
	BanReason     *string
	BannedBy      *string
	Metadata      []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ID            string
}

func (q *Queries) UserImportUpdate(ctx context.Context, arg UserImportUpdateParams) (string, error) {
	row := q.db.QueryRow(ctx, userImportUpdate,
		arg.Email,
		arg.PhoneNumber,
		arg.Username,
		arg.EmailVerified,
		arg.PhoneVerified,
		arg.BannedAt,
		arg.BannedUntil,
		arg.BanReason,
		arg.BannedBy,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const userInsert = `-- name: UserInsert :one
INSERT INTO profiles.users (id, email, username)
VALUES ($1::uuid, NULLIF(lower($2::text), ''), $3)
RETURNING id, email, username, email_verified, banned_at, deleted_at
`

type UserInsertParams struct {
	ID       string
	Email    string
	Username *string
}

type UserInsertRow struct {
	ID            string
	Email         *string
	Username      *string
	EmailVerified bool
	BannedAt      *time.Time
	DeletedAt     *time.Time
}

func (q *Queries) UserInsert(ctx context.Context, arg UserInsertParams) (UserInsertRow, error) {
	row := q.db.QueryRow(ctx, userInsert, arg.ID, arg.Email, arg.Username)
	var i UserInsertRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.EmailVerified,
		&i.BannedAt,
		&i.DeletedAt,
	)
	return i, err
}

const userLastRenamedAt = `-- name: UserLastRenamedAt :one
SELECT renamed_at
FROM   profiles.user_renames
WHERE  user_id = $1::uuid
ORDER  BY renamed_at DESC
LIMIT  1
`

func (q *Queries) UserLastRenamedAt(ctx context.Context, userID string) (time.Time, error) {
	row := q.db.QueryRow(ctx, userLastRenamedAt, userID)
	var renamed_at time.Time
	err := row.Scan(&renamed_at)
	return renamed_at, err
}

const userPasswordInsert = `-- name: UserPasswordInsert :exec
INSERT INTO profiles.user_passwords (user_id, password_hash, hash_algo)
VALUES ($1, $2, 'argon2id')
`

type UserPasswordInsertParams struct {
	UserID       string
	PasswordHash string
}

func (q *Queries) UserPasswordInsert(ctx context.Context, arg UserPasswordInsertParams) error {
	_, err := q.db.Exec(ctx, userPasswordInsert, arg.UserID, arg.PasswordHash)
	return err
}

const userPasswordRow = `-- name: UserPasswordRow :one
SELECT password_hash, hash_algo, COALESCE(hash_params, '{}'::jsonb)::jsonb AS hash_params
FROM profiles.user_passwords WHERE user_id = $1
`

type UserPasswordRowRow struct {
	PasswordHash string
	HashAlgo     string
	HashParams   []byte
}

func (q *Queries) UserPasswordRow(ctx context.Context, userID string) (UserPasswordRowRow, error) {
	row := q.db.QueryRow(ctx, userPasswordRow, userID)
	var i UserPasswordRowRow
	err := row.Scan(&i.PasswordHash, &i.HashAlgo, &i.HashParams)
	return i, err
}

const userPasswordUpsert = `-- name: UserPasswordUpsert :exec
INSERT INTO profiles.user_passwords (user_id, password_hash, hash_algo, hash_params)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET password_hash = EXCLUDED.password_hash, hash_algo = EXCLUDED.hash_algo, hash_params = EXCLUDED.hash_params, password_updated_at = NOW()
`

type UserPasswordUpsertParams struct {
	UserID       string
	PasswordHash string
	HashAlgo     string
	HashParams   []byte
}

func (q *Queries) UserPasswordUpsert(ctx context.Context, arg UserPasswordUpsertParams) error {
	_, err := q.db.Exec(ctx, userPasswordUpsert,
		arg.UserID,
		arg.PasswordHash,
		arg.HashAlgo,
		arg.HashParams,
	)
	return err
}

const userPhoneOrUsernameExists = `-- name: UserPhoneOrUsernameExists :one
SELECT EXISTS(
  SELECT 1 FROM profiles.users
  WHERE phone_number = $1::text OR username = $2::text::citext
)
`

type UserPhoneOrUsernameExistsParams struct {
	Phone    string
	Username string
}

func (q *Queries) UserPhoneOrUsernameExists(ctx context.Context, arg UserPhoneOrUsernameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, userPhoneOrUsernameExists, arg.Phone, arg.Username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userPhoneOrUsernameTaken = `-- name: UserPhoneOrUsernameTaken :one
SELECT
  EXISTS(SELECT 1 FROM profiles.users WHERE phone_number = $1::text)::boolean AS phone_taken,
  EXISTS(SELECT 1 FROM profiles.users WHERE username = $2::text::citext)::boolean AS username_taken
`

type UserPhoneOrUsernameTakenParams struct {
	Phone    string
	Username string
}

type UserPhoneOrUsernameTakenRow struct {
	PhoneTaken    bool
	UsernameTaken bool
}

func (q *Queries) UserPhoneOrUsernameTaken(ctx context.Context, arg UserPhoneOrUsernameTakenParams) (UserPhoneOrUsernameTakenRow, error) {
	row := q.db.QueryRow(ctx, userPhoneOrUsernameTaken, arg.Phone, arg.Username)
	var i UserPhoneOrUsernameTakenRow
	err := row.Scan(&i.PhoneTaken, &i.UsernameTaken)
	return i, err
}

const userPreferredLanguage = `-- name: UserPreferredLanguage :one
SELECT COALESCE(preferred_language, '')::text AS language
FROM profiles.users
WHERE id = $1::uuid
`

func (q *Queries) UserPreferredLanguage(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, userPreferredLanguage, id)
	var language string
	err := row.Scan(&language)
	return language, err
}

const userRenameInsert = `-- name: UserRenameInsert :exec
INSERT INTO profiles.user_renames (user_id, from_slug)
VALUES ($1::uuid, $2)
`

type UserRenameInsertParams struct {
	UserID   string
	FromSlug string
}

func (q *Queries) UserRenameInsert(ctx context.Context, arg UserRenameInsertParams) error {
	_, err := q.db.Exec(ctx, userRenameInsert, arg.UserID, arg.FromSlug)
	return err
}

const userRestore = `-- name: UserRestore :exec
UPDATE profiles.users SET deleted_at = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) UserRestore(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, userRestore, id)
	return err
}

const userSetBiography = `-- name: UserSetBiography :exec
UPDATE profiles.users SET biography = $2, updated_at = NOW() WHERE id = $1
`

type UserSetBiographyParams struct {
	ID        string
	Biography *string
}

func (q *Queries) UserSetBiography(ctx context.Context, arg UserSetBiographyParams) error {
	_, err := q.db.Exec(ctx, userSetBiography, arg.ID, arg.Biography)
	return err
}

const userSetEmailAndUnverify = `-- name: UserSetEmailAndUnverify :exec
UPDATE profiles.users SET email = lower($2::text), email_verified = false, updated_at = NOW() WHERE id = $1
`

type UserSetEmailAndUnverifyParams struct {
	ID    string
	Email string
}

func (q *Queries) UserSetEmailAndUnverify(ctx context.Context, arg UserSetEmailAndUnverifyParams) error {
	_, err := q.db.Exec(ctx, userSetEmailAndUnverify, arg.ID, arg.Email)
	return err
}

const userSetEmailAndVerified = `-- name: UserSetEmailAndVerified :exec
UPDATE profiles.users SET email = lower($2::text), email_verified = true, updated_at = NOW() WHERE id = $1
`

type UserSetEmailAndVerifiedParams struct {
	ID    string
	Email string
}

func (q *Queries) UserSetEmailAndVerified(ctx context.Context, arg UserSetEmailAndVerifiedParams) error {
	_, err := q.db.Exec(ctx, userSetEmailAndVerified, arg.ID, arg.Email)
	return err
}

const userSetEmailVerified = `-- name: UserSetEmailVerified :exec
UPDATE profiles.users SET email_verified = $2, updated_at = NOW() WHERE id = $1
`

type UserSetEmailVerifiedParams struct {
	ID            string
	EmailVerified bool
}

func (q *Queries) UserSetEmailVerified(ctx context.Context, arg UserSetEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, userSetEmailVerified, arg.ID, arg.EmailVerified)
	return err
}

const userSetLastLogin = `-- name: UserSetLastLogin :exec
UPDATE profiles.users SET last_login = $2, updated_at = NOW() WHERE id = $1
`

type UserSetLastLoginParams struct {
	ID        string
	LastLogin *time.Time
}

func (q *Queries) UserSetLastLogin(ctx context.Context, arg UserSetLastLoginParams) error {
	_, err := q.db.Exec(ctx, userSetLastLogin, arg.ID, arg.LastLogin)
	return err
}

const userSetPhoneAndVerified = `-- name: UserSetPhoneAndVerified :exec
UPDATE profiles.users
SET phone_number = $2, phone_verified = $3, updated_at = NOW()
WHERE id = $1
`

type UserSetPhoneAndVerifiedParams struct {
	ID            string
	PhoneNumber   *string
	PhoneVerified bool
}

func (q *Queries) UserSetPhoneAndVerified(ctx context.Context, arg UserSetPhoneAndVerifiedParams) error {
	_, err := q.db.Exec(ctx, userSetPhoneAndVerified, arg.ID, arg.PhoneNumber, arg.PhoneVerified)
	return err
}

const userSetPhoneVerifiedByID = `-- name: UserSetPhoneVerifiedByID :exec
UPDATE profiles.users SET phone_verified = $2, updated_at = NOW() WHERE id = $1
`

type UserSetPhoneVerifiedByIDParams struct {
	ID            string
	PhoneVerified bool
}

func (q *Queries) UserSetPhoneVerifiedByID(ctx context.Context, arg UserSetPhoneVerifiedByIDParams) error {
	_, err := q.db.Exec(ctx, userSetPhoneVerifiedByID, arg.ID, arg.PhoneVerified)
	return err
}

const userSetPhoneVerifiedByIDAndPhone = `-- name: UserSetPhoneVerifiedByIDAndPhone :exec
UPDATE profiles.users
SET phone_verified = true
WHERE id = $1 AND phone_number = $2
`

type UserSetPhoneVerifiedByIDAndPhoneParams struct {
	ID          string
	PhoneNumber *string
}

func (q *Queries) UserSetPhoneVerifiedByIDAndPhone(ctx context.Context, arg UserSetPhoneVerifiedByIDAndPhoneParams) error {
	_, err := q.db.Exec(ctx, userSetPhoneVerifiedByIDAndPhone, arg.ID, arg.PhoneNumber)
	return err
}

const userSetPreferredLanguage = `-- name: UserSetPreferredLanguage :exec
UPDATE profiles.users
SET preferred_language = $2,
    updated_at = now()
WHERE id = $1::uuid
`

type UserSetPreferredLanguageParams struct {
	ID                string
	PreferredLanguage *string
}

func (q *Queries) UserSetPreferredLanguage(ctx context.Context, arg UserSetPreferredLanguageParams) error {
	_, err := q.db.Exec(ctx, userSetPreferredLanguage, arg.ID, arg.PreferredLanguage)
	return err
}

const userSetUsername = `-- name: UserSetUsername :exec
UPDATE profiles.users SET username = $2, updated_at = NOW() WHERE id = $1
`

type UserSetUsernameParams struct {
	ID       string
	Username *string
}

func (q *Queries) UserSetUsername(ctx context.Context, arg UserSetUsernameParams) error {
	_, err := q.db.Exec(ctx, userSetUsername, arg.ID, arg.Username)
	return err
}

const userSoftDelete = `-- name: UserSoftDelete :exec
UPDATE profiles.users SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) UserSoftDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, userSoftDelete, id)
	return err
}

const userUsernameByID = `-- name: UserUsernameByID :one
SELECT username::text FROM profiles.users WHERE id = $1::uuid
`

func (q *Queries) UserUsernameByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, userUsernameByID, id)
	var username string
	err := row.Scan(&username)
	return username, err
}

const userUsernameExists = `-- name: UserUsernameExists :one
SELECT EXISTS(SELECT 1 FROM profiles.users WHERE username = $1)
`

func (q *Queries) UserUsernameExists(ctx context.Context, username *string) (bool, error) {
	row := q.db.QueryRow(ctx, userUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const usersPurgeCandidates = `-- name: UsersPurgeCandidates :many
SELECT id::text
FROM profiles.users
WHERE deleted_at IS NOT NULL AND deleted_at < $1
ORDER BY deleted_at ASC
LIMIT $2::bigint
`

type UsersPurgeCandidatesParams struct {
	Cutoff  *time.Time
	MaxRows int64
}

func (q *Queries) UsersPurgeCandidates(ctx context.Context, arg UsersPurgeCandidatesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, usersPurgeCandidates, arg.Cutoff, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
